### PR TITLE
Backport lazy collection init

### LINKED ISSUE #3596: [Backport] Lazy collection init
### Original feature issue

- Issue: #3360
- PR: #3363

### Target release

- [x] release33
- [ ] release32
- [ ] release30

### Reason

The SQLite backend support backport request is related to the performance desired that surfaced in https://github.com/cobbler/cobbler/discussions/3578.

### PR DESCRIPTION
**Pull request by SchoolGuy**
## Linked Items

Fixes #3596

## Description

This PR attempts to backport the lazy collection init. This will be off per default.

## Behaviour changes

Old: Cobbler wasn't available until all items are fully loaded.

New: Cobbler will startup up with only the item names in memory until the item is first accessed.

## Category

This is related to a:

- [ ] Bugfix
- [x] Feature
- [ ] Packaging
- [ ] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [x] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [ ] No tests required

### CODE REVIEW

**Comment by SchoolGuy** [comment]
I will try to test the PR as soon as possible in regard to the performance gains that it potentially presents.

**Comment by SchoolGuy** [comment]
@tpw56j Do you have an idea for the backport of how to prevent the recursion error for the IP addresses? I don't want to introduce breaking changes for this one and as such I am not sure where to start debugging/fixing at the moment...

**Comment by SchoolGuy** [comment]
@tpw56j Something like this:

```
Mar 05 11:50:58 cobbler cobblerd[2602]: INFO | Exception occurred: <class 'RecursionError'>
Mar 05 11:50:58 cobbler cobblerd[2602]: INFO | Exception value: maximum recursion depth exceeded while calling a Python object
Mar 05 11:50:58 cobbler cobblerd[2602]: INFO | Exception Info:
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/remote.py", line 3771, in _dispatch
Mar 05 11:50:58 cobbler cobblerd[2602]:     return method_handle(*params)
Mar 05 11:50:58 cobbler cobblerd[2602]:            ^^^^^^^^^^^^^^^^^^^^^^
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/remote.py", line 941, in get_items
Mar 05 11:50:58 cobbler cobblerd[2602]:     items = [x.to_dict() for x in self.api.get_items(what)]
Mar 05 11:50:58 cobbler cobblerd[2602]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/remote.py", line 941, in <listcomp>
Mar 05 11:50:58 cobbler cobblerd[2602]:     items = [x.to_dict() for x in self.api.get_items(what)]
Mar 05 11:50:58 cobbler cobblerd[2602]:              ^^^^^^^^^^^
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 957, in to_dict
Mar 05 11:50:58 cobbler cobblerd[2602]:     self.deserialize()
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 1034, in deserialize
Mar 05 11:50:58 cobbler cobblerd[2602]:     self.from_dict(item_dict)
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 834, in from_dict
Mar 05 11:50:58 cobbler cobblerd[2602]:     super().from_dict(dictionary)
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 940, in from_dict
Mar 05 11:50:58 cobbler cobblerd[2602]:     setattr(self, lowered_key, dictionary[key])
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 931, in interfaces
Mar 05 11:50:58 cobbler cobblerd[2602]:     network_iface.from_dict(value[key])
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 67, in from_dict
Mar 05 11:50:58 cobbler cobblerd[2602]:     setattr(self, key, dictionary[key])
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 274, in ip_address
Mar 05 11:50:58 cobbler cobblerd[2602]:     matched = self.__api.find_items("system", {"ip_address": address})
Mar 05 11:50:58 cobbler cobblerd[2602]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1020, in find_items
Mar 05 11:50:58 cobbler cobblerd[2602]:     return self.__find_with_collection(
Mar 05 11:50:58 cobbler cobblerd[2602]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1027, in __find_with_collection
Mar 05 11:50:58 cobbler cobblerd[2602]:     return items.find(
Mar 05 11:50:58 cobbler cobblerd[2602]:            ^^^^^^^^^^^
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/cobbler_collections/collection.py", line 141, in find
Mar 05 11:50:58 cobbler cobblerd[2602]:     obj.deserialize()
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 1034, in deserialize
Mar 05 11:50:58 cobbler cobblerd[2602]:     self.from_dict(item_dict)
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 834, in from_dict
Mar 05 11:50:58 cobbler cobblerd[2602]:     super().from_dict(dictionary)
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 940, in from_dict
Mar 05 11:50:58 cobbler cobblerd[2602]:     setattr(self, lowered_key, dictionary[key])
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 931, in interfaces
Mar 05 11:50:58 cobbler cobblerd[2602]:     network_iface.from_dict(value[key])
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 67, in from_dict
Mar 05 11:50:58 cobbler cobblerd[2602]:     setattr(self, key, dictionary[key])
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 274, in ip_address
Mar 05 11:50:58 cobbler cobblerd[2602]:     matched = self.__api.find_items("system", {"ip_address": address})
Mar 05 11:50:58 cobbler cobblerd[2602]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1020, in find_items
Mar 05 11:50:58 cobbler cobblerd[2602]:     return self.__find_with_collection(
Mar 05 11:50:58 cobbler cobblerd[2602]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1027, in __find_with_collection
Mar 05 11:50:58 cobbler cobblerd[2602]:     return items.find(
Mar 05 11:50:58 cobbler cobblerd[2602]:            ^^^^^^^^^^^
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/cobbler_collections/collection.py", line 141, in find
Mar 05 11:50:58 cobbler cobblerd[2602]:     obj.deserialize()
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 1034, in deserialize
Mar 05 11:50:58 cobbler cobblerd[2602]:     self.from_dict(item_dict)
Mar 05 11:50:58 cobbler cobblerd[2602]:   File "/usr/lib/python3.11/site-packages/cob
....
```

**Comment by tpw56j** [comment]
One possible error could be here:
https://github.com/cobbler/cobbler/blob/a8e8da9b3d05edce94150e913cd157ad7de70d6a/cobbler/items/item.py#L973

It should be like this:
serialized_interfaces[interface_key] = interfaces[interface_key].to_dict(**resolved**)

**Comment by SchoolGuy** [comment]
@tpw56j Yes that is certainly a bug but this is the inverse direction that is shown in the stacktrace. Any more ideas?

**Comment by tpw56j** [comment]
The recursion occurs here:
https://github.com/cobbler/cobbler/blob/b8a7f7a6ce4a2b28f691896bee99ce94dbcb7401/cobbler/items/system.py#L254

The interface as a whole must have `LazyProperty`, but not its individual properties.
Check the NetworkInterface class in the main branch and take the decorators from there.

**Comment by SchoolGuy** [comment]
@tpw56j Sorry to say but it wasn't enough to fix the issue. We still have recursion during adding a new system since it tries to deserialize during deserializing (`ip_address`):

```
Traceback (most recent call last):
  File "/root/./fillup.py", line 40, in <module>
    add_system(api, 1, str(next(hosts_iterator)))
  File "/root/./fillup.py", line 20, in add_system
    system.modify_interface({"macaddress-default": "random", "ip_address-default": ip})
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 945, in modify_interface
    self.interfaces[interface].modify_interface({key: interface_values[key]})
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 713, in modify_interface
    self.mac_address = value
    ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 305, in mac_address
    address = utils.get_random_mac(self.__api)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/utils.py", line 324, in get_random_mac
    while systems.find(mac_address=mac):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/cobbler_collections/collection.py", line 141, in find
    obj.deserialize()
  File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 1034, in deserialize
    self.from_dict(item_dict)
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 834, in from_dict
    super().from_dict(dictionary)
  File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 940, in from_dict
    setattr(self, lowered_key, dictionary[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 931, in interfaces
    network_iface.from_dict(value[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 67, in from_dict
    setattr(self, key, dictionary[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 274, in ip_address
    matched = self.__api.find_items("system", {"ip_address": address})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1020, in find_items
    return self.__find_with_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1027, in __find_with_collection
    return items.find(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/cobbler_collections/collection.py", line 141, in find
    obj.deserialize()
  File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 1034, in deserialize
    self.from_dict(item_dict)
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 834, in from_dict
    super().from_dict(dictionary)
  File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 940, in from_dict
    setattr(self, lowered_key, dictionary[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 931, in interfaces
    network_iface.from_dict(value[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 67, in from_dict
    setattr(self, key, dictionary[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 274, in ip_address
    matched = self.__api.find_items("system", {"ip_address": address})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1020, in find_items
    return self.__find_with_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1027, in __find_with_collection
    return items.find(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/cobbler_collections/collection.py", line 141, in find
    obj.deserialize()
  File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 1034, in deserialize
    self.from_dict(item_dict)
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 834, in from_dict
    super().from_dict(dictionary)
  File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 940, in from_dict
    setattr(self, lowered_key, dictionary[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 931, in interfaces
    network_iface.from_dict(value[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 67, in from_dict
    setattr(self, key, dictionary[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 274, in ip_address
    matched = self.__api.find_items("system", {"ip_address": address})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1020, in find_items
    return self.__find_with_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1027, in __find_with_collection
    return items.find(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/cobbler_collections/collection.py", line 141, in find
    obj.deserialize()
  File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 1034, in deserialize
    self.from_dict(item_dict)
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 834, in from_dict
    super().from_dict(dictionary)
  File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 940, in from_dict
    setattr(self, lowered_key, dictionary[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 931, in interfaces
    network_iface.from_dict(value[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 67, in from_dict
    setattr(self, key, dictionary[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 274, in ip_address
    matched = self.__api.find_items("system", {"ip_address": address})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1020, in find_items
    return self.__find_with_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1027, in __find_with_collection
    return items.find(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/cobbler_collections/collection.py", line 141, in find
    obj.deserialize()
  File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 1034, in deserialize
    self.from_dict(item_dict)
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 834, in from_dict
    super().from_dict(dictionary)
  File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 940, in from_dict
    setattr(self, lowered_key, dictionary[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 931, in interfaces
    network_iface.from_dict(value[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 67, in from_dict
    setattr(self, key, dictionary[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 274, in ip_address
    matched = self.__api.find_items("system", {"ip_address": address})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1020, in find_items
    return self.__find_with_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 1027, in __find_with_collection
    return items.find(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cobbler/cobbler_collections/collection.py", line 141, in find
    obj.deserialize()
  File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 1034, in deserialize
    self.from_dict(item_dict)
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 834, in from_dict
    super().from_dict(dictionary)
  File "/usr/lib/python3.11/site-packages/cobbler/items/item.py", line 940, in from_dict
    setattr(self, lowered_key, dictionary[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 931, in interfaces
    network_iface.from_dict(value[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 67, in from_dict
    setattr(self, key, dictionary[key])
  File "/usr/lib/python3.11/site-packages/cobbler/items/system.py", line 274, in ip_address
    matched = self.__api.find_items("system", {"ip_address": address})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by SchoolGuy** [comment]
This bug is also present on `main`:

```
95f3a3d32d93:~ # cobbler system add --name=testsys2 --mac-address="random" --ip-address="192.168.0.6" --profile="testprof"
exception on server: maximum recursion depth exceeded while calling a Python object
95f3a3d32d93:~ # cobbler version
Cobbler 3.4.0
  source: ?, ?
  build time: Tue Mar  5 17:20:55 2024
```

**Comment by SchoolGuy** [comment]
@tpw56j I have pushed an experimental commit, it solves the chicken-egg problem that I described. I would love it if you would play the devil's advocate for my change and propose a better solution if you can offer one!

**Comment by tpw56j** [comment]
Your commit breaks the logic of `collection.find` and in other places in the code it will stop working as expected.
The problem here is that we are trying to deserialize an object that has not yet been initialized. So I propose another fix: 

```diff
     def deserialize(self) -> None:
         """
         Deserializes the object itself and, if necessary, recursively all the objects it depends on.
         """
 
         def deserialize_ancestor(ancestor_item_type: str, ancestor_name: str):
             if ancestor_name not in {"", enums.VALUE_INHERITED}:
                 ancestor = self.api.get_items(ancestor_item_type).get(ancestor_name)
                 if ancestor is not None and not ancestor.inmemory:
                     ancestor.deserialize()
 
+        if not self._has_initialized:
+            return
+
         item_dict = self.api.deserialize_item(self)
         if item_dict["inmemory"]:
             for ancestor_item_type, ancestor_deps in Item.TYPE_DEPENDENCIES.items():
```
This solves the chicken-egg problem.

Along the way, I found another bug in `utils.get_random_mac`, which makes searching by passing an array parameter instead of a string to `collection.find`:
```
# cobbler system add --name=testsys2 --mac-address="random" --ip-address="192.168.0.7" --profile="profile02"
exception on server: 'list' object has no attribute 'startswith'
```

Fix:
```diff
     else:
         raise CX("virt mac assignment not yet supported")
 
     result = ":".join([f"{x:02x}" for x in mac])
     systems = api_handle.systems()
-    while systems.find(mac_address=mac):
+    while systems.find(mac_address=result):
         result = get_random_mac(api_handle)
 
     return result
```

**Comment by SchoolGuy** [comment]
@SchoolGuy Thanks for the help! I will try it out after I slept. Recovering my k8s cluster atm. 😴

**Comment by tpw56j** [comment]
I was haunted last night by your idea of a lazy start with 500,000 target items.
The first search after the start in the collection by an attribute that is not a name will lead to the need to deserialize all items of the collection. This will take a long time and will result in a time-out error while executing such a command. 

Therefore I suggest:
1. return to the original version of my commit with autostart of the task when cobbler starts, which deserializes items during idle time.
2. check whether the deserialization task has completed when executing commands that require the presence of all collection items in memory. If not all items of the desired collection have not yet been deserialized, then return a message like this "Please be patient, cobbler is not yet ready to execute this command. Retry the command in approximately NNN hours/min/sec." We can estimate the readiness time by the number of items already deserialized by this task.

**Comment by SchoolGuy** [comment]
@tpw56j Thanks a lot :)

**Comment by tpw56j** [comment]
I tested on my laptop the effect of `lazy_start` on the time of deserialization of collections during cobbler startup.
Most of the time is spent parsing json regardless of the database type used. Replacing `python-json` with `python-orjson` or `python-ujson` did not improve performance. I will prepare a PR for the main branch on bugs regarding `lazy_start ` found during testing.

In the current implementation, `lazy_start` only defers the problem to a later time. After starting with `lazy_start=True`, I was unable to create the 1001st system due to a timeout during the long execution of deserializing all items of the collection in `collection.find()`. Therefore, I will try to prepare a PR to solve it.

Here are my results for 1000 target systems.

Timing of serializers.file deserialize() based on the results of 3 measurements
|lazy_start|json|orjson|ujson|
|------------|---------|---------|---------|
|False|69.91 - 89.20|70.52 - 72.97|73.21 - 74.13|
|True|0.0629 - 0.0684|

serializers.sqlite
|lazy_start|json|
|------------|---------|
|False|65.55 - 81.53|
|True|0.0585 - 0.06425|

serializers.mongodb
|lazy_start|json|
|------------|---------|
|False|68.82 - 72.24|
|True|0.0602 - 0.0648|

**Comment by SchoolGuy** [comment]
@tpw56j After being haunted by my infrastructure at work I was finally able to apply your two-line fix to my PR. In terms of functionality do you believe that this PR is finished?

The rest of my performance concerns I would like to discuss in the issue we have for this (#3341).

**Comment by tpw56j** [comment]
@SchoolGuy  I think this fix is not enough to solve the problem. To fix the bug in the main branch #3654, I had to additionally monitor the deserialization state of the entire collection to avoid recursion. The problem arises if, when deserializing an item, it is necessary to check the attributes of this item for validity among other items of the same or another collection. For example, check for duplicate mac addresses. In this case, `collection.find()` should act the same as when loading a collection when the cobbler starts, without a lazy start. Namely, check attributes only among already loaded items and do not try to read remaining items from disk because this collection is already being read in its entirety. And to implement this behaviour I had to add code to the `collection.py`.
To avoid recursion, we need to include this code here too and carefully check that it completely solves the problem.

**Comment by SchoolGuy** [comment]
@tpw56j Thanks for your take on this. I will cherry pick the required changes from your PR tomorrow.

**Comment by SchoolGuy** [comment]
This PR isn't actually closed. We still want the backport.

**Pull request closed without merging**
