### PR TITLE
config: add anolis distro

### PR DESCRIPTION
**Pull request by geliwei**
Signed-off-by: Liwei Ge <geliwei@openanolis.org>

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@geliwei Is it possible for you to add an `import-anolis` test to our integration testsuite? I would love to know if this is actually working and we can validate that it is working. If I am not mistaken the following is the website for the distro? - https://openanolis.cn/

**Comment by geliwei** [comment]
> 

Sure, I just did a test with two kvm box. I would happy to compose some testcases for Anolis distro.
And yes, https://openanolis.cn/ is the official website.

**Comment by SchoolGuy** [comment]
@geliwei If you would like to run Cobbler on top of Anolis... Is the `distro` module able to detect that distro correctly? We are using this in some parts of Cobbler to detect the host systems and depending on that use one path or the other...

**Comment by geliwei** [comment]
> @geliwei If you would like to run Cobbler on top of Anolis... Is the `distro` module able to detect that distro correctly? We are using this in some parts of Cobbler to detect the host systems and depending on that use one path or the other...
Yes, the distro module could work after I apply changes to utils.py.
[GCC 8.3.1 20191121 (Anolis 8.3.1-5.0.1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distro
>>> print (distro.name())
Anolis OS
>>> 

[root@localhost cobbler]# systemctl status cobblerd
● cobblerd.service - Cobbler Helper Daemon
   Loaded: loaded (/usr/lib/systemd/system/cobblerd.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2022-03-31 03:25:03 EDT; 38min ago
 Main PID: 20424 (cobblerd)
    Tasks: 1 (limit: 101363)
   Memory: 32.0M
   CGroup: /system.slice/cobblerd.service
           └─20424 /usr/bin/python3.6 -s /usr/bin/cobblerd -F

Mar 31 03:25:03 localhost.localdomain systemd[1]: Started Cobbler Helper Daemon.
[root@localhost cobbler]# cat /etc/os-release 
NAME="Anolis OS"
VERSION="8.2"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.2"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.2"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"

And the import test failed because of I didn't filter directory in index file. I have fixed that in the new push.

**Review by SchoolGuy — APPROVED** [review]
The failing `reposync` tests can be safely ignored. I will accept this PR thus.

**Comment by geliwei** [comment]
> @geliwei Do you have anything you want to add or can we merge?

Thank you for the review. no other changes,  please go ahead.

**Comment by SchoolGuy** [comment]
@geliwei I just saw that your commit is unsigned. Could you do that or is that too much to ask?

**Comment by geliwei** [comment]
> @geliwei I just saw that your commit is unsigned. Could you do that or is that too much to ask?

push new commit that signed with gpg key

**Comment by SchoolGuy** [comment]
@geliwei We added support for alma in the meantime. I am deeply sorry but could you please rebase this one last time?

**Comment by geliwei** [comment]
> @geliwei We added support for alma in the meantime. I am deeply sorry but could you please rebase this one last time?

new commit pushed

**Pull request merged**
