### PR TITLE
Disable cache

### PR DESCRIPTION
**Pull request by holmesb**
Disabling cache for time-being since it breaks XMLRPC API.  Fixes issue #2386.  Also [issue #31](https://github.com/terraform-providers/terraform-provider-cobbler/issues/31) in the Terraform Cobbler provider.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@holmesb At some point we anyway need to be able to have a switch for use Cache vs use no Cache. Thus I would appreciate after you have resolved the conflict that instead of just commenting this out we do this properly and create a switch for this in the settings. When this is in, I will create a PR which will state that when someone is using the xmlrpc api with the Terraform provider the Cache needs to be disabled.

**Comment by SchoolGuy** [comment]
Also I would love if you wouldn't delete the branch from the other PR so we can possibly use this at some point.

**Comment by SchoolGuy** [comment]
@holmesb If you resolve the conflict we are good to merge!

**Comment by hbokh** [comment]
@SchoolGuy Off topic: is there any weight in my approval? With yours and mine there are two approving reviews, but because my approvals are always grey (not green like yours), I wonder if they really count.

**Comment by SchoolGuy** [comment]
@hbokh They count to me. I don't know exactly why they are not green but I will have a look.

**Comment by SchoolGuy** [comment]
@holmesb Many thanks for this one!

**Comment by hbokh** [comment]
> @hbokh They count to me. I don't know exactly why they are not green but I will have a look.

Found it by hovering over the grey checkmark:
_Only reviews by reviewers with write access count towards mergeability_

So mine do not count...

**Comment by SchoolGuy** [comment]
@hbokh I forgot to add you to the Hackers Group

**Pull request merged**
