### PR TITLE
Added/changed packages for Ubuntu 18.04

### PR DESCRIPTION
**Pull request by Oddly**
Added/changed package names for Ubuntu 18.04.

### CODE REVIEW

**Review by SchoolGuy — APPROVED** [review]
LGTM

**Review by dansou901 — CHANGES_REQUESTED** [review]
This is wrong. The module mod_ssl is included in the apache2 package in Ubuntu already, libapache2-mod-ssl doesn't even exist anymore. For mod_wsgi there are two options: libapache2-mod-wsgi for Python 2 (which is for the old Cobbler 2.8.x which no one should install anymore) and libapache2-mod-wsgi-py3 for the current Cobbler 3.x. So please update the lists first before merging.

**Review by SchoolGuy — CHANGES_REQUESTED** [review]
I will revoke my approval until the changes from @dansou901 are addressed.

**Comment by SchoolGuy** [comment]
Nothing happened since September. Thus closing this one. Please reopen when the changes are applied.

**Pull request closed without merging**
