### PR TITLE
Let koan support CentOS 7 version numbering scheme

### PR DESCRIPTION
**Pull request by qingbo**
Borrowing code of os_release from cobbler/utils.py
Ref: http://lwn.net/Articles/601914/

### CODE REVIEW

**Comment by opoplawski** [comment]
Can we backport to 2.6?

**Comment by celesteking** [comment]
Guys, this still doesn't work?

```ruby
koan-2.6.10-1.el7.noarch
virt-install-1.2.1-8.el7.noarch

# koan -v  -s xxx  --wait=30  --system xxx
- looking for Cobbler at http://xx:80/cobbler_api
- ['/usr/bin/virt-install', '--version']
1.2.1
<type 'exceptions.Exception'>
expected version format differs
  File "/usr/lib/python2.7/site-packages/koan/app.py", line 274, in main
    k.run()
   File "/usr/lib/python2.7/site-packages/koan/app.py", line 424, in run
    self.virt()
   File "/usr/lib/python2.7/site-packages/koan/app.py", line 844, in virt
    return self.net_install(after_download)
   File "/usr/lib/python2.7/site-packages/koan/app.py", line 636, in net_install
    if len(version_str) == 0 and not utils.check_version_greater_or_equal(version_str.strip(), "0.2.0"):
   File "/usr/lib/python2.7/site-packages/koan/utils.py", line 591, in check_version_greater_or_equal
    raise Exception("expected version format differs")

# rpm -q --changelog koan |grep -i versio
- Backport upstream patch to fix centos version detection (bug #1201879)

```

**Comment by opoplawski** [comment]
@celesteking The issue you are seeing was addressed by pull #995, not this one.

**Comment by celesteking** [comment]
@opoplawski, I hope you understand this is happening right now with recent versions of official packages, which means koan on EL7 is currently unusable. Was there any regression introduced recently?

**Pull request merged**
