### PR TITLE
added trigger for background tasks

### PR DESCRIPTION
**Pull request by santosh0705**
patch for feature request #1502
Can add external triggers (python module and old style) to background tasks.
Need to create directories for each tasks for old styled trigger at /var/lib/cobbler/triggers
ex: for import task have to create following directories:
/var/lib/cobbler/triggers/task/import/pre & /var/lib/cobbler/triggers/task/import/post

### CODE REVIEW

**Comment by jmaas** [comment]
Please fix the code quality regressions and also verify codestyle with 'make qa' before sending a PR.
Thanks!

**Comment by santosh0705** [comment]
Sure will do it :)

**Comment by jmaas** [comment]
Any news on this PR ?

**Comment by jmaas** [comment]
Any news on this PR ?

**Comment by santosh0705** [comment]
@jmaas apologise for the late response.
code quality maintained in new pull request in #1517

**Pull request closed without merging**
