### PR TITLE
API: Expose input_converters to the outside

### LINKED ISSUE #3162: Expose input converters to the API
### Is your feature request related to a problem?

It seems that languages like Java cannot reimplement our `input_string_or_dict` functions. Theses functions are important so that users may enter their kernel options in a way they would enter it in a real command line.

### Provide a detailed description of the proposed feature

The functionality of all `input_string_or*` functions should be available via both XML-RPC or HTTP API.

### Alternatives you've considered

None

### Additional information

Found during an L3 at SUSE Manager.

### PR DESCRIPTION
**Pull request by SchoolGuy**
Fixes #3162 

This PR adds the `input_*` functionality to the XML-RPC and Python API.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
Uhhh docs are broken. I need to regenerate the API documentation...

**Comment by SchoolGuy** [comment]
Okay docs are fixed now. There are two open questions:

- Do we want to put this behind authentication?
- Do we want to log the usage of this method if called externally via the XML-RPC API?

@cobbler/suse-reviewers

**Review by vzhestkov — APPROVED** [review]
Looks good :+1: no any questions

**Comment by ycedres** [comment]
@SchoolGuy Would it be a good idea to write a test to cover the not empty list case?

**Comment by SchoolGuy** [comment]
@ycedres Could you please be a bit more specific. We have multiple functions that are being added and tested thus.

**Comment by ycedres** [comment]
> @ycedres Could you please be a bit more specific? We have multiple functions that are being added and tested thus.

Of course. For example, the parameters in the tests for `cobbler_api.input_string_or_list_no_inherit` are `[], "<<inherit>>" and "delete"` but not a non-empty list or string. For `cobbler_api.input_string_or_dict` some non-empty dictionaries are tested.

**Comment by SchoolGuy** [comment]
@ycedres Here you go. Latest commit has these examples.

**Comment by ycedres** [comment]
> @ycedres Here you go. Latest commit has these examples.

@SchoolGuy Thanks!

**Review by ycedres — APPROVED** [review]
LGTM!

**Pull request merged**
