### PR TITLE
Fix string replacements for @@xyz@@

### PR DESCRIPTION
**Pull request by tpw56j**
`regex = r"@@[\S]*@@"` for `"tree=http://@@http_server@@/cblr/links/@@distro_name@@"` returns:
`['@@http_server@@/cblr/links/@@distro_name@@']`

`regex = r"@@[\S]*?@@"`:
`['@@http_server@@', '@@distro_name@@']`

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@tpw56j Could you please write a testcase for that and rebase onto master. We just now replaced the CI to be sure Cobbler is stable. Thus I would very much adore if you could make these changes!

**Comment by tpw56j** [comment]
@SchoolGuy I added a testcase.

**Review by SchoolGuy — APPROVED** [review]
LGTM in my eyes. That the tests are in general not perfect is no reason to not merge this. Thanks for the contribution!

**Review by brejoc — APPROVED** [review]
Looks good to me! Thx for fixing that!

**Pull request merged**
