### PR TITLE
feat: Added signature for Ubuntu 22.04 LTS

### LINKED ISSUE #3251: Can we support ubuntu 22.04 in future?
### Discussed in https://github.com/cobbler/cobbler/discussions/3217

<div type='discussions-op-text'>

<sup>Originally posted by **mytxyang-arm** July 29, 2022</sup>
Ubuntu 22.04 was released already, do we have a plan to support it on cobbler?</div>

### PR DESCRIPTION
**Pull request by btravouillon**
## Linked Items

Fixes #3251

## Description

Add support for Ubuntu 22.04 LTS.

This is mainly a copy + update of `impish`. I don't really understand the purpose of each variable and did not find the developer documentation for this file.

## Behaviour changes

Old: Cannot define `os_version`.

```
cobbler:~$ sudo cobbler distro report --name ubuntu-22.04
Name                           : ubuntu-22.04
Architecture                   : x86_64
Automatic Installation Template Metadata : {'install_source_hostname': 'mirror.example.tld', 'install_source_directory': '/ubuntu/'}
TFTP Boot Files                : {}
Boot loaders                   : <<inherit>>
Breed                          : ubuntu
Comment                        : 
Fetchable Files                : {}
Initrd                         : /var/lib/tftpboot/ubuntu/22.04/ubuntu-installer/amd64/initrd
Kernel                         : /var/lib/tftpboot/ubuntu/22.04/ubuntu-installer/amd64/vmlinuz
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Management Classes             : []
OS Version                     : 
Owners                         : ['admin']
Redhat Management Key          : 
Remote Boot Initrd             : 
Remote Boot Kernel             : 
Template Files                 : {}

cobbler:~$ sudo cobbler distro edit --name ubuntu-22.04 --os-version "jammy"
exception on server: os_version for breed "ubuntu" must be one of artful, lucid, oneiric, precise, quantal, raring, saucy, trusty, utopic, vivid, wily, xenial, yakkety, zesty, bionic, cosmic, disco, eoan, focal, impish, given was "jammy"
```

New:  Can define `os_version`.

```
cobbler:~$ sudo cobbler distro edit --name ubuntu-22.04 --os-version "jammy"
cobbler:~$ sudo cobbler distro report --name ubuntu-22.04
Name                           : ubuntu-22.04
Architecture                   : x86_64
Automatic Installation Template Metadata : {'install_source_hostname': 'mirror.example.tld', 'install_source_directory': '/ubuntu/'}
TFTP Boot Files                : {}
Boot loaders                   : <<inherit>>
Breed                          : ubuntu
Comment                        : 
Fetchable Files                : {}
Initrd                         : /var/lib/tftpboot/ubuntu/22.04/ubuntu-installer/amd64/initrd
Kernel                         : /var/lib/tftpboot/ubuntu/22.04/ubuntu-installer/amd64/vmlinuz
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Management Classes             : []
OS Version                     : jammy
Owners                         : ['admin']
Redhat Management Key          : 
Remote Boot Initrd             : 
Remote Boot Kernel             : 
Template Files                 : {}

```

## Category

This is related to a:

- [ ] Bugfix
- [x] Feature
- [ ] Packaging
- [ ] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [ ] No tests required

### CODE REVIEW

**Review by SchoolGuy — APPROVED** [review]
@btravouillon Could you open a PR to https://github.com/cobbler/cobbler.github.io as well please? This PR is looking good to me.

**Comment by SchoolGuy** [comment]
@btravouillon If it is not too much trouble it would be nice if we could add a system-test that tests the import.

**Comment by btravouillon** [comment]
> @btravouillon Could you open a PR to https://github.com/cobbler/cobbler.github.io as well please? This PR is looking good to me.

Looks like https://github.com/cobbler/cobbler.github.io/pull/175/ will do the job.

**Comment by SchoolGuy** [comment]
Rebased and system tests added. Can now be merged.

**Pull request merged**
