### PR TITLE
Remove child reference on parent on collection.remove()

### LINKED ISSUE #2680: Sync fails during writing PXE file
### Describe the bug

`cobbler sync` fails with the following error if some of my systems have
bootloaders set to "pxe":

```
$ cobbler sync
...
Exception occurred: <class 'AttributeError'>
Exception value: 'NoneType' object has no attribute 'to_dict'
Exception Info:
!!! TASK FAILED !!!
```

### Steps to reproduce

1. Create a x86\_64 distro with bootloader "pxe"
2. Create a profile with bootloader "pxe"
3. Create an OS with bootloader "pxe"
4. Run cobbler sync

### Expected behavior

The command should not fail.

### Cobbler version

````paste below
Cobbler 3.2.1
  source: ?, ?
  build time: Tue Jun 22 15:41:34 2021
````

### Operating system

CentOS 8.

### Cobbler log

````paste below
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['distro']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['profile']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['system']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['repo']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['image']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['mgmtclass']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['package']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['file']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['menu']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | Exception occurred: <class 'AttributeError'>
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | Exception value: 'NoneType' object has no attribute 'to_dict'
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 96, in run
    rc = self._run(self)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 212, in runner
    self.remote.api.sync(self.options.get("verbose", False), what=what)

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1379, in sync
    sync_obj.run()

  File "/usr/lib/python3.6/site-packages/cobbler/actions/sync.py", line 144, in run
    self.tftpd.sync(self.verbose)

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/in_tftpd.py", line 177, in sync
    menu_items = self.tftpgen.get_menu_items()

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 367, in get_menu_items
    return self.get_menu_level(None, arch)

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 549, in get_menu_level
    self.get_profiles_menu(menu, metadata, arch)

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 449, in get_profiles_menu
    image=None, format=boot_loader)

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 673, in write_pxe_file
    self.build_kernel(metadata, system, profile, distro, image, format)

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 755, in build_kernel
    blended = utils.blender(self.api, True, profile)

  File "/usr/lib/python3.6/site-packages/cobbler/utils.py", line 612, in blender
    results["children"][key] = api_handle.find_items("", name=key, return_list=False).to_dict()

[2021-06-22_212727_sync] 2021-06-22T21:27:28 - ERROR | ### TASK FAILED ###
````

### PR DESCRIPTION
**Pull request by SchoolGuy**
This PR tries to improve the stacktrace in case we have orphaned children, as well as trying to prevent it in more cases.

~~Fixes #2680~~

Edit: The fixed issue is unrelated to this PR now because it can't be reproduced anymore...

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@heroin-moose Could you check with the current changes from this PR if you can make more sense of your situation?

**Comment by heroin-moose** [comment]
I kinda have the same workaround, except there is no printing :D
I'll apply your patch and report back with the logs.

**Comment by heroin-moose** [comment]
During `cobbler system add`:

```
exception on server: Child with the name "test" of parent object "packer-ppc64le" did not exist!
```

test is a system, packer-ppc64le is a profile.

**Comment by SchoolGuy** [comment]
Okay that gives me a vague feeling where to look. I will debug tomorrow.

**Comment by SchoolGuy** [comment]
@heroin-moose Rebased onto `master´ (so all past fixes included) and my first approach of fixing it. Please test for yourself, I will try to reproduce and test myself now.

**Comment by SchoolGuy** [comment]
While working on #2693 I found out that we actually have an empty str and duplicate entries in the children. Thus I will dive deeper into this, sadly this also means that both bugs have become more complicated.

**Comment by SchoolGuy** [comment]
I rebased to include the lastest Commits

**Comment by heroin-moose** [comment]
Still cannot `systemctl restart cobblerd` if a system has any bootloaders.

**Comment by SchoolGuy** [comment]
@heroin-moose also showed my that this can be reproduced with `cobbler system get-autoinstall --name test` a few days ago. Leaving this just here as a reminder for myself, so I can reproduce that this is really fixed.

**Comment by SchoolGuy** [comment]
Okay this is getting out of hand. I found the following issues which I also need to solve:

- [ ] Cheetah Snippets are not working (again; their death is imminent but well now they need to work)
- [ ] The value for the servername is not filled in, not even localhost (which wouldn't make sense at all)

P.S.: I will update this comment with more TODOs if required.

**Comment by heroin-moose** [comment]
Please check the `servern` of your profile, it's probably empty instead of '<<inherited>>'. I was bitten by that.

**Comment by heroin-moose** [comment]
As for Cheetah -- I fixed them in the latest master.

**Comment by SchoolGuy** [comment]
@heroin-moose Could you submit the patch with the hacks please? I now at least for my case that I have the corresponding erros in my log (in this case the snippets can't call `lower` on their values).

**Comment by heroin-moose** [comment]
There is no patch, must make sure `server` is inherited.

**Comment by SchoolGuy** [comment]
@heroin-moose Ah okay that is the case...

**Comment by heroin-moose** [comment]
Huh, lower is something new.

**Comment by heroin-moose** [comment]
Or maybe not...

**Comment by SchoolGuy** [comment]
I think it is related to `blender` and the enum values...

**Comment by SchoolGuy** [comment]
@heroin-moose The `lower()` thing should be fixed afaik with my last commit...

**Comment by SchoolGuy** [comment]
Okay so locally I have made good progress but this is a lot of small changes which need to be well tested, so this will take a few days to fully work.

**Comment by SchoolGuy** [comment]
@heroin-moose Could you please thoroughly test my changes, I wasn't able to reproduce the behavior anymore but I havn't found it before so, well better you test it again plase. :)

If you confirm I will fix the remaining `virt_*` properties. Making the code nice is something I will do in a followup PR, I am aware that this is a lot of copy & paste.

**Comment by SchoolGuy** [comment]
The regression I am fixing was introduced with my refactoring in PR https://github.com/cobbler/cobbler/pull/2433

**Comment by heroin-moose** [comment]
I'll do that today!

**Comment by SchoolGuy** [comment]
Even though this is working now, you can't restart Cobbler due to the importance of order from the keys. I will fix that tomorrow. The `factory_produce` method needs to prioritize the keys `name`, `parent`, `distro`, `profile` and `image` in case they are present. I do need to fix that for all collections so that the rest of the keys can be validated on loading time. This will in the end boil down I guess to adjusting the `from_dict` method of the individual items.

**Comment by nodeg** [comment]
@heroin-moose Could you please do a test again with the most recent changes. It works for @SchoolGuy and me. Thanks!

**Comment by SchoolGuy** [comment]
I have decided to not blow up this PR any more that I will create an issue for the inheritance of the `virt_*` properties which will be done by any contributor before the next release.

**Comment by heroin-moose** [comment]
Yes, it works for me if there are no menus. If there a menu, I cannot restart cobblerd:

```
[root@pxe cobbler]# cobblerd
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/manager.py", line 189, in deserialize
    serializer.deserialize(collection)
  File "/usr/lib/python3.6/site-packages/cobbler/serializer.py", line 128, in deserialize
    storage_module.deserialize(collection, topological)
  File "/usr/lib/python3.6/site-packages/cobbler/modules/serializers/file.py", line 160, in deserialize
    collection.from_list(datastruct)
  File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/collection.py", line 201, in from_list
    item = self.factory_produce(self.api, item_dict)
  File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/profiles.py", line 45, in factory_produce
    new_profile.from_dict(item_dict)
  File "/usr/lib/python3.6/site-packages/cobbler/items/profile.py", line 132, in from_dict
    super().from_dict(dictionary)
  File "/usr/lib/python3.6/site-packages/cobbler/items/item.py", line 780, in from_dict
    setattr(self, lowered_key, dictionary[key])
  File "/usr/lib/python3.6/site-packages/cobbler/items/profile.py", line 783, in menu
    raise CX("menu %s not found" % menu)
cobbler.cexceptions.CX: 'menu packer not found'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/cobblerd", line 79, in main
    api = cobbler_api.CobblerAPI(is_cobblerd=True)
  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 107, in __init__
    self.deserialize()
  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1616, in deserialize
    return self._collection_mgr.deserialize()
  File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/manager.py", line 192, in deserialize
    % (collection.collection_type(), e)) from e
cobbler.cexceptions.CX: "serializer: error loading collection profile: 'menu packer not found'. Check /etc/cobbler/modules.conf"
[root@pxe cobbler]# find /var/lib/cobbler/collections/
/var/lib/cobbler/collections/
/var/lib/cobbler/collections/distros
/var/lib/cobbler/collections/distros/packer-x86_64.json
/var/lib/cobbler/collections/files
/var/lib/cobbler/collections/images
/var/lib/cobbler/collections/menus
/var/lib/cobbler/collections/menus/packer.json
/var/lib/cobbler/collections/mgmtclasses
/var/lib/cobbler/collections/packages
/var/lib/cobbler/collections/profiles
/var/lib/cobbler/collections/profiles/packer-x86_64.json
/var/lib/cobbler/collections/repos
/var/lib/cobbler/collections/systems
/var/lib/cobbler/collections/systems/test.json
```

**Comment by heroin-moose** [comment]
However, I still get the error in the following scenario:

- Create a distro with two bootloaders (grub, ipxe)
- Create a profile with two bootloaders (grub, ipxe)
- Create a system with two bootloaders (grub, ipxe)

Bam! You won't be able to complete step #3:

```
exception on server: 'Error with system "" - not all boot_loaders are supported (given: "[\'grub\', \'ipxe\']"; supported:"[]")'
```

**Comment by nodeg** [comment]
@heroin-moose the problem with the bootloaders should be hopefully fixed now. Would you mind doing a test again, please and confirm if so?

Create distro, profile and system:
```bash
  #!/bin/bash    
               
  # create fake kernel and initrd    
  sudo touch /root/vmlinuz    
  sudo touch /root/initrd    
               
  #cobbler menu add \    
  #        --name test \    
  #        --display-name "Test menu"    
               
  cobbler distro add \    
          --name test-x86_64 \    
          --arch x86_64 \    
          --kernel /root/vmlinuz \    
          --initrd /root/initrd \    
          --boot-loaders 'grub ipxe' \    
               
  cobbler profile add \    
          --name test-x86_64 \    
          --distro test-x86_64 \    
          --boot-loaders 'grub ipxe' \    
               
  cobbler system add \    
          --name test \    
          --profile test-x86_64 \    
          --boot-loaders 'grub ipxe' \   
```

```bash
$ cobbler version
Cobbler 3.2.1
  source: a13c9704, Mon Jul 12 10:45:49 2021 +0200
  build time: Mon Jul 12 08:54:53 2021
```

```bash
$ cobbler report            
distros:
==========
Name                           : test-x86_64
Architecture                   : x86_64
Automatic Installation Template Metadata : {}
TFTP Boot Files                : {}
Boot loaders                   : ['grub', 'ipxe']
Breed                          : 
Comment                        : 
Fetchable Files                : {}
Initrd                         : /root/initrd
Kernel                         : /root/vmlinuz
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Management Classes             : []
OS Version                     : 
Owners                         : ['admin']
Redhat Management Key          : 
Remote Boot Initrd             : 
Remote Boot Kernel             : 
Template Files                 : {}


profiles:
==========
Name                           : test-x86_64
Automatic Installation Template : default.ks
Automatic Installation Metadata : <<inherit>>
TFTP Boot Files                : <<inherit>>
Boot loaders                   : ['grub', 'ipxe']
Comment                        : 
DHCP Tag                       : 
Distribution                   : test-x86_64
Enable iPXE?                   : False
Enable PXE Menu?               : True
Fetchable Files                : <<inherit>>
DHCP Filename Override         : <<inherit>>
Kernel Options                 : <<inherit>>
Kernel Options (Post Install)  : <<inherit>>
Parent boot menu               : 
Management Classes             : <<inherit>>
Management Parameters          : <<inherit>>
Name Servers                   : []
Name Servers Search Path       : []
Next Server (IPv4) Override    : 127.0.0.1
Next Server (IPv6) Override    : ::1
Owners                         : ['admin']
Parent Profile                 : 
Proxy                          : 
Red Hat Management Key         : <<inherit>>
Repos                          : []
Server Override                : 
Template Files                 : {}
Virt Auto Boot                 : True
Virt Bridge                    : xenbr0
Virt CPUs                      : 1
Virt Disk Driver Type          : raw
Virt File Size(GB)             : 0
Virt Path                      : 
Virt RAM (MB)                  : 512
Virt Type                      : xenpv


systems:
==========
Name                           : test
Automatic Installation Template : <<inherit>>
Automatic Installation Template Metadata : <<inherit>>
TFTP Boot Files                : <<inherit>>
Boot loaders                   : ['grub', 'ipxe']
Comment                        : 
Enable iPXE?                   : <<inherit>>
Fetchable Files                : <<inherit>>
DHCP Filename Override         : <<inherit>>
Gateway                        : 
Hostname                       : 
Image                          : 
IPv6 Autoconfiguration         : False
IPv6 Default Device            : 
Kernel Options                 : <<inherit>>
Kernel Options (Post Install)  : <<inherit>>
Management Classes             : <<inherit>>
Management Parameters          : <<inherit>>
Name Servers                   : []
Name Servers Search Path       : []
Netboot Enabled                : False
Next Server (IPv4) Override    : <<inherit>>
Next Server (IPv6) Override    : <<inherit>>
Owners                         : <<inherit>>
Power Management Address       : 
Power Management ID            : 
Power Identity File            : 
Power Management Options       : 
Power Management Password      : 
Power Management Type          : 
Power Management Username      : 
Profile                        : test-x86_64
Internal Proxy                 : <<inherit>>
Redhat Management Key          : <<inherit>>
Repos Enabled                  : False
Serial Baud Rate               : 0
Serial Device #                : 0
Server Override                : 
Status                         : 
Template Files                 : {}
Virt Auto Boot                 : <<inherit>>
Virt CPUs                      : <<inherit>>
Virt Disk Driver Type          : <<inherit>>
Virt File Size(GB)             : <<inherit>>
Virt Path                      : <<inherit>>
Virt PXE Boot                  : False
Virt RAM (MB)                  : <<inherit>>
Virt Type                      : <<inherit>>
Interface =====                : default
Bonding Opts                   : 
Bridge Opts                    : 
CNAMES                         : []
InfiniBand Connected Mode      : False
DHCP Tag                       : 
DNS Name                       : 
Per-Interface Gateway          : 
Master Interface               : 
Interface Type                 : NA
IP Address                     : 
IPv6 Address                   : 
IPv6 Default Gateway           : 
IPv6 MTU                       : 
IPv6 Prefix                    : 
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    : 
Management Interface           : False
MTU                            : 
Subnet Mask                    : 
Static                         : False
Static Routes                  : []
Virt Bridge                    : 


repos:
==========

images:
==========

mgmtclasses:
==========

packages:
==========

files:
==========

menus:
==========
```


Create distro, profiles and system with test menu:
```bash
#!/bin/bash

# create fake kernel and initrd
sudo touch /root/vmlinuz
sudo touch /root/initrd


cobbler menu add \
        --name test_menu \
        --display-name "test_menu"

cobbler distro add \
        --name test-x86_64 \
        --arch x86_64 \
        --kernel /root/vmlinuz \
        --kernel-options 'debug pxe_shell=yes' \
        --initrd /root/initrd \
        --boot-loaders 'grub ipxe' \

cobbler profile add \
        --name test-x86_64 \
        --distro test-x86_64 \
        --server '<<inherit>>' \
        --boot-loaders 'grub ipxe' \
        --enable-menu 1 \
        --menu test_menu

cobbler profile add \
        --name test-centos-8.4-x86_64 \
        --parent test-x86_64 \
        --server '<<inherit>>' \
        --boot-loaders 'grub ipxe' \
        --enable-menu 1 \
        --menu test_menu

cobbler system add \
        --name test \
        --profile test-centos-8.4-x86_64 \
        --server '<<inherit>>' \
        --boot-loaders 'grub ipxe' \
        --enable-ipxe 0 \
        --netboot 1
```

```bash
$ cobbler report
distros:
==========
Name                           : test-x86_64
Architecture                   : x86_64
Automatic Installation Template Metadata : {}
TFTP Boot Files                : {}
Boot loaders                   : ['grub', 'ipxe']
Breed                          : 
Comment                        : 
Fetchable Files                : {}
Initrd                         : /root/initrd
Kernel                         : /root/vmlinuz
Kernel Options                 : {'debug': '~', 'pxe_shell': 'yes'}
Kernel Options (Post Install)  : {}
Management Classes             : []
OS Version                     : 
Owners                         : ['admin']
Redhat Management Key          : 
Remote Boot Initrd             : 
Remote Boot Kernel             : 
Template Files                 : {}


profiles:
==========
Name                           : test-x86_64
Automatic Installation Template : default.ks
Automatic Installation Metadata : <<inherit>>
TFTP Boot Files                : <<inherit>>
Boot loaders                   : ['grub', 'ipxe']
Comment                        : 
DHCP Tag                       : 
Distribution                   : test-x86_64
Enable iPXE?                   : False
Enable PXE Menu?               : True
Fetchable Files                : <<inherit>>
DHCP Filename Override         : <<inherit>>
Kernel Options                 : <<inherit>>
Kernel Options (Post Install)  : <<inherit>>
Parent boot menu               : test_menu
Management Classes             : <<inherit>>
Management Parameters          : <<inherit>>
Name Servers                   : []
Name Servers Search Path       : []
Next Server (IPv4) Override    : 127.0.0.1
Next Server (IPv6) Override    : ::1
Owners                         : ['admin']
Parent Profile                 : 
Proxy                          : 
Red Hat Management Key         : <<inherit>>
Repos                          : []
Server Override                : <<inherit>>
Template Files                 : {}
Virt Auto Boot                 : True
Virt Bridge                    : xenbr0
Virt CPUs                      : 1
Virt Disk Driver Type          : raw
Virt File Size(GB)             : 0
Virt Path                      : 
Virt RAM (MB)                  : 512
Virt Type                      : xenpv

Name                           : test-centos-8.4-x86_64
Automatic Installation Template : default.ks
Automatic Installation Metadata : <<inherit>>
TFTP Boot Files                : <<inherit>>
Boot loaders                   : ['grub', 'ipxe']
Comment                        : 
DHCP Tag                       : 
Distribution                   : 
Enable iPXE?                   : False
Enable PXE Menu?               : True
Fetchable Files                : <<inherit>>
DHCP Filename Override         : <<inherit>>
Kernel Options                 : <<inherit>>
Kernel Options (Post Install)  : <<inherit>>
Parent boot menu               : test_menu
Management Classes             : <<inherit>>
Management Parameters          : <<inherit>>
Name Servers                   : []
Name Servers Search Path       : []
Next Server (IPv4) Override    : 127.0.0.1
Next Server (IPv6) Override    : ::1
Owners                         : ['admin']
Parent Profile                 : test-x86_64
Proxy                          : 
Red Hat Management Key         : <<inherit>>
Repos                          : []
Server Override                : <<inherit>>
Template Files                 : {}
Virt Auto Boot                 : True
Virt Bridge                    : xenbr0
Virt CPUs                      : 1
Virt Disk Driver Type          : raw
Virt File Size(GB)             : 0
Virt Path                      : 
Virt RAM (MB)                  : 512
Virt Type                      : xenpv


systems:
==========
Name                           : test
Automatic Installation Template : <<inherit>>
Automatic Installation Template Metadata : <<inherit>>
TFTP Boot Files                : <<inherit>>
Boot loaders                   : ['grub', 'ipxe']
Comment                        : 
Enable iPXE?                   : False
Fetchable Files                : <<inherit>>
DHCP Filename Override         : <<inherit>>
Gateway                        : 
Hostname                       : 
Image                          : 
IPv6 Autoconfiguration         : False
IPv6 Default Device            : 
Kernel Options                 : <<inherit>>
Kernel Options (Post Install)  : <<inherit>>
Management Classes             : <<inherit>>
Management Parameters          : <<inherit>>
Name Servers                   : []
Name Servers Search Path       : []
Netboot Enabled                : True
Next Server (IPv4) Override    : <<inherit>>
Next Server (IPv6) Override    : <<inherit>>
Owners                         : <<inherit>>
Power Management Address       : 
Power Management ID            : 
Power Identity File            : 
Power Management Options       : 
Power Management Password      : 
Power Management Type          : 
Power Management Username      : 
Profile                        : test-centos-8.4-x86_64
Internal Proxy                 : <<inherit>>
Redhat Management Key          : <<inherit>>
Repos Enabled                  : False
Serial Baud Rate               : 0
Serial Device #                : 0
Server Override                : <<inherit>>
Status                         : 
Template Files                 : {}
Virt Auto Boot                 : <<inherit>>
Virt CPUs                      : <<inherit>>
Virt Disk Driver Type          : <<inherit>>
Virt File Size(GB)             : <<inherit>>
Virt Path                      : <<inherit>>
Virt PXE Boot                  : False
Virt RAM (MB)                  : <<inherit>>
Virt Type                      : <<inherit>>
Interface =====                : default
Bonding Opts                   : 
Bridge Opts                    : 
CNAMES                         : []
InfiniBand Connected Mode      : False
DHCP Tag                       : 
DNS Name                       : 
Per-Interface Gateway          : 
Master Interface               : 
Interface Type                 : NA
IP Address                     : 
IPv6 Address                   : 
IPv6 Default Gateway           : 
IPv6 MTU                       : 
IPv6 Prefix                    : 
IPv6 Secondaries               : []
IPv6 Static Routes             : []
MAC Address                    : 
Management Interface           : False
MTU                            : 
Subnet Mask                    : 
Static                         : False
Static Routes                  : []
Virt Bridge                    : 


repos:
==========

images:
==========

mgmtclasses:
==========

packages:
==========

files:
==========

menus:
==========
Name                           : test_menu
Comment                        : 
Display Name                   : test_menu
Parent Menu                    : 
```

**Comment by heroin-moose** [comment]
@nodeg, will do today.

**Comment by heroin-moose** [comment]
Bootloaders are now indeed work!

**Comment by heroin-moose** [comment]
Guys, there is a thing...

With the following patch:

```
diff --git a/cobbler/utils.py b/cobbler/utils.py
index ba7a4391..033b8453 100644
--- a/cobbler/utils.py
+++ b/cobbler/utils.py
@@ -735,9 +735,6 @@ def __consolidate(node) -> dict:
                 node_data_copy[key] = getattr(type(node), "autoinstall").fget(node)
             elif key == "ks_meta":
                 node_data_copy[key] = getattr(type(node), "autoinstall_meta").fget(node)
-            else:
-                # Normal handling
-                node_data_copy[key] = getattr(type(node), key).fget(node)

     for field in node_data_copy:
         data_item = node_data_copy[field]
```

Any attribute that simply returns `self._attribute_name` (without the manual inheritance logic) seems to be working fine. If I am not missing anything, `__check_parent_none()` may not be needed at all.

**Comment by heroin-moose** [comment]
However, if you want to eventually drop `blender()` then `_check_parent_none()` should do the very same thing the blender currently does: merging dicts and checking the top-level Settings for the defaults, instead of bailing early with a default value.

**Comment by SchoolGuy** [comment]
This is currently awaiting the merge of #2711

**Comment by nodeg** [comment]
Tests are fixed. I will do a review tomorrow.

**Comment by SchoolGuy** [comment]
I refactored the commit history to make it better.

**Comment by SchoolGuy** [comment]
Okay I once again looked over the code and personally I don't find any things I would like to change.

However I had a discussion with @heroin-moose whether we should remove some safeguards in regard to stability or not. We came in the Gitter Chat to the conclusion that we will remove them once the integration testsuite prepared by him will be in place, until then the safeguards will stay.

**Comment by SchoolGuy** [comment]
So @watologo1 found the first thing while testing this PR in

https://github.com/cobbler/cobbler/blob/ded3e6e5453ad88607de1a0df18731f9df79aaff/cobbler/items/item.py#L727

we need to adjust the line to `result.keys()`. Otherwise just all keys are shown and not those who are failing.

**Comment by SchoolGuy** [comment]
So @watologo1 found out that we should not serialize and deserialize the `remote_grub_*` fields.

**Review by watologo1 — APPROVED** [review]
Beside mixing up one variable/dict in error case, I could not find anything.

I also did some tests like adding/removing a system, generating grub network configs and all went well.

We might want to go back with variable re-naming before the next release still.
I realized that next-server now has to be next-server-v4.
This could lead to quite some grief and extra work for backward compatibility. I guess for this one we should stills stay with the old variable name.

Well done, the stuff works.

**Review by nodeg — APPROVED** [review]
LGTM.
@watologo1 The renaming was necessary due to the introduction of IPv6/DHCPv6 and to be consistend with the naming style.

**Pull request merged**
