### PR TITLE
Replaces Grub Legacy bootloader by Grub2

### LINKED ISSUE #1904: issues with EL7 + UEFI + Cobbler
Greetings,

I'm having a heck of a time with UEFI and would appreciate some help. I reached out on the [mailing list](https://groups.google.com/forum/#!forum/cobbler-users), but it is just crickets over there and there is no history to sort through.

I finally discovered the problem that I mentioned on the mailing list, I just don't know how to fix it. All my hosts are Scientific Linux 7.5.

Here's the short of it. If I use the cobbler loaders (even a forced upgrade), everything goes horribly wrong.

From the SL7.5 disk I copied BOOTX64.EFI -> /var/lib/cobbler/loaders/grub-el7-bootx64.efi and grubx64.efi -> /var/lib/cobbler/loaders/grubx64.efi (my hacky way to have cobbler sync those files too). I updated my dhcpd.template file to load grub-el7-bootx64.efi.

Now suddenly, I no longer have weird TFTP issues! Hooray!! But I can't get it to load the kickstart to provision! Ugh.

Well lets look. For some reason some of my hosts have files that look like this:
```
$ cat /var/lib/tftpboot/grub/01-3C-FD-FE-B2-5A-A3 
default=0
timeout=0
splashimage=(nd)/splash.xpm.gz
title local
	quit
```

Well, that is EFI...but nothing tells it to kickstart anything at all.

Other files look like this:
```$ cat /var/lib/tftpboot/grub/01-3C-FD-FE-B2-5C-A7 
default=0
timeout=0

title testhost02
    root (nd)
    kernel /images/SL-7.5-x86_64/vmlinuz  ksdevice=link lang=en_US kssendmac text  ks=http://192.168.1.3/cblr/svc/op/ks/system/testhost02
    initrd /images/SL-7.5-x86_64/initrd.img
```
Better. At least that is a grub menu...too bad that it is the WRONG one. 

So I wrote a nastly little script that basically figured out which host each of the Mac address are in cobbler and dumps out a GRUB2 file instead. Also, notice the new name AND LOWERCASE (ugh, that bit me hard...).
```
$ cat /var/lib/tftpboot/grub/grub.cfg-01-3c-fd-fe-b5-9a-a4
set default="1"

function load_video {
  insmod efi_gop
  insmod efi_uga
  insmod video_bochs
  insmod video_cirrus
  insmod all_video
}

load_video
set gfxpayload=keep
insmod gzio
insmod part_gpt
insmod ext2

set timeout=3
### END /etc/grub.d/00_header ###

search --no-floppy --set=root -l 'Scientific-7.5-x86_64'

### BEGIN /etc/grub.d/10_linux ###
menuentry 'Install Scientific 7.5' --class fedora --class gnu-linux --class gnu --class os {
	linuxefi /images/SL-7.5-x86_64/vmlinuz ksdevice=link lang=en_US kssendmac text  ks=http://192.168.1.3/cblr/svc/op/ks/system/testhost01
	initrdefi /images/SL-7.5-x86_64/initrd.img
}
```
HOORAY! <Insert heavenly rejoicing music here!>

My nodes now boot UEFI with cobbler!! After much dancing and rejoicing, I would really like to figure out how I can get cobbler to write out a correct GRUB2 menu instead of whatever it is  that it's doing now (since it isn't doing any one thing consistently with the nodes I have right now).

Can someone please help? Have I hit a bug with cobbler or am I just doing something wrong? I can't find anything in the docs that relates to EUFI or configuring GRUB2.

Thanks!

### PR DESCRIPTION
**Pull request by MRinalducci**
This PR replaces Grub Legacy bootloader by Grub2 as requested in #1904.

There is a makefile in the loaders folder to build and copy the Grub2 loaders to Cobbler loaders folder.
This have to be implement in the future to the `get-loaders` function.
By the way, the bootloader binaries are also provided for easier testing. I build them on a fresh Centos 7 machine.  

This PR closes #1904.

### CODE REVIEW

**Comment by watologo1** [comment]
I generally agree with replacing grub with grub2.

I also did parts of this yesterday. It would be great to know more about the background of the work and how we can get together to integrate this nice and distro independent.

Some comments:
- You should use grub2-mkimage instead of grub2-mkstandalone
The fingerprint of created binary files is much bigger with mkstandalone and you should not need it.
Here I created grub2 binaries for 4 different archs with mkimage and mkstandalone and I have:
4.8M    grub2
22M     grub2_standalone

- Next point is already mentioned: Different architectures. I have a tiny, distro independent script which creates grub2 executables for 4 different archs. It would be nice if the whole:
grub2-mkstandalone call could get replace with my script:
https://hastebin.com/zovifazeho.bash
The lower part with the coping of the signed grub is distro specific, I would cut that out.

- I also first started with a cobbler create_loaders command (instead of get-loaders which is fully download oriented and after looking at it, I guess it should be kept like this).

My idea also was to create:
/var/lib/cobbler/loaders/grub2/${arch}
subdirectories and sync those to /srv/tftpboot/grub2
This would implement different arch support more cleanly from the beginnning.

But this patch is definitely some steps in the right direction. And it's not wrong. I guess we can discuss further steps and how to implement other grub2 features (especially multi arch support, also possible shim and signed grub2 binaries for secure boot) on top of it.

PS: It would be great to get in touch. trenn@suse.de. Feel free to drop me a mail so that we can fiddle out the one or other implementation detail.

**Comment by jmaas** [comment]
Great contribution, this provides a base to work from. Replacing grub1 is indeed the way forward.
I'd like to get this in the tree and then apply the suggestions from Thomas, starting with grub-mkimage.

Thomas's script provides a great reference to get this implemented within Cobbler. But i think i like the idea of an action_buildloaders.py (cli: cobbler build-loaders) approach. Where configuration of this is using the settings.d/ framework (e.g. for listing grub2 modules, mapping architectures to filenames, etc). Moving this from code to configuration helps future contributors.

It also makes Cobbler better work in air-gapped networks (not having to rely on get-loaders to work), cobbler get-loaders can stay as a convenience feature.

So how to proceed? If we merge this as-is, are you Thomas willing to work on adding your suggestions? Any other views/opinions are ofcourse much appreciated! :)

**Comment by MRinalducci** [comment]
Thanks for your inputs 👍 

As you say @jmaas it is a first step for Grub2 integration.
I think we can add some nice enhancements as suggested by @watologo1 or @JohanElmis.
It will be a great feature to have Cobbler better work in air-gapped networks as a lot of user are certainly concerned by this.

My opinion is to merge this PR as-is to help enhancements from other contributors on this base.
I can also find some time (few hours per week) for helping. :)

**Comment by jmaas** [comment]
@watologo1 Any comments from your side?

If not i'll merge this and lets work from there....

**Comment by watologo1** [comment]
On Friday, January 18, 2019 11:45:02 AM CET Jörgen wrote:
> @watologo1 Any comments from your side?
> 
> If not i'll merge this and lets work from there....

Yes, please.
I already wanted to start on top of it and asked whether Jochen could even
push it (not sure he has rights to do so). A quick merge helps.

Thanks,

    Thomas

**Pull request merged**
