### PR TITLE
The "cobbler reposync" command does not work in Fedora 32

### PR DESCRIPTION
**Pull request by tpw56j**
This PR solves problems 1-4 described in the #2378.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
What do we need the yum code for? librepo and dnf are available on all supported hosts for Cobbler.

**Comment by SchoolGuy** [comment]
@Conan-Kudo In theory you are right. I would suggest leaving it in there for the next release and then throwing it out. Even if you are for removing it now, I would say that I do that in a seperate PR and not complicate things for @tpw56j anymore. Since this is his first PR ever as far as I understand, I don't want to have meta discussions over it and just appreciate that a newcomer is taking all this effort for Cobbler.

**Comment by Conan-Kudo** [comment]
@SchoolGuy I'm not saying that @tpw56j should take that effort, but we should probably purge it in a followup PR. The yum code can't even be used with cobbler being Python 3 only anyway.

**Comment by SchoolGuy** [comment]
CI passes, Docs are passing and we have two approvals. Thus I will merge this now. Big thanks to @tpw56j !

**Pull request merged**
