### PR TITLE
Prevent some race conditions when writting tftpboot files

### PR DESCRIPTION
**Pull request by meaksh**
Fixes: https://github.com/cobbler/cobbler/issues/2635

### CODE REVIEW

**Comment by nodeg** [comment]
I removed the unused time import for making the builds work again.

**Comment by meaksh** [comment]
Thanks @nodeg !

**Review by nodeg — APPROVED** [review]
LGTM.

**Review by SchoolGuy — APPROVED** [review]
LGTM but since I want to check if this can happen to other directories and code parts, I will reopen the issue.

**Pull request merged**
