### PR TITLE
docker: add build of debs for Debian 12 Bookworm

### PR DESCRIPTION
**Pull request by btravouillon**
## Description

This commit adds a Dockerfile to build the debs for Debian 12.

Update the installation guide to provide the build and install command for Debian 12. Also add Debian 12 to the Makefile and GH Action jobs.

## Behaviour changes

Old: There were no DEB files to install Cobbler on Debian 12 servers.

New: There are DEB files to install Cobbler on Debian 12 servers.

## Category

This is related to a:

- [ ] Bugfix
- [ ] Feature
- [x] Packaging
- [x] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [x] Code is already covered by System-Tests
- [ ] No tests required

### CODE REVIEW

**Comment by btravouillon** [comment]
With [Debian 11 end of life in 6 months](https://wiki.debian.org/DebianReleases#Production_Releases), that would be great to provide DEBS to run Cobbler server on the current stable Debian 12 Bookworm.

I would also open a backport to the latest stable branch `release33` after this PR.

**Review by SchoolGuy — APPROVED** [review]
Thanks for this contribution!

**Comment by SchoolGuy** [comment]
@btravouillon do you have the capability to sign your commits? It would be nice if that could be made possible.

**Comment by btravouillon** [comment]
Sorry, new laptop :smile: . Done.

**Pull request merged**
