### PR TITLE
README: Update Gitter to Matrix link

### PR DESCRIPTION
**Pull request by ByteOtter**
## Description

Replace the link to the cobbler matrix room with a default matrix link instead of the old gitter url

## Behaviour changes

Old: 

New: 

## Category

This is related to a:

- [ ] Bugfix
- [ ] Feature
- [ ] Packaging
- [x] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [x] No tests required

### CODE REVIEW

**Review by SchoolGuy — COMMENTED** [review]
Looking at the redirection of the room is maybe <https://app.gitter.im/#/room/#cobbler_community:gitter.im> more appropriate? Gitter is its own matrix instance and I see no benefit in using the matrix.to link atm.

However, you may of course show me the benefits of using the matrix.to link if you think it is better.

**Comment by ByteOtter** [comment]
> Looking at the redirection of the room is maybe https://app.gitter.im/#/room/#cobbler_community:gitter.im more appropriate? Gitter is its own matrix instance and I see no benefit in using the matrix.to link atm.
> 
> However, you may of course show me the benefits of using the matrix.to link if you think it is better.

for getting a room preview you are right. What I am trying to achieve is being able to directly login with an existing Matrix account aswell, as gitter seems to only support github/gitlab or twitter login.
Still working on it though.

**Comment by SchoolGuy** [comment]
@ByteOtter I would love if you could please finish this PR once you are back in the office. :)

**Review by SchoolGuy — APPROVED** [review]
LGTM

**Pull request merged**
