### PR TITLE
CI: Add PR template

### LINKED ISSUE #3206: PR templates
### Is your feature request related to a problem?

At the moment when seeing a PR it is hard to grasp what it is about.

### Provide a detailed description of the proposed feature

I would like to have a form that enables a reviewer to have a uniform view of each PR.

### Alternatives you've considered

None

### Additional information

This idea was raised by @meaksh in an internal retrospective of the team we both are working on at SUSE.

### PR DESCRIPTION
**Pull request by SchoolGuy**
## Linked Items

Fixes #3206

## Description

Adds Pull Request templates to the repository.

## Behaviour changes

Old: PRs were opened and people had all kind of different formatting

New: PRs now have a unified UI for all contributors

## Category

This is related to a:

- [ ] Bugfix
- [x] Feature
- [ ] Packaging
- [ ] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [x] No tests required

### CODE REVIEW

**Review by tiltingpenguin — COMMENTED** [review]
Maybe add sections for UI and behavior changes?

**Comment by SchoolGuy** [comment]
@tiltingpenguin

- We don't have a UI per-se. Thus that doesn't make sense.
- In regard to behaviour: That is an interesting idea. Do you have an idea how to make a bit more concrete? In theory every bugfix is removing incorrect previous behaviour in my eyes.

**Comment by tiltingpenguin** [comment]
I just saw it on other PRs before. What I mean is that we add a section for previous behavior and new behavior to highlight the differences that each PR introduces. This might be somewhat covered by the description, but I think a PR template exists to make sure that all aspects are explained properly and this could help people to be more concrete about the changes they make.

**Comment by SchoolGuy** [comment]
@tiltingpenguin Okay so would that be additionally to the "Description" section or instead of the section?

**Comment by tiltingpenguin** [comment]
I think we should do it additionally to the "Description"

**Review by tiltingpenguin — APPROVED** [review]
Sorry for the late answer, LGTM!

**Pull request merged**
