### PR TITLE
Fixed supervisord service restarts 

### LINKED ISSUE #2925: cobbler sync error - supervisord
### Describe the bug

Using Cobbler on a distro with supervisord and with `manage_dhcp` enabled, `cobbler sync` errors:

```
Exception occurred: <class 'cobbler.cexceptions.CX'>
Exception value: 'Cobbler trigger failed: cobbler.modules.sync_post_restart_services'
Exception Info:
!!! TASK FAILED !!!
```
and log shows stack trace:
```
[2022-02-01_153306_sync] 2022-02-01T15:33:08 - INFO | Exception occurred: <class 'cobbler.cexceptions.CX'>
[2022-02-01_153306_sync] 2022-02-01T15:33:08 - INFO | Exception value: 'Cobbler trigger failed: cobbler.modules.sync_post_restart_services'
[2022-02-01_153306_sync] 2022-02-01T15:33:08 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 99, in run
    rc = self._run(self)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 218, in runner
    self.remote.api.sync(self.options.get("verbose", False), what=what)

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1406, in sync
    sync_obj.run()

  File "/usr/lib/python3.6/site-packages/cobbler/actions/sync.py", line 179, in run
    utils.run_triggers(self.api, None, "/var/lib/cobbler/triggers/sync/post/*")

  File "/usr/lib/python3.6/site-packages/cobbler/utils.py", line 983, in run_triggers
    raise CX("Cobbler trigger failed: %s" % m.__name__)

[2022-02-01_153306_sync] 2022-02-01T15:33:08 - ERROR | ### TASK FAILED ###
```

This is because in #2841 @th-2021 set [no return code](https://github.com/cobbler/cobbler/blob/a783fd652254ff8613ec347759bb738c35d51127/cobbler/utils.py#L258) for the supervisord case.  [ret](https://github.com/cobbler/cobbler/blob/a783fd652254ff8613ec347759bb738c35d51127/cobbler/utils.py#L270) is `None`

### Cobbler version

v3.3.1 (latest master)

### PR DESCRIPTION
**Pull request by holmesb**
... which were causing a cobbler sync exception. 

Fixes #2925

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@holmesb Would it be asked too much if you add a test that this works as expected?

**Comment by SchoolGuy** [comment]
I took the liberty of rebasing onto `master` because this fixes two testsuite errors we still had in.

**Comment by SchoolGuy** [comment]
@holmesb I will write some tests for you and make some suggestions. Before I merge I would love to get your opinion on my proposed changes once they are pushed..

**Comment by holmesb** [comment]
Cool, yes sorry I'm tied up until tomorrow, otherwise would have written tests myself

**Comment by SchoolGuy** [comment]
@holmesb For details have a look at [d583625](https://github.com/cobbler/cobbler/pull/2926/commits/d583625e8772eb7cc894819ea338a857a894bfb1). But I believe it should be good now.

**Comment by holmesb** [comment]
Yes about as much as we can do until we mock supervisord.  Good that we've got decent coverage of service restarts now.  LGTM

**Review by SchoolGuy — APPROVED** [review]
@holmesb and me agree that this is legitimate.

**Pull request merged**
