### PR TITLE
Rewrite Cobbler packaging

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This pull request rewrites the Cobbler packaging into something that supports the full range of distributions that Cobbler is intended to support.

As part of this, the old Debian packaging that has been unmaintained for ~2 years has been dropped and the Debian support has been merged into the cobbler spec file.

Some other fixes have been made as separate commits to fix support for building and running Cobbler everywhere, too.

You can see a build of the spec on OBS here: https://build.opensuse.org/package/show/home:Pharaoh_Atem:cobbler-dev/cobbler

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@brejoc @watologo1 If you are fine with it I would like one of you two to hit the merge button. Of some else has concerns please speak up!

**Comment by SchoolGuy** [comment]
P.S.: Gitter seems to be down atm...

**Comment by SchoolGuy** [comment]
@Conan-Kudo This is your PR so your choice. Either we let the default as it was before or we manipulate the config for the Tests so it is as it was the default before.

**Comment by Conan-Kudo** [comment]
@SchoolGuy I'm manipulating the config in the tests.

**Comment by SchoolGuy** [comment]
@Conan-Kudo I will have a look tomorrow. Now it's bedtime for me... Christmas with the parents is exhausting... (Probably the food but anyway...)

**Comment by Conan-Kudo** [comment]
@SchoolGuy The tests pass, so you can merge now.

**Comment by hbokh** [comment]
@Conan-Kudo The Debian_10 packages v3.0.1 (cobbler and cobbler-web) won’t install on Debian Buster. Has multiple errors, for example in the systems service script (path to `cobblerd`), sed on the secret key, etc.
Do you want me to file a bug report? Or are they it still NSFW? 😁

**Comment by SchoolGuy** [comment]
@hbokh Please file a bug. Then I can fix it. I am just preparing a PR for fixing the linter...

**Comment by Conan-Kudo** [comment]
@hbokh bug reports welcome. I only made sure it built and the files looked sane.

**Comment by hbokh** [comment]
Done! See #2238

**Pull request merged**
