### PR TITLE
WIP: Initial start on migration script

### PR DESCRIPTION
**Pull request by opoplawski**
Here is an initial start on an in-place migration script from v2 to v3.  It's pretty fast-and-loose.  Suggestions welcome.

### CODE REVIEW

**Comment by hbokh** [comment]
Take care with this script!
I tested it on CentOS7. Upgraded Cobbler 2.8.5 to 3.1.2 (had to fix the config first) and ran the migration script:

```
# ./migrate-data-v2-to-v3.py
Processing distros.d:
    Processing Debian_Stretch
    Processing CentOS7
    Processing Debian_Buster
    Processing Ubuntu16.04-hwe-x86_64
    Processing Ubuntu18.04-hwe-x86_64
Processing files.d:
Processing images.d:
Processing mgmtclasses.d:
Processing packages.d:
Processing profiles.d:
    Processing debian9-x86_64
    Processing debian10-x86_64
    Processing Ubuntu16.04-hwe-x86_64
    Processing Ubuntu18.04-hwe-x86_64
Processing repos.d:
    Processing Debian_Stretch
    Processing Debian_Buster
    Processing Ubuntu16.04-x86_64
    Processing Ubuntu18.04-x86_64
Processing systems.d:
    Processing linux004
cp: missing file operand
Try 'cp --help' for more information.
cp: missing file operand
Try 'cp --help' for more information.

```

Now Cobbler is eh... broken. 😋 Nothing serious, since it's a lab machine.

Anyway, `/var/www/cobbler/distro_mirror -> ks_mirror` but `ks_mirror` is gone.

I decided to test it on CentOS7, after all went OK yesterday on a Debian host where I **copied** the configuration of a production server onto.

**Comment by watologo1** [comment]
@opoplawski : I did not review all, just realized by trying to understand the concept..., you have  a typo in line 76:
  "systemd": {
must be:
  "systems": {

**Comment by opoplawski** [comment]
@watologo1 ouch, good catch

**Comment by SchoolGuy** [comment]
@opoplawski This script is used in uyuni/SUMA: https://github.com/uyuni-project/uyuni/blob/aa01598f082c7bd74c4895ad6c027e2a7aabbedd/susemanager/bin/migrate-cobbler.sh

**Comment by hbokh** [comment]
LGTM. I used the latest fix of this script successfully on the migration of v2.6.11 to v3.1.2 yesterday.
In short: I copied a tarball of the old config-directory to the new Cobbler host, extracted it in `/var/lib/cobbler/` and ran this script.

**Comment by hbokh** [comment]
@SchoolGuy See my comment from over 2 months ago.
I think it is safe to merge single script this into master. It is not touching the core actively.

**Comment by SchoolGuy** [comment]
Although Codacy is not happy let's merge this. We are satisfied and this maybe very useful in the future.

**Pull request merged**
