### PR TITLE
Remove esxi70u1 bootcfg template and signature

### LINKED ISSUE #2525: ESXi 7.0U1 bootfcg template is incorrect
### Describe the bug

Hello,

looks to me that ESXI 7.0U1 support introduced on #2442 is wrong.
- on bootcfg_esxi70u1.template, prefix and modules are hardcoded and should be a variable:
```
prefix=/images/esxi7-x86_64
modules=jumpstrt.gz --- useropts.gz --- features.gz ...
```
- on distro_signatures.json,  version_file_regex for esxi70 catches any esxi70u1 regex string
`"version_file_regex": "^(VMware )?ESXi( )?(v)?7(\\.)?0(\\.)?.*$"`
`"version_file_regex": "^(VMware )?ESXi( )?(v)?7(\\.)?0(\\.)?1.*$"`

IMHO esxi70u1 signature is not needed (as it has not been for any other minor esxi versions).

### To Reproduce

If you import any ESXi 7.0U1 distro and give it a name different to "esxi7" , hardcoded prefix would lead to erroneous cobbler-boot.cfg file.
TBH I have not been able to test with ESXi 7.0U1 (only version I have is 7.0b).

### Expected behavior

esxi70u1 signature/template is not needed. ESXi 7.0U1 distro covered by esxi70 signature.

### Version

````# cobbler version
Cobbler 3.2.0
  source: b'77ccee3c', b'Mon Jan 18 11:50:40 2021 +0100'
  build time: Thu Jan 21 21:19:37 2021

````

### PR DESCRIPTION
**Pull request by javier-angulo**
Fixes #2525

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@javier-angulo So do I understand correctly that no additions are needed for supporting the servicepack?

**Comment by SchoolGuy** [comment]
@shparker1977 Could you please confirm that this is working and if not reason with @javier-angulo to why your template is needed?

**Review by hbokh — APPROVED** [review]
LGTM

**Comment by SchoolGuy** [comment]
Ping @shparker1977

**Comment by shparker1977** [comment]
@SchoolGuy @javier-angulo - Sorry for the late response.  I've been on short-term disability, so I don't currently have access to a testing environment.  Here's what I can say:

- ESXi 7u1 did not work without the changes I made
- The original changes I made did work for ESXi 7u1
- It's possible I made some extra/unnecessary changes :)

I should be able to test in about 2 weeks.  Thanks to all for looking into this.

**Comment by SchoolGuy** [comment]
@javier-angulo I hope it is okay that your PR stays open until @shparker1977 was able to tests this.

@shparker1977 Take your time. I won't be ready to ship a new release anyway, thus as long as we merge this before the release or discard it, I am good with it.

**Comment by javier-angulo** [comment]
No problem on my side @SchoolGuy . Thanks for having a look at it @shparker1977

**Comment by javier-angulo** [comment]
Just for the record, I was able to get a copy today of ESXi 7.0U1c (last version available from VMware as ISO).
Tested import **without** esxi70u1 template & signature, signature of esxi70 marches, distro imported, no issues:
```  
# cobbler import --arch=x86_64 --path=/mnt --name=esxi7.0U1c
task started: 2021-02-10_144201_import
task started (id=Media import, time=Wed Feb 10 14:42:01 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Found a candidate signature: breed=suse, version=opensuse15generic
Found a candidate signature: breed=suse, version=sles15generic
Found a candidate signature: breed=vmware, version=esxi67
Found a candidate signature: breed=vmware, version=esxi70
Found a matching signature: breed=vmware, version=esxi70
Adding distros from path /var/www/cobbler/distro_mirror/esxi7.0U1c-x86_64:
Could not detect the filetype and read the content of file "/var/www/cobbler/distro_mirror/esxi7.0U1c-x86_64/tools.t00". Returning nothing.
creating new distro: esxi7.0U1c-x86_64
trying symlink: /var/www/cobbler/distro_mirror/esxi7.0U1c-x86_64 -> /var/www/cobbler/links/esxi7.0U1c-x86_64
creating new profile: esxi7.0U1c-x86_64
associating repos
*** TASK COMPLETE ***

# cobbler distro report --name esxi7.0U1c-x86_64
Name                           : esxi7.0U1c-x86_64
Architecture                   : x86_64
Automatic Installation Template Metadata : {'tree': 'http://@@http_server@@/cblr/links/esxi7.0U1c-x86_64'}
TFTP Boot Files                : {'$local_img_path/*.*': '/var/www/cobbler/distro_mirror/esxi7.0U1c-x86_64/*.*'}
Boot loader                    : grub
Breed                          : vmware
Comment                        : 
Fetchable Files                : {}
Initrd                         : /var/www/cobbler/distro_mirror/esxi7.0U1c-x86_64/imgpayld.tgz
Kernel                         : /var/www/cobbler/distro_mirror/esxi7.0U1c-x86_64/mboot.c32
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Management Classes             : []
OS Version                     : esxi70
Owners                         : ['admin']
Redhat Management Key          : 
Remote Boot Initrd             : ~
Remote Boot Kernel             : ~
Template Files                 : {'/etc/cobbler/boot_loader_conf/bootcfg_esxi70.template': '$local_img_path/cobbler-boot.cfg'}
```

**Comment by SchoolGuy** [comment]
@shparker1977 I would plan to do a release either end of next week or the week after it. Does that give you enough time or do you need more?

**Comment by shparker1977** [comment]
@SchoolGuy - I think I should be good for testing tomorrow or Tuesday.  Apologies for the lag on this again.  On top of the disability, I'm in Texas.  Lost power all last week.  All good now.  :)

**Review by shparker1977 — APPROVED** [review]
I didn't have a chance to test, but if it's been successfully tested, I'm ok with it.  The only complication I would have experienced is with using HP branded ISOs.  I may have made these specific adjustments for that reason, but if the base code for the VMware ISOs is good, I say ship it.  I won't be able to get my hands on the HP ISO for another 2 weeks.  Thanks for the patience.

**Comment by SchoolGuy** [comment]
@shparker1977 If you have access to such HP ISOs, would you be able to share them? Or are they not Open Source? If you share what exactly they are I can get my hands on them via work. Thanks for contributing!

**Review by SchoolGuy — APPROVED** [review]
LGTM

**Pull request merged**
