### PR TITLE
[replicate] Add setter for `distro.remote_grub_kernel/remote_grub_initrd`

### LINKED ISSUE #3030: [replicate] Attribute "remote_grub_kernel" could not be set!
### Describe the bug

`cobbler replicate` got error `Attribute "remote_grub_kernel" could not be set!`.

### Steps to reproduce

1. run `cobbler replicate --master=cobbler.xsky.com --prune --distros=* --profiles=*` on standby cobber node

### Expected behavior

`replicate` command execute successfully without error.

### Cobbler version

````
Cobbler 3.3.2
  source: ?, ?
  build time: Wed Mar 16 02:41:51 2022
````

### Operating system

```
Rocky Linux release 8.4 (Green Obsidian)
```

### Cobbler log

````
[2022-04-15_025652_replicate] 2022-04-15T03:33:30 - INFO | Adding Objects Not Stored On Local
[2022-04-15_025652_replicate] 2022-04-15T03:33:30 - INFO | new_distro; [False]
[2022-04-15_025652_replicate] 2022-04-15T03:33:30 - INFO | Exception occurred: <class 'AttributeError'>
[2022-04-15_025652_replicate] 2022-04-15T03:33:30 - INFO | Exception value: Attribute "remote_grub_kernel" could not be set!
[2022-04-15_025652_replicate] 2022-04-15T03:33:30 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 99, in run
    rc = self._run(self)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 290, in runner
    self.options.get("use_ssl", False),

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1810, in replicate
    file_patterns=file_patterns, prune=prune, omit_data=omit_data, sync_all=sync_all, use_ssl=use_ssl

  File "/usr/lib/python3.6/site-packages/cobbler/actions/replicate.py", line 399, in run
    self.replicate_data()

  File "/usr/lib/python3.6/site-packages/cobbler/actions/replicate.py", line 220, in replicate_data
    self.add_objects_not_on_local(what)

  File "/usr/lib/python3.6/site-packages/cobbler/actions/replicate.py", line 109, in add_objects_not_on_local
    newobj.from_dict(utils.revert_strip_none(rdata))

  File "/usr/lib/python3.6/site-packages/cobbler/items/distro.py", line 110, in from_dict
    super().from_dict(dictionary)

  File "/usr/lib/python3.6/site-packages/cobbler/items/item.py", line 795, in from_dict
    raise AttributeError("Attribute \"%s\" could not be set!" % lowered_key) from error

[2022-04-15_025652_replicate] 2022-04-15T03:33:30 - ERROR | ### TASK FAILED ###
````

### Screenshots

image
### Additional information

https://github.com/cobbler/cobbler/blob/7324b1918848d2bcc6c126a40defa7e3a56c75ce/cobbler/items/distro.py#L307
`remote_grub_kernel` and `remote_grub_initrd` need to implement `setter`.

### PR DESCRIPTION
**Pull request by wy-z**
Signed-off-by: weiyang <weiyang.ones@gmail.com>

Fix #3030.

### CODE REVIEW

**Comment by wy-z** [comment]
Hi, @SchoolGuy
This PR tries to fix #3030, hope it helps.

**Comment by SchoolGuy** [comment]
Sadly this will break the mechanism as intended. Sadly I am not able to find the commit at the moment with the removal of the setter but the reason is that this property was wrongfully introduced in the first place. These properties just handle special properties of the `kernel` and `initrd` at the moment. They also contain specially rendered formats of the locations for GRUB. Sadly there is also a [long outstanding PR](https://github.com/cobbler/cobbler/pull/2884) to fix this which is not being progressed at the moment due to a lack of downstream resources.

**Comment by wy-z** [comment]
> Sadly this will break the mechanism as intended. Sadly I am not able to find the commit at the moment with the removal of the setter but the reason is that this property was wrongfully introduced in the first place. These properties just handle special properties of the `kernel` and `initrd` at the moment. They also contain specially rendered formats of the locations for GRUB. Sadly there is also a [long outstanding PR](https://github.com/cobbler/cobbler/pull/2884) to fix this which is not being progressed at the moment due to a lack of downstream resources.

Glad to see your reply~
Never mind, I will just use it as a temporary circumvention solution for myself, you can turn off this PR if needed.

**Comment by wy-z** [comment]
Hi @SchoolGuy 
The setters were removed by https://github.com/cobbler/cobbler/commit/05ad7c65eeed0abbfeb1ed8c23cdc86275325b28.
Indeed, as you said, this PR is not accurate enough and I will close it.

**Pull request closed without merging**
