### PR TITLE
Fix issue #2381 - Cobbler <--> Terraform compatibility #1

### PR DESCRIPTION
**Pull request by holmesb**

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@holmesb Would you please fix the linter for this one so the tests can run?

**Comment by hbokh** [comment]
> Side note: I have to test this some time later with the Terraform provider we made

I adapted `items/item.py` (added the comment) and applied the code change @holmesb provided here to `utils.py`.
The test from the CLI with our provider looks good!

Apply / add a new Terraform configured host named `prov-test3`:
```
$ terraform apply -auto-approve
cobbler_system.prov-test3[0]: Refreshing state... [id=prov-test3]
cobbler_system.prov-test3[0]: Creating...
cobbler_system.prov-test3[0]: Creation complete after 4s [id=prov-test3]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

And once more:
```
$ terraform apply -auto-approve
cobbler_system.prov-test3[0]: Refreshing state... [id=prov-test3]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
✅

**Comment by hbokh** [comment]
*Don't merge yet* @SchoolGuy 

We are seeing these errors (again) in `/var/log/cobbler/cobbler.log` while provisioning:


```
2020-07-20T17:08:45 - INFO | REMOTE generate_autoinstall; user(?)
2020-07-20T17:08:45 - INFO | Exception occured: <class 'AttributeError'>
2020-07-20T17:08:45 - INFO | Exception value: 'str' object has no attribute 'copy'
2020-07-20T17:08:45 - INFO | Exception Info:
  File "/usr/lib/python3/dist-packages/cobbler/remote.py", line 1115, in generate_autoinstall
    return self.autoinstall_mgr.generate_autoinstall(profile, system)

  File "/usr/lib/python3/dist-packages/cobbler/autoinstall_manager.py", line 230, in generate_autoinstall
    return self.autoinstallgen.generate_autoinstall_for_system(system)

  File "/usr/lib/python3/dist-packages/cobbler/autoinstallgen.py", line 246, in generate_autoinstall_for_system
    return self.generate_autoinstall(profile=p, system=s)

  File "/usr/lib/python3/dist-packages/cobbler/autoinstallgen.py", line 256, in generate_autoinstall
    meta = utils.blender(self.api, False, obj)

  File "/usr/lib/python3/dist-packages/cobbler/utils.py", line 550, in blender
    __consolidate(node, results)

  File "/usr/lib/python3/dist-packages/cobbler/utils.py", line 690, in __consolidate
    results[field].update(data_item.copy())

2020-07-20T17:10:05 - DEBUG | get_items; ['system']
```

**Comment by holmesb** [comment]
Yes thx for testing @hbokh  I'm happy to help troubleshoot if you can send a slim example resource that causes.

**Comment by holmesb** [comment]
I had only tested the fix by creating Cobbler templates.  I was able to reproduce this error when attempting to create a system.  New commit addresses.  Please post any more occurrences you find @hbokh, be great if you could include the resource type too thx.

**Comment by hbokh** [comment]
Great @holmesb! Will check tomorrow at work. For resource you mean a `main.tf` file I guess, right?

**Comment by holmesb** [comment]
Just whether it's a cobbler_system, cobbler_template, cobbler_distro, etc should do.  I'll assume you'll have tried a mimimal example with few attributes.

**Comment by hbokh** [comment]
Also issues with the latest commit.

Here is a somewhat obfuscated resource for a test-system:

```hcl
resource "cobbler_system" "prov-test3" {
  count       = "1"
  name        = "prov-test3"
  profile     = "debian10-x86_64"
  hostname    = "prov-test3.example.lan"
  autoinstall = "debian10_PROXMOX.seed"
  # NOTE: Extra space at the end is there for a reason!
  # When reading the resource state, the terraform-provider-cobbler
  # parses these fields with an extra space. Adding an extra space
  # here prevents Terraform from constantly changing the resource.
  kernel_options      = "netcfg/choose_interface=ens18 noquiet "
  autoinstall_meta    = "fs=ext4 swap=2048 "
  status              = "testing"
  netboot_enabled     = "1"
  comment             = "Test system - contact: Henk"
  ipv6_default_device = "ens19"

  # Spindle-Backend vlan ###########################
  interface {
    name        = "ens18"
    mac_address = "76:55:17:40:41:41"
    ip_address  = "10.85.114.239"
    netmask     = "255.255.255.0"
    dhcp_tag      = "amstst"
    dns_name      = "prov-test3.example.lan"
    static_routes = ["10.85.115.0/24:10.85.114.1"]
    static        = true
    management    = true
  }
  # Bogus IP address since out of range; NIC disabled in Proxmox
  interface {
    name                 = "ens19"
    mac_address          = "9E:AA:37:7A:2A:CA"
    ip_address           = "145.85.114.239"
    netmask              = "255.255.255.128"
    gateway              = "145.85.114.1"
    dns_name             = "prov-test3.example.nl"
    ipv6_address         = "2a09:2a80:0:114::239"
    ipv6_default_gateway = "2a09:2a80:0:114::1"
    ipv6_static_routes   = ["::/0,2a09:2a80:0:114::1"]
    static               = true
  }
}
```


terraform apply -auto-approve                                      (☸ |voipgrid-k8s1:default) 11:02 
cobbler_system.prov-test3[0]: Refreshing state... [id=prov-test3]
cobbler_system.prov-test3[0]: Creating...
cobbler_system.prov-test3[0]: Creation complete after 2s [id=prov-test3]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
$ vi main.tf                                                         (☸ |voipgrid-k8s1:default) 11:04 
   ~/P…/V…/t…/t…/prov-test3     develop ±  terraform apply -auto-approve                                      (☸ |voipgrid-k8s1:default) 11:05 
cobbler_system.prov-test3[0]: Refreshing state... [id=prov-test3]
cobbler_system.prov-test3[0]: Modifying... [id=prov-test3]

Error: Cobbler System: Error syncing system: Fault(1): <class 'AttributeError'>:'str' object has no attribute 'copy'

  on main.tf line 1, in resource "cobbler_system" "prov-test3":
   1: resource "cobbler_system" "prov-test3" {

**Comment by hbokh** [comment]
Also issues with the latest commit.

Here is a somewhat obfuscated resource for a test-system:

```hcl
resource "cobbler_system" "prov-test3" {
  count       = "1"
  name        = "prov-test3"
  profile     = "debian10-x86_64"
  hostname    = "prov-test3.example.lan"
  autoinstall = "debian10_PROXMOX.seed"
  # NOTE: Extra space at the end is there for a reason!
  # When reading the resource state, the terraform-provider-cobbler
  # parses these fields with an extra space. Adding an extra space
  # here prevents Terraform from constantly changing the resource.
  kernel_options      = "netcfg/choose_interface=ens18 noquiet "
  autoinstall_meta    = "fs=ext4 swap=2048 "
  status              = "testing"
  netboot_enabled     = "1"
  comment             = "Test system - contact: Henk"
  ipv6_default_device = "ens19"

  # Spindle-Backend vlan ###########################
  interface {
    name        = "ens18"
    mac_address = "76:55:17:40:41:41"
    ip_address  = "10.85.114.239"
    netmask     = "255.255.255.0"
    dhcp_tag      = "amstst"
    dns_name      = "prov-test3.example.lan"
    static_routes = ["10.85.115.0/24:10.85.114.1"]
    static        = true
    management    = true
  }
  # Bogus IP address since out of range; NIC disabled in Proxmox
  interface {
    name                 = "ens19"
    mac_address          = "9E:AA:37:7A:2A:CA"
    ip_address           = "145.85.114.239"
    netmask              = "255.255.255.128"
    gateway              = "145.85.114.1"
    dns_name             = "prov-test3.example.nl"
    ipv6_address         = "2a09:2a80:0:114::239"
    ipv6_default_gateway = "2a09:2a80:0:114::1"
    ipv6_static_routes   = ["::/0,2a09:2a80:0:114::1"]
    static               = true
  }
}
```

```txt
$ terraform apply -auto-approve
cobbler_system.prov-test3[0]: Refreshing state... [id=prov-test3]
cobbler_system.prov-test3[0]: Creating...
cobbler_system.prov-test3[0]: Creation complete after 2s [id=prov-test3]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

OK that works, just as yesterday, but now I make a change to the existing resource:

```txt
$ vi main.tf <== edit the line with "kernel_options", remove "noquiet"
```

And apply again:
```txt
$ terraform apply -auto-approve
cobbler_system.prov-test3[0]: Refreshing state... [id=prov-test3]
cobbler_system.prov-test3[0]: Modifying... [id=prov-test3]

Error: Cobbler System: Error syncing system: Fault(1): <class 'AttributeError'>:'str' object has no attribute 'copy'

  on main.tf line 1, in resource "cobbler_system" "prov-test3":
   1: resource "cobbler_system" "prov-test3" {
```

Next, I **only uncomment** the line 

```python
#return utils.to_dict_from_fields(self, self.get_fields())
```
in file `cobbler/items/item.py`, restart cobbler (`systemctl restart cobblerd`) and run

```
$ terraform apply -auto-approve
cobbler_system.prov-test3[0]: Refreshing state... [id=prov-test3]
cobbler_system.prov-test3[0]: Modifying... [id=prov-test3]
cobbler_system.prov-test3[0]: Modifications complete after 3s [id=prov-test3]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by holmesb** [comment]
I was able to simulate this problem changing kernel_options in a system.  With the latest commit, I've successfully tested:
1.  Creating a template
2.  Creating a system
3  Changing kernel_options in a system

Please can you do another round of terraform tests @hbokh

**Comment by hbokh** [comment]
> Please can you do another round of terraform tests @hbokh

Sure, will do tomorrow (I'm in TZ Europe/Amsterdam).

**Comment by hbokh** [comment]
Some improvements but still an issue. Here's what I did.
Applied the changes in `utils.py` and (re-)commented the specific line it `item.py` and restarted Cobbler
Now, at least Terraform is not complaining anymore:

```console 
$ terraform apply -auto-approve
cobbler_system.prov-test3[0]: Creating...
cobbler_system.prov-test3[0]: Creation complete after 4s [id=prov-test3]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

$ vi main.tf << Remove "noquiet" from the "kernel_options".

$ terraform apply -auto-approve
cobbler_system.prov-test3[0]: Refreshing state... [id=prov-test3]
cobbler_system.prov-test3[0]: Modifying... [id=prov-test3]
cobbler_system.prov-test3[0]: Modifications complete after 5s [id=prov-test3]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

$ terraform apply -auto-approve
cobbler_system.prov-test3[0]: Refreshing state... [id=prov-test3]
cobbler_system.prov-test3[0]: Modifying... [id=prov-test3]
cobbler_system.prov-test3[0]: Modifications complete after 3s [id=prov-test3]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

It keeps on saying `1 changed` every time it's run, but in Cobbler the `kernel_options` remain showing `netcfg/choose_interface=ens18 noquiet `.

**Comment by SchoolGuy** [comment]
@hbokh What method of changing the attribute is the client using? The xapi method or the old one? Because since we have two ways of doing that it may be that one is broken silently.

**Comment by hbokh** [comment]
> @hbokh What method of changing the attribute is the client using? The xapi method or the old one? Because since we have two ways of doing that it may be that one is broken silently.

Not sure, but I think it must be the "old one" (the one with XMLRPC, right?), since the code (for both `cobblerclient` and `terraform-provider-cobbler`) is not that much different from the code that worked with Cobbler 2.6.11.
Look here for example: https://github.com/wearespindle/cobblerclient

**Comment by SchoolGuy** [comment]
Ah okay I just saw you are using the `modify_*`. So this is normally working since the CI passes.

**Comment by holmesb** [comment]
[The XMLRPC api is broken when cache is enabled](https://github.com/cobbler/cobbler/issues/2386).  This is the root cause of issue #2381 so closing this PR.

**Pull request closed without merging**
