### PR TITLE
Cobbler285

### PR DESCRIPTION
**Pull request by kwizart**
Here are few backports from patches already in master  (or PR pending).

It should be possible to tag cobbler 2.8.5 once:
- IPMI fixes are merged 
- A little bit of testing is done.

This was tested again python sdist on Fedora/EPEL with django 1.11

### CODE REVIEW

**Comment by SchoolGuy** [comment]
Sorry to not respond so long. I find it very reasonable to do a 2.8.5 release. I would take some time and look for stuff we fixed in 3.0 and maybe propose some additional commits to include since we fixed a lot of problems there.

**Comment by kwizart** [comment]
Hello,

I think this PR has nothing newer than anything in master.
It should be good to go and tag 2.8.5

Thx in advances.

(side note, I expect Fedora f31+ will move to cobbler 3.0.0).

**Comment by SchoolGuy** [comment]
Yeah I think also that this one is complete. Since there is no urgency in releasing this I would wait until I backported the readthedocs documentation to this branch.

**Comment by kwizart** [comment]
Can this PR be merged and tagging later then ?
(Or any reviewers are awaited ?)

Thx for the answer.

**Comment by SchoolGuy** [comment]
Okay this seems reasonable. Then I will merge my docs stuff with a seperate PR

**Pull request merged**
