### PR TITLE
Latest master fixes

### PR DESCRIPTION
**Pull request by watologo1**

### CODE REVIEW

**Review by SchoolGuy — APPROVED** [review]
LGTM in my eyes...

**Review by SchoolGuy — CHANGES_REQUESTED** [review]
Pls adjust the failing tests if you remove that wrapper.

**Comment by watologo1** [comment]
> Pls adjust the failing tests if you remove that wrapper.

Outch... Looks like I have to set the default fence agent to ipmilan until ipmilanplus is wider spread.

**Review by SchoolGuy — APPROVED** [review]
Everything is green. Now again LGTM.

**Review by brejoc — APPROVED** [review]
lgtm!

**Pull request merged**
