### PR TITLE
Adjust DNS settings

### LINKED ISSUE #2710: Cobbler sync: DNS does not work
### Steps to reproduce

1. Set `manage_dns` to true in `/etc/cobbler/settings.yaml`
2. Restart cobblerd
3. Add distro, profile, system
4. Do a `cobbler sync` (must be done at least once before using `cobbler sync --dns`)

### Expected behavior

`cobbler sync` and `cobbler sync --dns` should work.

### Cobbler version

#2684

### Operating system

openSUSE Tumbleweed

### Cobbler log

````bash
(...)
[2021-07-15_094204_sync] 2021-07-15T09:42:05 - DEBUG | done with get_items; ['distro']
[2021-07-15_094204_sync] 2021-07-15T09:42:05 - INFO | rendering DNS files
[2021-07-15_094204_sync] 2021-07-15T09:42:05 - INFO | Exception occurred: <class 'TypeError'>
[2021-07-15_094204_sync] 2021-07-15T09:42:05 - INFO | Exception value: 'NetworkInterface' object is not subscriptable
[2021-07-15_094204_sync] 2021-07-15T09:42:05 - INFO | Exception Info:
  File "/usr/local/lib/python3.8/site-packages/cobbler/remote.py", line 96, in run
    rc = self._run(self)

  File "/usr/local/lib/python3.8/site-packages/cobbler/remote.py", line 212, in runner
    self.remote.api.sync(self.options.get("verbose", False), what=what)

  File "/usr/local/lib/python3.8/site-packages/cobbler/api.py", line 1379, in sync
    sync_obj.run()

  File "/usr/local/lib/python3.8/site-packages/cobbler/actions/sync.py", line 164, in run
    self.dns.write_configs()

  File "/usr/local/lib/python3.8/site-packages/cobbler/modules/managers/bind.py", line 604, in write_configs
    self.__write_named_conf()

  File "/usr/local/lib/python3.8/site-packages/cobbler/modules/managers/bind.py", line 270, in __write_named_conf
    metadata = {'forward_zones': list(self.__forward_zones().keys()),

  File "/usr/local/lib/python3.8/site-packages/cobbler/modules/managers/bind.py", line 119, in __forward_zones
    host = interface["dns_name"]

[2021-07-15_094204_sync] 2021-07-15T09:42:05 - ERROR | ### TASK FAILED ###
````

### Additional information

```bash
$ cobbler sync      
task started: 2021-07-15_094204_sync
task started (id=Sync, time=Thu Jul 15 09:42:04 2021)
running python triggers from /var/lib/cobbler/triggers/task/sync/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/sync/pre/*
shell triggers finished successfully
syncing all
running pre-sync triggers
running python triggers from /var/lib/cobbler/triggers/sync/pre/*
running shell triggers from /var/lib/cobbler/triggers/sync/pre/*
shell triggers finished successfully
cleaning trees
removing: /srv/www/cobbler/images/dtest
removing: /srv/tftpboot/pxelinux.cfg/stest
removing: /srv/tftpboot/pxelinux.cfg/default
removing: /srv/tftpboot/grub/images
removing: /srv/tftpboot/grub/system
removing: /srv/tftpboot/grub/system_link
removing: /srv/tftpboot/grub/grub.cfg
removing: /srv/tftpboot/grub/local_efi.cfg
removing: /srv/tftpboot/grub/local_legacy.cfg
removing: /srv/tftpboot/grub/local_powerpc-ieee1275.cfg
removing: /srv/tftpboot/images/dtest
removing: /srv/tftpboot/ipxe/default.ipxe
copying bootloaders
running: ['rsync', '-rpt', '--copy-links', '--exclude=.cobbler_postun_cleanup', '/var/lib/cobbler/loaders/', '/srv/tftpboot']
received on stdout: 
received on stderr: 
running: ['rsync', '-rpt', '--copy-links', '--exclude=README.grubconfig', '/var/lib/cobbler/grub_config/', '/srv/tftpboot']
received on stdout: 
received on stderr: 
copying distros to tftpboot
copying files for distro: dtest
mkdir: /srv/tftpboot/images/dtest
trying hardlink /root/vmlinuz -> /srv/tftpboot/images/dtest/vmlinuz
trying cachelink /root/vmlinuz -> /srv/tftpboot/images/.link_cache/da39a3ee5e6b4b0d3255bfef95601890afd80709 -> /srv/tftpboot/images/dtest/vmlinuz
trying hardlink /root/initrd -> /srv/tftpboot/images/dtest/initrd
trying cachelink /root/initrd -> /srv/tftpboot/images/.link_cache/da39a3ee5e6b4b0d3255bfef95601890afd80709 -> /srv/tftpboot/images/dtest/initrd
copying images
generating PXE configuration files
(...)
generating: /srv/tftpboot/pxelinux.cfg/stest
(...)
generating: /srv/tftpboot/grub/system/stest
removing: /srv/tftpboot/grub/system_link/stest
mkdir: /srv/tftpboot/grub/system_link
generating PXE menu structure
(...)
mkdir: /srv/tftpboot/pxelinux.cfg
mkdir: /srv/tftpboot/ipxe
(...)
mkdir: /srv/www/cobbler/images/dtest
trying hardlink /root/vmlinuz -> /srv/www/cobbler/images/dtest/vmlinuz
trying symlink /root/vmlinuz -> /srv/www/cobbler/images/dtest/vmlinuz
trying hardlink /root/initrd -> /srv/www/cobbler/images/dtest/initrd
trying symlink /root/initrd -> /srv/www/cobbler/images/dtest/initrd
Writing template files for dtest
(...)
rendering DNS files
Exception occurred: <class 'TypeError'>
Exception value: 'NetworkInterface' object is not subscriptable
Exception Info:
!!! TASK FAILED !!!
```

### PR DESCRIPTION
**Pull request by nodeg**
This PR fixes some issues regarding DNS:

- Fixes #2710.
- `@@bind_zoneinfo@@` got not replaced during build time
- Some links in the comments in `settings.yaml`
- I left some comments in the named templates regarding the PATH
Furthermore I rearranged some key/values in `settings.yaml` to have those belonging to each other closer together.

For now I leave this as a WIP since I am not completely finished testing DNS.

### CODE REVIEW

**Comment by nodeg** [comment]
Syncing DNS works but we could still improve the `named.template` in Cobbler.

The hardcoded path bothers me. Maybe we can make this adjustable in our settings.
https://github.com/cobbler/cobbler/blob/ded3e6e5453ad88607de1a0df18731f9df79aaff/templates/etc/named.template#L1-L9

Furthermore the logging as implemented in the config does not work under openSUSE. In Fedora 34 and Debian 10 this works.
https://github.com/cobbler/cobbler/blob/ded3e6e5453ad88607de1a0df18731f9df79aaff/templates/etc/named.template#L11-L16

```bash
$ journalctl-u named

Jul 15 10:52:36 localhost.localdomain systemd[1]: Starting Berkeley Internet Name Domain (DNS)...    
Jul 15 10:52:36 localhost.localdomain named[31986]: starting BIND 9.16.18 (Stable Release) <id:1c027c4>                  
Jul 15 10:52:36 localhost.localdomain named[31986]: running on Linux x86_64 5.13.0-1-default #1 SMP Fri Jul 2 05:54:32 UTC 2021 (aa40472)     
(...)
Jul 16 15:18:54 localhost.localdomain named[19937]: command channel listening on ::1#953
Jul 16 15:18:54 localhost.localdomain named[19937]: isc_stdio_open 'data/named.run' failed: file not found
Jul 16 15:18:54 localhost.localdomain named[19937]: configuring logging: file not found
Jul 16 15:18:54 localhost.localdomain named[19937]: loading configuration: file not found
Jul 16 15:18:54 localhost.localdomain named[19937]: exiting (due to fatal error)
Jul 16 15:18:54 localhost.localdomain systemd[1]: named.service: Control process exited, code=exited, status=1/FAILURE
Jul 16 15:18:54 localhost.localdomain systemd[1]: named.service: Failed with result 'exit-code'.
Jul 16 15:18:54 localhost.localdomain systemd[1]: Failed to start Berkeley Internet Name Domain (DNS).
```

What are your thoughts @SchoolGuy, @watologo1?

**Comment by SchoolGuy** [comment]
So my opinion is the following:

1. If we give that template some love, let's convert it to Jinja2. WIth the magic header we can use both Jinja2 for this and Cheetah as the default for all others at the same time.
2. We are requiring the distro module for Cobbler, thus we can use it in this template. This means we can have an include in Jinja2 which depending on the OS then lazy loads the appropriate file for both sections which are different.
3. The approach found in the second point I made will be required for more then only the `named.template`, I would like to formalize that process, so we can repeat it in other templates.
4. I personally don't see this as a blocker for the release. A template can be easily touched by an admin and they should do it, so what we deliver is a best effort not a "works-out-of-the-box". The scenarios in which Cobbler is used are too broad to do that. So once this PR is merged, I would open a second one for fixing up the template.

**Comment by nodeg** [comment]
Rebased onto master.

**Comment by nodeg** [comment]
I was not able to find any other issues besides the things @SchoolGuy mentioned. I think the PR is ready so far and everything template related should be done in a seperate PR.

**Review by SchoolGuy — APPROVED** [review]
LGTM

**Comment by agraul** [comment]
> So my opinion is the following:
> 
>     1. If we give that template some love, let's convert it to Jinja2. WIth the magic header we can use both Jinja2 for this and Cheetah as the default for all others at the same time.
> 

I don't fully understand the second part. Do you want to replace Cheetah with Jinja2 for only some of the templates? Or do you want to use Jinja2 for everything if the system running Cobbler supports it and Cheetah otherwise? Or just move to Jinja2 completely? Personally I think that only one templating system should be used for each Cobbler version and changing it should only be done in a major release (without traces of the old templating system.)

Is this what you have in mind yourself @SchoolGuy ?

**Comment by SchoolGuy** [comment]
@agraul The plan was for 3.4.0 to convert all Cobbler default templates to Jinja2 and let the default at Cheetah, so we don't break templates without a "shebang", the Cobbler version after that would then switch to Jinja2 as a default and with 4.0.0 I would remove the Cheetah Support and only allow Jinja2. I would announce that with the release of Cobbler 3.3.0 to the broader public.

**Review by watologo1 — APPROVED** [review]
Nice cleanup!

**Pull request merged**
