### PR TITLE
Remove field_info.py as it is empty and not used for ages

### PR DESCRIPTION
**Pull request by SchoolGuy**
The mechanism of `field_info.py` was not used in a long while and I believe it is just dead code. This PR is a splitout of #2433

### CODE REVIEW

**Review by nodeg — CHANGES_REQUESTED** [review]
I did not test this, although according to the code this looks indeed like dead and unused code.

You missed some parts in `docs/cobbler.rst` line 85 ff.

**Comment by SchoolGuy** [comment]
Codecov may fail as we only remove code which was untested.

**Review by nodeg — APPROVED** [review]
LGTM.

**Comment by SchoolGuy** [comment]
The openSUSE Leap Package error is due to an unsigned `repomod.xml` file. Thus we ignore it because it bails out before actually building the package. Since TW works, this should be fine anyway...

**Pull request merged**
