### PR TITLE
Undo split of cobbler-web from cobbler

### PR DESCRIPTION
**Pull request by nacc**
Based upon the discussion at
https://github.com/cobbler/cobbler/pull/1428, undo the split of the
repository by revert of the appropriate commits.

Revert "Split off cobbler-web into a seperate repo/package."
This reverts commit b15b0c35c4b9afe6536c79b64f21d7b7185e621b.

Revert "Remove cobbler_web.conf since cobbler-web is in it's own repo."
This reverts commit e9853bfcc3f9c873a058d081530e65f9ebcea21d.

Signed-off-by: Nishanth Aravamudan <nacc@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by nacc** [comment]
Sorry fixed the commit log and refreshed with an E303 fix.

**Comment by nacc** [comment]
I can continue to work on the landscape issues found, but not sure if they should block the revert?

**Comment by alanoe** [comment]
It seems these issues reported by landscape-bot (probably runs Pylint) already existed in the code before the revert, so +1

**Comment by jmaas** [comment]
thanks a lot nacc!!!

**Comment by nacc** [comment]
Alan, agreed -- I am working on cleaning up as many of them as I can, some are just noisy (e.g., unused variables).

Is the plan to have landscape run clean for 3.0? Just curious if I can hold off on working on it for a bit :) Also, can I run a landscape job myself? Or does it only run via  PR?

**Comment by jmaas** [comment]
Nish,

I haven't found a way to manually trigger a landscape job just yet.
We could integrate pylint into `make qa` to ease local testing.

It would be awesome if code quality for 3.0 could be increased a lot :)

Thanks again!

On Wed, Jun 3, 2015 at 11:31 PM, nacc <notifications@github.com> wrote:

> Alan, agreed -- I am working on cleaning up as many of them as I can, some
> are just noisy (e.g., unused variables).
>
> Is the plan to have landscape run clean for 3.0? Just curious if I can
> hold off on working on it for a bit :) Also, can I run a landscape job
> myself? Or does it only run via PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbler/cobbler/pull/1481#issuecomment-108622186>.
>



-- 
Grtz,
Jörgen Maas

**Pull request merged**
