### PR TITLE
Fix: rename item

### LINKED ISSUE #3350: Cannot rename Items with uppercase characters
### Describe the bug

1. Cobbler allows object names containing uppercase characters, but it is not possible to rename such objects. The renamed object is lost and cannot be recovered.
2. When renaming Items, no lock is set on manipulations with the collection, which can lead to unpredictable behavior.

### Steps to reproduce

1. cobbler menu add --name=Test
2. cobbler menu rename --name=Test --newname=test1
````
exception on server: 'Test'

# cobbler menu list
### ERROR ###
Unexpected remote error, check the server side logs for further info
<class 'AttributeError'>:'NoneType' object has no attribute 'name'
````
3. systemctl restart cobblerd
````
# cobbler menu report --name=Test
No menu found: Test
# cobbler menu report --name=test1
No menu found: test1
````
### Expected behavior

The renaming should happen without errors.

### Cobbler version

````paste below
Cobbler 3.3.3
  source: ?, ?
  build time: Wed Jul 20 00:00:00 2022
````
### Operating system

Fedora 37

### Cobbler log

````paste below
File "/usr/lib/python3.11/site-packages/cobbler/remote.py", line 2151, in xapi_object_edit
self.rename_item(object_type, handle, attributes["newname"], token)
File "/usr/lib/python3.11/site-packages/cobbler/remote.py", line 1657, in rename_item
self.api.rename_item(what, obj, newname)
File "/usr/lib/python3.11/site-packages/cobbler/api.py", line 843, in rename_item
self.get_items(what).rename(ref, newname)
File "/usr/lib/python3.11/site-packages/cobbler/cobbler_collections/collection.py", line 262, in rename
self.listing.pop(oldname)
````

### PR DESCRIPTION
**Pull request by SchoolGuy**
## Linked Items

Fixes #3350 

## Description

Fixes renaming items with uppercase characters.

## Behaviour changes

Old:

- Items with uppercase letters could not be renamed.
- Renaming items was not thread safe

New:

- Items that have uppercase letters can be renamed
- Renaming items is not thread safe

## Category

This is related to a:

- [x] Bugfix
- [ ] Feature
- [ ] Packaging
- [ ] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [x] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [ ] No tests required

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@tpw56j I don't know how hard it is for you to test this PR specifically but it would be cool if you could confirm if my changes make it possible to have case-sensitive names in Cobbler.

**Comment by tpw56j** [comment]
@SchoolGuy I'll test the ability to have case-sensitive names tomorrow.

**Comment by SchoolGuy** [comment]
@tpw56j many thanks!

**Comment by tpw56j** [comment]
@SchoolGuy I tested the patch, everything looks great and I think the problem has been solved.

**Comment by SchoolGuy** [comment]
This PR is tested by a regular contributor that has made significant changes in the past. The code changes themselves are not too extensive and this is related to a bugfix. Lastly, the CI is green.

I have decided to merge this PR without a formal review.

**Pull request merged**
