### PR TITLE
Add new distros to signatures and update isort

### PR DESCRIPTION
**Pull request by tiltingpenguin**
## Description

This PR aims to update the distro signatures for cobbler by adding new versions of supported distros.

This PR will also update the isort dependency to fix a compatibility issue with newer poetry versions.

## Behaviour changes

New: cobbler can be used to install newer distributions

## Category

This is related to a:

- [ ] Bugfix
- [x] Feature
- [ ] Packaging
- [ ] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [x] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [ ] No tests required

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@tiltingpenguin I would kindly ask you to add as many `import-@` tests are possible for the different distros that you added. That we way have at least a good guess that they are importable.

**Comment by SchoolGuy** [comment]
@tiltingpenguin any update on this PR? If you need more time I would love to split out the `pre-commit` `isort` version update.

**Comment by tiltingpenguin** [comment]
Sorry about the delay, I'm still working on the import tests. If you'd like we could merge this PR and I will open another one for the tests

**Comment by tiltingpenguin** [comment]
We discussed that @SchoolGuy will take care of the listings and import tests for esxi and xenserver distros, if we can get access to the ISO files for them

**Review by SchoolGuy — APPROVED** [review]
So according to the VMware ESXi website 7.0 is the most up to date ISO you can get. For this we already have an import test. As we cannot get access to xenserver ISOs as of now (requires to have a company backed account), I will approve this PR and merge it.

**Pull request merged**
