### PR TITLE
Refactor unittest to pytest

### PR DESCRIPTION
**Pull request by SchoolGuy**
This obsoletes `unittest` in the cobbler tests and fixes most of the `xmlrpcapi` tests. Also adds some new tests.

### CODE REVIEW

**Comment by brejoc** [comment]
@jmaas Would you like this to be squashed?

**Comment by jmaas** [comment]
If you mean merged, yes. Feel free :)

**Comment by brejoc** [comment]
@jmaas Yes and no. :smile: I was really asking if this should be squashed. Or would you prefer to keep those 32 commits in master?

**Comment by brejoc** [comment]
Okay, I'm squashing this before merge.

**Pull request merged**
