### PR TITLE
fix: Cannot set property 'file' of image #2877

### LINKED ISSUE #2877: Cannot set property 'file' of image
### Describe the bug

Set image's property 'file' is not working

### Steps to reproduce

1. `touch /tmp/test.iso`
2. Run below Python code on Cobbler installed machine

```
#!/usr/bin/python3
from xmlrpc.client import Server
rpc_server = Server("http://127.0.0.1/cobbler_api")
token = rpc_server.login('cobbler', 'cobbler')
image_handle = rpc_server.new_image(token)
rpc_server.modify_image(image_handle, "name", "testit", token)
rpc_server.modify_image(image_handle, "file", "/tmp/test.iso", token)
rpc_server.save_image(image_handle, token)

img = rpc_server.get_image("testit")
assert(img['file'] == "/tmp/test.iso")
```

### Expected behavior
End without AssertionError

### Cobbler version

````
Cobbler 3.3.0
  source: d8f60bbf, Mon Sep 20 16:55:41 2021 +0200
  build time: Thu Dec 23 06:27:43 2021
````

### Operating system

CentOS 8
### Cobbler log

````paste below
````

### PR DESCRIPTION
**Pull request by cy-lee**
Fixes #2877

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@cy-lee Thanks for the submission of the fix! If possible for you I would appreciate a test so we can check that the desired functionality is working. If you are not able to add this to your PR, I would still merge it and add it later.

**Comment by cy-lee** [comment]
Hi, I modify the unit-test in commit, please help to review it, thank you.

**Comment by SchoolGuy** [comment]
@cy-lee Sorry for taking so long. I was/am out sick. I will merge this once the PR is tested by the CI. Thanks a lot for your contribution!

**Review by SchoolGuy — APPROVED** [review]
LGTM in my eyes. Thanks for the contribution!

**Pull request merged**
