### PR TITLE
item: deduplicate value from resolve decorator

### PR DESCRIPTION
**Pull request by geliwei**

### CODE REVIEW

**Comment by geliwei** [comment]
Create a pre-review to ensure I'm on the right way to fix https://github.com/cobbler/cobbler/issues/3211

**Comment by SchoolGuy** [comment]
@geliwei So if you can prove with a Unit-Test that the logic is working (which it should but I want to be certain that it is), then you are indeed on the right track. If you need help with a test, I will happily assist you. The diff you produced so far looks good from an initial standpoint!

**Comment by SchoolGuy** [comment]
@geliwei Any updates on your progress? Anything I can assist you with?

**Comment by SchoolGuy** [comment]
@geliwei Any updates? If you can't continue, I would take over this PR soon to fix the issue. :)

**Comment by geliwei** [comment]
> @geliwei Any updates? If you can't continue, I would take over this PR soon to fix the issue. :)

sorry, have some urgent tasks last month. I shall take a look this week

**Comment by SchoolGuy** [comment]
@geliwei Sadly you used the `main` branch and not a feature branch. The PR is hard to merge for me. I will cherry pick your commit and integrate it via a separate PR. Thanks for your work!

**Pull request closed without merging**
