### PR TITLE
Improve devel Docker image

### PR DESCRIPTION
**Pull request by SchoolGuy**
This PR is a splitout of #2416 and tries to improve the Docker container in a way that it is more convenient to use. This is achieved through three things:

- Remove the unrequired `python3-simplejson`
- Add the bootloaders for testing functionallity related to this
- Add the scripts directory to the PATH so they can be easier used

### CODE REVIEW

**Review by vzhestkov — APPROVED** [review]
LGTM

**Review by meaksh — APPROVED** [review]

**Comment by SchoolGuy** [comment]
The openSUSE Tumbleweed Docker container seems to be broken when doing a `zypper dup -y`. This is unrelated to this change I (did not touch that Dockerfile on that line or before) and thus I will ignore it.

**Comment by SchoolGuy** [comment]
The openSUSE Leap Docker container is also broken because of an invalid repository. Sad that this is the case but I can't change that.

**Comment by ericchambers1940** [comment]
Hey @SchoolGuy, I'm assuming the invalid repository (or some other issue) is causing the development docker image build to fail? I'm rebuilding my dev environment to resume adding some tests when I ran into this:
image

Is it safe to temporarily comment out the package install for these bootloaders in the meantime?

**Comment by SchoolGuy** [comment]
@ericchambers1940 I was able to build the development images successfully without trouble multiple times. So no this should not fail. Only the RPM builder images seem to be affected. I am having a look after breakfast.

**Comment by SchoolGuy** [comment]
@ericchambers1940 Okay so I investigation is that building TW RPMs in Docker does not work since `overlayfs` and the UsrMerge is not compatible. I can't possibly solve this but need to find a way around it instead. I can't fix this short term though sadly. We need `systemd` as a build dep though which pulls in the UsrMerge...

A solution which would work, is that you don't use the Docker overlayfs driver but another one. Depending on your Docker knowledge I would not recommend this though because this has greater implications.

**Comment by ericchambers1940** [comment]
I see. For the time being, I commented out those failed packages in the Dockerfile since I’m just writing tests at the moment.

**Pull request merged**
