### PR TITLE
Prevent duplicate pathing of snippet filenames

### LINKED ISSUE #2483: Adding snippet via UI retains path
### Describe the bug

I added a snippet via the UI and it shows the snippet in the list with the full path `var/lib/cobbler/snippets/name` prefixed. So use the snippet in a template i have to do the whole path.  and it turns out that the full path got created recursively as `/var/lib/snippets/var/lib/snippets`

```
[root@bootstrap-n01 snippets]# pwd
/var/lib/cobbler/snippets/var/lib/cobbler/snippets
[root@bootstrap-n01 snippets]# ls
root_authorized_key
```

### To Reproduce

1. Open web ui
2. Goto snippet and click add
3. Add the snippet
4. Look at snippet list, and see the path

### Expected behavior

Should just see the filename in the list, and be able to reference it with just `$SNIPPET('filename')`

### Version

```
[root@bootstrap-n01 snippets]# cobbler version
Cobbler 3.2.0
  source: ?, ?
  build time: Sun Oct 25 21:46:20 2020
```

### Screenshots

image

### PR DESCRIPTION
**Pull request by gregswift**
Fixes #2483﻿

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@hbokh If I remember you are using the webui. Could you please confirm?

**Review by SchoolGuy — APPROVED** [review]
LGTM by me. The whole code will be anyway removed with 3.3.0...

**Comment by hbokh** [comment]
> @hbokh If I remember you are using the webui. Could you please confirm?

Yes, we do.

**Comment by SchoolGuy** [comment]
@hbokh Sorry. I was not precise enough... I meant that the changes are fixing the problem.

**Review by hbokh — APPROVED** [review]
LGTM

**Pull request merged**
