### PR TITLE
some SuSE autoyast improvements

### PR DESCRIPTION
**Pull request by Sniper677**
I would like to contribute to your great project by adding some SuSE autoyast code for network configuration and repository addon.

- repo addon (addon.xml) is working in the same way as for RHEL
- improved networking (adding VLAN support, static routing IPv4 and IPv6)
- some code cleanup

**To be discussed:**
- the way how kickstart_start and kickstart_done should work

From my point of view it should be done in the same way as for RHEL by including kickstart_* to autoyast template. While doing that I realized that the curl/wget commands are executed always twice. I found some code (function 'generate_autoyast') in kickgen.py which is also doing it. I think this should be removed there.

### CODE REVIEW

**Comment by jmaas** [comment]
Hi! Nice work, love to merge this!
To answer your question, i agree that generate_autoyast() should not do the pxe toggle.

How to proceed:
- please adjust the code according to your suggestion
- please also target release28 (there will be no more 2.6 releases)
- also target the  master branch.

Please let me know if you have issues with this. Thanks again!

**Comment by Sniper677** [comment]
Hello J.

I will do it, like you suggested.

**Comment by jmaas** [comment]
Awesome! :)

**Comment by jmaas** [comment]
Any news on this?

**Comment by Sniper677** [comment]
Hello J.

Sorry for delay, but some other work kept me busy.
Pull request for master branch was already added ... same for release28 will follow.

**Comment by jmaas** [comment]
Cool, i will merge this in 2.6, even though there will be no more 2.6 releases. Users using local builds from git will still benefit from this.

Thanks a lot!

**Pull request merged**
