### PR TITLE
Fix usage of interfacename none if no interfacename is given

### LINKED ISSUE #2681: New systems have two identical interfaces
### Describe the bug

Running `cobbler system add --name new --profile foobar --mac 11:22:33:44:55:66`
creates a system with two identical interfaces:

```
$ cobbler system add --name new --profile foobar --mac 11:22:33:44:55:66
$ cobbler system report --name new | grep -E '^(Interface =====|MAC Address)'
Interface =====                : default
MAC Address                    : 11:22:33:44:55:66
Interface =====                : None
MAC Address                    : 11:22:33:44:55:66
```

### Steps to reproduce

1. Create a new system via `cobbler system add`

### Expected behavior

There should be only one interface instead of two.

### Cobbler version

````paste below
Cobbler 3.2.1
  source: ?, ?
  build time: Tue Jun 22 15:41:34 2021
````

### Operating system

CentOS 8.

### Cobbler log

````paste below
[Thread-154] 2021-06-22T21:37:57 - INFO | REMOTE get_settings; user(?)
[Thread-155] 2021-06-22T21:37:57 - INFO | REMOTE get_item(system,new); user(?)
[Thread-155] 2021-06-22T21:37:57 - DEBUG | get_item; ['system', 'new']
[Thread-155] 2021-06-22T21:37:57 - DEBUG | done with get_item; ['system', 'new']
[Thread-159] 2021-06-22T21:39:49 - INFO | REMOTE version; user(?)
````

### PR DESCRIPTION
**Pull request by SchoolGuy**
Fixes #2681 

@heroin-moose could you please confirm that this fixes the problem you discovered?

### CODE REVIEW

**Comment by heroin-moose** [comment]
On it.

**Comment by heroin-moose** [comment]
Yes, works for me.

**Comment by SchoolGuy** [comment]
Now waiting for the quality gatekeeper of our code @nodeg :)

**Comment by SchoolGuy** [comment]
The reporter confirmed that this fix is working for him and requested that this may be merged. Thus not waiting for the review from @nodeg .

**Pull request merged**
