### PR TITLE
SUSE: Pass netdevice=<mac> kernel param correctly to linuxrc

### PR DESCRIPTION
**Pull request by watologo1**
This was in our develproject for a while already.
Forgot to submit this upstream.

### CODE REVIEW

**Comment by watologo1** [comment]
Travis failure seem to be wrong. I wonder why we need all these:
 Build CentOS 7 RPMs
 Build CentOS 8 RPMs
 Build Fedora 29 RPMs
 Build Fedora 30 RPMs
 
For master branch latest distro code base should be enough?:
Build CentOS 8 RPMs
Build Fedora 30 RPMs

Travis failure output is from CentOS 7 build and has nothing to do with this pull request:
-ba cobbler.spec
error: Failed build dependencies:
	python36-cheetah is needed by cobbler-3.1.2-1.el7.noarch
make: *** [rpms] Error 1
The command "./tests/build-and-install-rpms.sh el7 dockerfiles/CentOS7.dockerfile" exited with 2.

**Comment by SchoolGuy** [comment]
> For master branch latest distro code base should be enough?:
> Build CentOS 8 RPMs
> Build Fedora 30 RPMs
 
I think it is reasonable if our build works for all distros we support cobbler on. And since it does not hurt to build for the other versions as well I think it is good that we leave them there until they are EOL. @watologo1

**Comment by hbokh** [comment]
> error: Failed build dependencies:
> python36-cheetah is needed by cobbler-3.1.2-1.el7.noarch
> make: *** [rpms] Error 1
> The command "./tests/build-and-install-rpms.sh el7 dockerfiles/CentOS7.dockerfile" exited with 2.

For CentOS7 (still widely used!) `python36-cheetah` was submitted to stable a couple of hours ago and should be available soon.
See https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-afb894fa2f

When it comes to Fedora, maybe drop 29 and add 31 instead?

**Comment by SchoolGuy** [comment]
@hbokh Agreed let's do it like this.

**Pull request merged**
