### PR TITLE
Ported changes for ESXi profiles from 2.8.x to 3.x

### PR DESCRIPTION
**Pull request by Jhongturney**

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@Jhongturney Would you mind fixing the conflict. It is sadly just whitespace. We indent with two spaces. It appears that yours is spaced with single spaces.

**Comment by Jhongturney** [comment]
Well, that commit didn't seem to help :-/ My IDE is set to use 2 spaces, so I'm not sure what happened.

**Comment by Jhongturney** [comment]
> LGTM
> However I am unable to test this against VMware... 😇

We've been using this code in custom builds for months now - it definitely works 😄

**Comment by SchoolGuy** [comment]
Okay this is weird. I will have a look after work why this is still conflicting.

**Comment by hbokh** [comment]
> Okay this is weird. I will have a look after work why this is still conflicting.

Both spacing and JSON markup are different (though valid). Here's the top of a diff:

```diff
1,2c1,2
< {"breeds":
<   {
---
> {
>   "breeds": {
5,18c5,30
<         "signatures":["RedHat/RPMS","CentOS/RPMS"],
<         "version_file":"(redhat|sl|centos)-release-4(AS|WS|ES)[\\.-]+(.*)\\.rpm",
<         "version_file_regex":null,
<         "kernel_arch":"kernel-(.*).rpm",
<         "kernel_arch_regex":null,
<         "supported_arches":["i386","x86_64","ppc","ppc64"],
<         "supported_repo_breeds":["rsync", "rhn", "yum"],
<         "kernel_file":"vmlinuz(.*)",
<         "initrd_file":"initrd(.*)\\.img",
<         "isolinux_ok":false,
<         "default_autoinstall":"sample_legacy.ks",
<         "kernel_options":"",
<         "kernel_options_post":"",
<         "boot_files":[]
---
>         "signatures": [
>           "RedHat/RPMS",
>           "CentOS/RPMS"
>         ],
>         "version_file": "(redhat|sl|centos)-release-4(AS|WS|ES)[\\.-]+(.*)\\.rpm",
>         "version_file_regex": null,
>         "kernel_arch": "kernel-(.*).rpm",
>         "kernel_arch_regex": null,
>         "supported_arches": [
>           "i386",
>           "x86_64",
>           "ppc",
>           "ppc64"
>         ],
>         "supported_repo_breeds": [
>           "rsync",
>           "rhn",
>           "yum"
>         ],
>         "kernel_file": "vmlinuz(.*)",
>         "initrd_file": "initrd(.*)\\.img",
>         "isolinux_ok": false,
>         "default_autoinstall": "sample_legacy.ks",
>         "kernel_options": "",
>         "kernel_options_post": "",
>         "boot_files": []

...
```

**Comment by SchoolGuy** [comment]
@Jhongturney Commit the following to your `signatures.json`: https://gist.github.com/SchoolGuy/6291d31d180526544354357bba864eaf

That should include master + your changes and the diff is resolved.

**Comment by SchoolGuy** [comment]
@Jhongturney You are the expert in this matter... I don't know why GH is messing this up...

```
<<<<<<< esxi_6.x_7.x_signatures
        "version_file_regex": "^(VMware )?ESXi( )?(v)?6(\\.)?5(\\.)?.*$",
=======
        "version_file_regex": "^(VMware )?ESXi (v)?6\\.5.*$",
>>>>>>> master
```

What would be the correct regex in this case? (I will fix it in the webgui so we get this merged.)

**Comment by Jhongturney** [comment]
The top version from my branch would be correct.

**Comment by SchoolGuy** [comment]
Let's wait for CI and get this merged.

**Comment by SchoolGuy** [comment]
Good thing that we waited... The new templates must of course be included in the specfile.

Thus please add after the following Line https://github.com/cobbler/cobbler/blob/7f27c11a85143ce018504fa53142e016607ef9cb/cobbler.spec#L407 the following content: `%config(noreplace) %{_sysconfdir}/cobbler/boot_loader_conf/bootcfg_esxi70.template`

Additionally please do the same for the following line https://github.com/cobbler/cobbler/blob/7f27c11a85143ce018504fa53142e016607ef9cb/cobbler.spec#L409 with this content: `%config(noreplace) %{_sysconfdir}/cobbler/boot_loader_conf/gpxe_system_esxi7.template`.

**Comment by SchoolGuy** [comment]
If the CI in the new PR is going green then this one will be closed.

**Pull request closed without merging**
