### PR TITLE
Fix/general cleanup

### PR DESCRIPTION
**Pull request by SchoolGuy**
This addresses multiple issues at once. Yes I know multi purpose PR's are bad but we are not a lot of devs and the commits are separated.

Fixes:

- https://github.com/cobbler/cobbler/issues/1491
- https://github.com/cobbler/cobbler/issues/1801
- https://github.com/cobbler/cobbler/issues/2058
- https://github.com/cobbler/cobbler/issues/2155
- https://github.com/cobbler/cobbler/issues/2228
- https://github.com/cobbler/cobbler/issues/2262
- https://github.com/cobbler/cobbler/issues/2335

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@ wanghaiqing2015 Please confirm that my fix is working as expected!

**Comment by SchoolGuy** [comment]
@xenlo Would you be able to confirm that the adjusted check is now working on your system?

**Comment by SchoolGuy** [comment]
@dansou901 Do you think my warnings are appropriate enough? Or did I miss a location where you would expect that warning?

**Review by brejoc — APPROVED** [review]
The PR was pretty big, but I think it's okay. :+1:

**Comment by SchoolGuy** [comment]
@watologo1 If by Friday you have not reviewed this PR, I will just merge it. Jochen gave his approval and the CI passes.

**Comment by SchoolGuy** [comment]
So it is Wednesday. Let's merge.

**Pull request merged**
