### PR TITLE
[profile] Set '_next_server_v4/v6' to '<<inherit>>' by default

### PR DESCRIPTION
**Pull request by wy-z**
Signed-off-by: weiyang <weiyang.ones@gmail.com>

Fix https://github.com/cobbler/cobbler/issues/3085.

### CODE REVIEW

**Review by SchoolGuy — APPROVED** [review]
LGTM

**Comment by SchoolGuy** [comment]
I will leave this open until I was able to confirm that the testsuite works locally with Leap. Tumbleweed is sadly broken atm.

**Comment by SchoolGuy** [comment]
@wy-z Could you rebase onto `main` I have fixed the issue with the tests temporarily. Then we should be able to see if this works in the CI.

**Comment by wy-z** [comment]
> @wy-z Could you rebase onto `main` I have fixed the issue with the tests temporarily. Then we should be able to see if this works in the CI.

Done.

**Comment by SchoolGuy** [comment]
@wy-z The commit signature is missing. Would you please be so kind and readd that?

**Comment by wy-z** [comment]
> @wy-z The commit signature is missing. Would you please be so kind and readd that?

I'm sorry for the oversight, it should work now.

**Pull request merged**
