### PR TITLE
Fix /etc/cobbler/pxe/pxesystem_esxi.template file about boot.cfg issue.

### PR DESCRIPTION
**Pull request by nishiokay**
In esxi provisioning, I used system file that created "cobbler system add".
But esxi has been unable to boot with the message that "Configuration error while parsing /boot.cfg".
This issue is due to boot.cfg path does not exist in the system file.

I have fixed this issue.

### CODE REVIEW

**Comment by jmaas** [comment]
What version(s) of ESXi have you tested this with?

**Comment by nishiokay** [comment]
I have tested ESXi5.0, ESXi5.1, ESXi5.5 and ESXi6.0.

**Comment by jmaas** [comment]
Thanks!

**Comment by jmaas** [comment]
Also applied to release28

**Pull request merged**
