### PR TITLE
WIP: Document Terraform provider

### PR DESCRIPTION
**Pull request by hbokh**
**Changes**
- add file `docs/user-guide/terraform-provider.rst`
- updated files: `docs/conf.py` & `docs/user-guide.rst`

Work in progress - as long as Cobbler 3 is not compatible out of the box with any version of terraform-provider-cobbler yet!
In the end it solves #2166.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@hbokh Can we help you somehow with this? After #2268, #2202 and this I would like to release a new version of cobbler.

**Comment by hbokh** [comment]
@SchoolGuy At this moment, the **Terraform Provider Cobbler** will only work, if you "hack" the existing code.

In `cobbler/items/item.py`, this line has to be uncommented:
https://github.com/cobbler/cobbler/blob/master/cobbler/items/item.py#L218
If not, you will get

`Error: Cobbler Profile: Error Creating: Fault(1): <class 'AttributeError'>:'str' object has no attribute 'copy'`.

And also in `cobbler/items/item.py` change `sorted=True` to `sorted=False`:
https://github.com/cobbler/cobbler/blob/master/cobbler/items/item.py#L235
If not, you will get

`Error deleting distro: Fault(1): <class 'TypeError'>:'<' not supported between instances of 'str' and 'NoneType'`

So, to me it looks the caching lines that were added in #1807 break the functioning of the Terraform provider. The issue (and above errors) is (are) not reproducible in Cobbler 2.6.11 and 2.8.5 with the Cobbler provider v1.1.0.

If anyone wants to test / debug this behaviour, we provide pre-compiled binaries here:
https://github.com/wearespindle/terraform-provider-cobbler/releases/tag/v2.0.0

Follow the instructions in this PR to set things up. Will make a nice (weekend) project for those stuck at home during the current Corona outbreak. 🤡

**Comment by SchoolGuy** [comment]
@hbokh I saw that there is some progress on the Terraform side. Can I help somehow on the Cobbler side with anything. I would love to include this rather sooner then later! :)

**Comment by hbokh** [comment]
> @hbokh I saw that there is some progress on the Terraform side. Can I help somehow on the Cobbler side with anything. I would love to include this rather sooner then later! :)

Have a look here: https://github.com/terraform-providers/terraform-provider-cobbler/pull/32#issuecomment-724185387

Quote from the mentioned comment:
_Forking is the easiest path forward for community-maintained providers. If the original maintainer is interested, we can transfer over all open issues and PRs, and mention the new location prior to archiving._

I am unsure and don't have full understanding on how to move forward. The Terraform Registry is still somewhat of a black box to me and I'm having a hard time making time to get into this...
Besides, I was also thinking about moving / forking both `terraform-provider-cobbler` and its dependency `cobblerclient` under the umbrella of Cobbler itself.

**NOTE** Also not feeling safe at all with becoming the "officially designated maintainer" myself, since my "skills" in Golang are puzzle-copy-paste based.

**Comment by SchoolGuy** [comment]
@hbokh Okay then a proposal from my side: Let's fork it to the Cobbler Org and then start to fix things as with Cobbler itself. As we progress this we can see if we can make that blackbox somewhat transparent for us. If it's doesn't work out we won't make the situation worse then it is now. Right?

**Comment by hbokh** [comment]
@SchoolGuy I have *TRANSFERRED* both repositories from wearespindle to cobbler. So not forked.
I will check them out locally and fix pointers to the old owner / organization _wearespindle_.
Hope this is OK with (all) of you.

**Comment by SchoolGuy** [comment]
@hbokh Fine by me. Thanks for the progress on this. I won't have time this weekend but I will take a look as soon as I can.

**Comment by hbokh** [comment]
As far as I can see almost everything should be in place to publish the provider to the Terraform Registry.
Steps to take are described in [Publishing Providers ](https://www.terraform.io/docs/registry/providers/publishing.html).

"Almost", because we need some more things setup.

- I don't think the mentioned `GPG_PRIVATE_KEY` should be base on my ID. Is there a Cobbler one?
- I've authorized Terraform Registry to use GitHub and requested to also allow "Cobbler". There will be a mail in one of your mailboxes with something like this: `A third-party OAuth application (Terraform Registry) with read:org, user:email, and write:repo_hook scopes was recently authorized to access your account.`

I'll add some more to this comment if I find some.

**Comment by SchoolGuy** [comment]
@hbokh Thanks a lot! I will take a look. I have quite a lot on my table currently but I will try my best to do it soon.

**Comment by hbokh** [comment]
@SchoolGuy For some reason I do not have the original repository anymore...
Possibly the result of a bit too enthusiastic cleaning, hence the line in the top of the page shows `unknown repository`.

Anyhow, I pushed a new feature branch with the same name as before AFAIK here:
https://github.com/hbokh/cobbler/tree/feature/document-terraform-provider-%232166

**Comment by SchoolGuy** [comment]
Well the diff gladly still is there. Thus we can still merge. I will have a look on Sunday.

**Comment by hbokh** [comment]
Replaced with PR #2527.

**Pull request closed without merging**
