### PR TITLE
Try to fix CentOS7 CI builds

### PR DESCRIPTION
**Pull request by hbokh**
This PR is related to #2252. But it is **NOT** a complete fix for the CI pipeline.

Changes:
- Makefile: removed doc build from "release", since Sphinx is a rather old version on CentOS7
- Makefile: added `cleandoc`
- cobbler.spec: fixed `RAND_SECRET` that still gave chars sed would choke on
- Centos7.dockerfile: added missing packages and **TEMPORARY** `py36-cheetah`
- install-rpms.sh: added to quickly run a container when RPMs are build already

I'm curious of what Travis will show next... 🤓

### CODE REVIEW

**Comment by hbokh** [comment]
Travis is still wrong... RPM build failed on `sphinx.ext.githubpages`, but still marked green.

**Comment by hbokh** [comment]
That looks better!

**Comment by hbokh** [comment]
@SchoolGuy I guess this proves the fixes for the CI pipeline for now.
The Sphinx docs are a blocker on CentOS7 builds, due to an unsupported version of `sphinx.ext.githubpage`.
I would personally prefer to put the documentation outside of the package builds all together.
E.g. put them under `cobbler/cobbler.github.io` or in a seperate repo. They seem to complicate and slow down standard builds and are not even included inside the RPMs.
My €0,02.

This PR has become somewhat messy and should not be merged. I think it is clear for now where to fix things.

**Comment by SchoolGuy** [comment]
@hbokh I moved a while ago the docs on purpose into this repo to separate the docs (this repo), guides (cobbler.github.io; which we will hopefully have at some point) and docs for developing cobbler (GH-Wiki).

So the only solution which I would feel comfortable with atm is that we put them in a completely separate repo. I put a LOT of effort to achieve what we currently have. The pure build of the docs is happening on rtd and they normally don't complicate the build. We even got their beta feature of building the docs on PR's which is really, really cool! Also we are building our manpages out of the docs folder with Python/Sphinx. The reason why normal builds are not building the docs is because no-one simply put the command (which is prepared) into the build command.

I really want to try to make everyone happy with this project as much as I reasonably can with the time I have. If you disagree with my opinion or have more improvement suggestions then really please speak up. This is a community project not a dictatorship from me.

P.S.: I just looked at the github-pages-plugin of Sphinx and we don't need that because we don't publish the docs on GH-Pages. So we can remove this without any side effects in my eyes.

**Pull request closed without merging**
