### PR TITLE
Do not try to access log file if we are not running as root

### PR DESCRIPTION
**Pull request by opoplawski**
Actually, this may be a fairly reasonable workaround for issue #2440 and the apache logging issue.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
Okay and what happens if Cobbler is not running as root? Because I don't see an else there... Just curious how we solve the problem with this change.

**Comment by opoplawski** [comment]
If we aren't running as root, logging isn't initialized and so doesn't happen.

**Comment by SchoolGuy** [comment]
Is that reasonable? I mean in theory we should be able to fix this, so Cobbler doesn't require root. Right?

**Comment by opoplawski** [comment]
I see this as a stopgap measure for a 3.2.X branch if desired.  Presumably the if would be removed as part of the 3.3 removal of the web interface.  Although I think we're a long way from being able to run cobblerd as non-root (as desirable as that may be).

**Review by SchoolGuy — APPROVED** [review]
Okay this is reasonable but we need to keep in mind what merging this means for us.

**Comment by watologo1** [comment]
Another round of diving into python3 logging details...
There should be a possibility to automagically use one of these handlers depending on the user you are running as?!?:
[handler_FileLogger]
class=FileHandler
level=DEBUG
formatter=formatter
args=('/var/log/cobbler/cobbler.log', 'a')

[handler_FileLoggerApache]
class=FileHandler
level=DEBUG
formatter=formatter
args=('/var/log/cobbler/apache_context.log', 'a')


Anyway, I cannot further try on this (again).
One way to also log apache things could be to set group of:
/var/log/cobbler/cobbler.log
to the apache user (which we already have at several places, like cobbler.spec)
and set group writable flag there...

But logging into 2 separate, configurable files depending on user should be doable and is preferred...

**Comment by SchoolGuy** [comment]
Merging this PR won't hurt us badly because only logging is affected. Noone subjects, thus I will use my admin rights to do so now. @watologo1 pointed another solution out which is dependent on this PR and thus this is another reason to merge this one.

**Comment by SchoolGuy** [comment]
This PR broke `master`. Thus I need to fix this in the evening/later.

**Pull request merged**
