### PR TITLE
Fix some detected issues with tests when running them on different setups

### PR DESCRIPTION
**Pull request by meaksh**
## Description

During the setting up of Cobbler 3.3.3 tests in CI environment, we just found some issues that we fixed and some of them might make sense for Cobbler upstream.

This PR is pushing the candidate fixes so we can discuss and agree if we want them.

## Category

This is related to a:

- [ ] Bugfix
- [ ] Feature
- [ ] Packaging
- [ ] Docs
- [ ] Code Quality
- [ ] Refactoring
- [x] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [ ] System-Tests were created
- [x] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [ ] No tests required

### CODE REVIEW

**Comment by SchoolGuy** [comment]
The fixes themselves seem fine. If you would be so kind to explain why we need to apply each of those fixes, I am happy.

**Comment by SchoolGuy** [comment]
@meaksh I want to stress that I don't want to stop us from merging this PR but I would like to document this reasoning why we need to do the changes we do. The changes themselves are fine. Could you please add a sentence or two per commit please?

**Comment by meaksh** [comment]
Hey @SchoolGuy , I've reworded the commits to include some more details about them. I also dropped one of them as I think I was not really needed for upstream.

**Comment by SchoolGuy** [comment]
@meaksh In regard to `request.node.originalname`: https://docs.pytest.org/en/7.1.x/reference/reference.html?highlight=originalname#pytest.Function.originalname

It was introduced in 3.0. So yes it is due to the pytest version being out of date.

**Pull request merged**
