### PR TITLE
CI: Use prebuilt image for testing

### PR DESCRIPTION
**Pull request by SchoolGuy**
Should be self-explanatory

### CODE REVIEW

**Comment by SchoolGuy** [comment]
Okay I was expecting this to go smoother. Could reproduce locally. Putting this on hold until I have time to investigate further.

**Comment by nodeg** [comment]
I was not able to reproduce this locally:

```bash
❯ docker pull registry.opensuse.org/home/schoolguy/branches/opensuse/templates/images/tumbleweed/containers/opensuse/cobbler-github-ci:l
atest                                                                                                                                                                        
❯ docker pull registry.opensuse.org/home/schoolguy/branches/opensuse/templates/images/tumbleweed/containers/opensuse/cobbler-github-ci:latest                                
latest: Pulling from home/schoolguy/branches/opensuse/templates/images/tumbleweed/containers/opensuse/cobbler-github-ci                                                      
Digest: sha256:507dfba33cc8fda0093a2d9c791f0f90dedf8d7992708bc68d57c5eb365666b7                                                                                              
Status: Image is up to date for registry.opensuse.org/home/schoolguy/branches/opensuse/templates/images/tumbleweed/containers/opensuse/cobbler-github-ci:latest              
registry.opensuse.org/home/schoolguy/branches/opensuse/templates/images/tumbleweed/containers/opensuse/cobbler-github-ci:latest                                              
❯ docker run -t -d --name cobbler-dev -v $PWD:/code registry.opensuse.org/home/schoolguy/branches/opensuse/templates/images/tumbleweed/containers/opensuse/cobbler-github-ci:
latest                                                                                                                                                                       
3fc8871edd7bd991bd95937223aef400c1316cea94935d2d69f6363c6007554f                                                                                                             
❯ docker exec -u 0 -it cobbler-dev bash -c "./docker/develop/scripts/setup-supervisor.sh"                                                                                    
Copy supervisord confiuration file                                                                                                                                           
Install Cobbler                                                                                                                                                              
# Debian/Ubuntu requires an additional parameter in setup.py                                                                                                                 
running install                                                                                                                                                              
running build                                                                                                                                                                
running build_py                                                                                                                                                             
running build_scripts
(...)
changing mode of /usr/local/bin/cobbler-settings to 755
Load supervisord configuration file and wait 5s
Show Cobbler version
Cobbler 3.3.1
  source: 2260d54b, Thu Sep 30 15:22:00 2021 +0200
  build time: Fri Oct  1 06:38:03 2021
```

**Comment by SchoolGuy** [comment]
@nodeg I guess then we are back at glibc 2.34 problems?

**Comment by nodeg** [comment]
Maybe. I have the following on my system:
```bash
❯ rpm -qa | grep glibc
glibc-2.34-1.2.x86_64

❯ rpm -qa | grep docker
docker-20.10.6_ce-2.1.x86_64
```

**Review by watologo1 — APPROVED** [review]
Nice!

Isn't it possible to use some general container registry or does one have to have an account for this?
It would be nice to get the user account specific part out of it:
schoolguy
But I fear there is no way around that?

**Comment by nodeg** [comment]
Dockerhub would be a solution, too but there is already a Cobbler project which is not related to us.

**Comment by agraul** [comment]
What is wrong with building the container in OBS and thus publishing it to its registry at registry.opensuse.org?

I agree that Enno's home project is not the best location for an cobbler testing container "package", but that can be fixed by moving it somewhere else...

**Comment by nodeg** [comment]
Personally the OBS is my favorite, too when we find a suitable project location for Cobbler.

**Comment by SchoolGuy** [comment]
We can't move my name out of there except we submit it to factory. And I doubt that Factory Maintainers accept a CI image in the registry. Be aware that only branched repositories from the template repository appear in the obs registry. We have a wiki Page for that where this is documented also.

**Comment by agraul** [comment]
>  Be aware that only branched repositories from the template repository appear in the obs registry.

Are you sure that we can't do either of these two options?

1) branch again and move everything needed 
 2) move everything including the `_link` file 

Is there another mechanism (i.e. not through `_link`) that OBS uses to detect branched packages? If not then 2) should work, but I haven't done much on the container-building side of OBS.

> We have a wiki Page for that where this is documented also.

Which wiki is it in? Can you link to it?

**Comment by SchoolGuy** [comment]
@agraul here you go: https://en.opensuse.org/Building_derived_containers

**Comment by SchoolGuy** [comment]
GitHub Runners still not updated...

**Comment by SchoolGuy** [comment]
Rebase onto `master`-branch.

**Comment by SchoolGuy** [comment]
This is a big improvement. We go down from 10-12 minutes to 3!

**Pull request merged**
