### PR TITLE
Notify to systemd when cobblerd startup is finished

### LINKED ISSUE #3518: Notify to "systemd" when "cobblerd" startup has finished
### Is your feature request related to a problem?

As a sysadmin or developer,
I want to make "cobblerd" to notify "systemd" about cobblerd service startup has finished
so that I can have other dependand systemd services waiting until "cobblerd" is really ready to accept requests.

### Provide a detailed description of the proposed feature

By using `Type=notify` at systemd service definition for "cobblerd", this makes systemd to wait until "cobblerd" notifies the startup is finished. This makes "systemd" to not consider the "cobblerd" service as "active" until it receives the notification from "cobblerd".

### Alternatives you've considered

None

### Additional information

None

### PR DESCRIPTION
**Pull request by meaksh**
## Linked Items

Fixes #3518 

## Description

This PR makes `cobblerd` to notify systemd when the service has finished the startup. This is particularly useful when cobblerd startup time is high, so other dependant systemd services can properly wait for cobblerd to be ready to accept requests.

## Category

This is related to a:

- [ ] Bugfix
- [x] Feature
- [ ] Packaging
- [ ] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [x] No tests required

### CODE REVIEW

**Review by SchoolGuy — CHANGES_REQUESTED** [review]
@meaksh I have a few comments:

- For the container case this needs to be an optional import and the dependency needs to be moved into an extra in `setup.py`.
- We need a second PR that adds this to the Docker containers.
- Since this is a new feature we need a tracker issue. Linking PRs directly is not working with towncrier afaik.
- Lastly the dependency that you are using for this is a placeholder afaik - https://pypi.org/project/systemd/ - the project that should be used instead is https://pypi.org/project/cysystemd/.

**Comment by meaksh** [comment]
Thanks for the review!

> @meaksh I have a few comments:
> 
> * For the container case this needs to be an optional import and the dependency needs to be moved into an extra in `setup.py`.

This seems to work fine inside a container, it does not produce any exception. I don't think we need an optional import here:

```console
d71b97250408:/ # python3
Python 3.11.5 (main, Aug 31 2023, 07:57:41) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import systemd.daemon
>>> systemd.daemon.notify("READY=1")
False
>>> 
```

> * We need a second PR that adds this to the Docker containers.

Ah right! I will have a look and will update this PR to include necessary changes (unless you explicitely want a separated PR for this)

> * Since this is a new feature we need a tracker issue. Linking PRs directly is not working with towncrier afaik.

Ok, I'll prepare the issue and link it here.

> * Lastly the dependency that you are using for this is a placeholder afaik - https://pypi.org/project/systemd/ - the project that should be used instead is https://pypi.org/project/cysystemd/.

Hmmm, I think there a mess with the names here. What I really want is this: https://pypi.org/project/systemd-python/ , which is packaged at OBS as `python-systemd`.

I'll adjust the `spec` and `setup.py`  files accordingly once I've double checked this.

**Comment by meaksh** [comment]
@SchoolGuy this should be now ready:

- Issue has been created and linked. Now changelog file name is based on the issue number.
- The containers have been fixed to include the new dependency or necessary build dependency.
- The `spec` and `setup.py` has been fixed accordingly.

The current failures we see for the CI in this PR are caused because the CI container image doesn't contain yet the changes included in this PR.

I've built the `develop` container image locally based on this branch and then unit tests were able to successfully run on top:

```
# docker exec -u 0 -it cobbler bash -c "./docker/develop/scripts/setup-supervisor.sh"
[...]
make -C system-tests bootstrap
scripts/bootstrap
cobblerd: stopped
cobblerd: started
task started: 2023-11-17_123822_Create bootable bootloader images_2945f4af5b054e3891bf2e57aa51c001
task started (id=Create bootable bootloader images, time=Fri Nov 17 12:38:22 2023)
start_task(mkloaders); event_id(2023-11-17_123822_Create bootable bootloader images_2945f4af5b054e3891bf2e57aa51c001)
syslinux version 4 detected! Skip making symlink of "ldlinux.c32" file!
GRUB2 modules directory for arch "aarch64" did no exist. Skipping GRUB2 creation
GRUB2 modules directory for arch "arm" did no exist. Skipping GRUB2 creation
GRUB2 modules directory for arch "arm64-efi" did no exist. Skipping GRUB2 creation
Successfully built bootloader for arch "i386-efi"!
Successfully built bootloader for arch "i386-pc-pxe"!
GRUB2 modules directory for arch "i686" did no exist. Skipping GRUB2 creation
GRUB2 modules directory for arch "IA64" did no exist. Skipping GRUB2 creation
GRUB2 modules directory for arch "powerpc-ieee1275" did no exist. Skipping GRUB2 creation
Successfully built bootloader for arch "x86_64-efi"!
*** TASK COMPLETE ***

# docker exec -u 0 -it cobbler bash -c "pytest --benchmark-skip"
================================== test session starts ==================================
platform linux -- Python 3.11.5, pytest-7.4.3, pluggy-1.3.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005
max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /code
configfile: pytest.ini
testpaths: tests
plugins: cov-4.1.0, mock-3.12.0, anyio-3.6.2, benchmark-4.0.0
collected 1778 items
[...]
=============== 1516 passed, 262 skipped, 3 warnings in 381.81s (0:06:21) ===============
```

So, once this PR is merged and OBS rebuild the CI containers, then CI tests should successfully run again.

**Review by SchoolGuy — CHANGES_REQUESTED** [review]
Almost okay. Please add the dependency also to the release workflow it is working very similar to the one for the wheel.

**Comment by meaksh** [comment]
> Almost okay. Please add the dependency also to the release workflow it is working very similar to the one for the wheel.

Done!

**Review by SchoolGuy — APPROVED** [review]

**Comment by SchoolGuy** [comment]
@meaksh feel free to merge at your own pace.

**Pull request merged**
