### PR TITLE
Add Virtuozzo distribution support

### PR DESCRIPTION
**Pull request by scsnow**
Virtuozzo is a Linux distribution based on CentOS sources. More information can be found here: https://virtuozzo.com/products/virtuozzo-linux/

### CODE REVIEW

**Comment by jmaas** [comment]
Nice to have another platform supported! Could you also please create a pull request for the release28 branch? It would be awesome to have this platform supported in the next release.

**Comment by jmaas** [comment]
backporting to release28 requires more time than i have, so merging just to master.

**Comment by scsnow** [comment]
Thanks, I'll backport for r28 myself and submit separate merge request.

**Comment by jmaas** [comment]
awesome!

**Pull request merged**
