### PR TITLE
Use inst.ks= instead of ks=

### PR DESCRIPTION
**Pull request by opoplawski**
EL7 uses this which is as far back as we should support.  No idea about the esx stuff.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@opoplawski To make this work we also need to change the occurrences in `tftpgen.py`. And I guess then we may need to adjust some tests.

**Comment by opoplawski** [comment]
I believe I have changed all the needed occurrences in tftpgen.py.  What tests need to be adjusted?  I don't see any failures.

**Review by SchoolGuy — APPROVED** [review]
LGTM in my eyes. Tests are passing (I am surprised), thus let's get this into our main branch.

**Review by hbokh — APPROVED** [review]
LGTM too.
Though I fail to see why this is exactly needed to solve what problem. :-)

**Comment by SchoolGuy** [comment]
@hbokh Redhatish Systems are using as a kernel argument for the kickstart file `ks.inst` instead of the old `ks`.

**Pull request merged**
