### PR TITLE
Add Oracle Linux Server

### PR DESCRIPTION
**Pull request by sbluhm**
Adding Oracle Linux Server.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@sbluhm Could you please switch the branch to `master`? Or is this a backport?

**Comment by sbluhm** [comment]
@SchoolGuy this specific one is a backport. Am creating the 3.3 and master version at this moment.

**Comment by SchoolGuy** [comment]
@sbluhm Thanks. The `master` version is gladly accepted. In regard to the backports I need to check in the upcoming days how I want to handle them. A version for 3.3.x you don't need to prepare as I will cherry pick from `master` for the next release.

**Comment by sbluhm** [comment]
@SchoolGuy correction: This is a backport only. Master/3.3 are there already. For the backport, I am aware :)

**Comment by SchoolGuy** [comment]
@sbluhm Okay. Since i don't believe I need to push another 3.2.x version I will merge this PR. I don't believe it is linked to your PR that the CentOS 8 tests are failing. However that the normal tests are failing seems to be indeed a problem because Cobbler is not started. Could you have a look please?

**Comment by sbluhm** [comment]
CentOS 8 build is failing because of missing installation repo:
`Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist`

Not sure on the normal tests. Let me have a look. This change works fine on a live system (as far as I can tell).

**Comment by sbluhm** [comment]
@SchoolGuy the same tests are failing on the original 3.2 release: https://github.com/cobbler/cobbler/runs/5362088767?check_suite_focus=true . So I would say that the failure is not related to this PR.

Any chance you can tell me how to test this locally? Then I might be able to trace the issue better and take the time to look at it.

**Comment by SchoolGuy** [comment]
@sbluhm If it is already happening then I believe that it is fine.

In case you still want to test: here is our wiki page for testing: https://github.com/cobbler/cobbler/wiki/Testing

**Comment by sbluhm** [comment]
@SchoolGuy can you please merge? I would look into the test cases later and see what i can do. This doesn't look like a 5 min job for me so want to take my time between other prios.

**Pull request closed without merging**
