### PR TITLE
Fixes issue #2828 by converting arch from enums.Archs to enums.RepoArchs

### LINKED ISSUE #2828: cobbler import fails to identify the apt repo in ubuntu import
### Describe the bug

<!--- A clear and concise description of what the bug is. -->

<!--- HINT: You can paste gist.github.com links for long logs or larger files -->

### Steps to reproduce

1. mount ubuntu iso
2. cobbler import --name ubuntu-server-20_04_2-focal-casper --path /mnt/cobbler-import --arch x86_64 --breed ubuntu                                                                                                                                                                                                              

the import works up until the very end:
```
...
checking for apt repo(s)
adding apt repo for ubuntu-server-20_04_2-focal-casper-casper-x86_64
Exception occurred: <class 'TypeError'>
Exception value: arch needs to be of type enums.RepoArchs
Exception Info:
!!! TASK FAILED !!!
```

### Expected behavior

from cobbler 3.2.2

```
creating new profile: ubuntu-server-20_04_2-focal-casper-casper-x86_64                                                                                         
associating repos                                                                                                                                                                                                                                                                                                             
checking for apt repo(s)                                                                                                                                       
adding apt repo for ubuntu-server-20_04_2-focal-casper-casper-x86_64                                                                                                                                                                                                                                                          
Added repos for ubuntu-server-20_04_2-focal-casper-casper-x86_64    
*** TASK COMPLETE ***                                                              
```
<!--- A clear and concise description of what you expected to happen. -->

### Cobbler version

cobbler-3.3.0-2

This is with the patch that fixes cobbler import. 
<!--- Paste output from `cobbler version` -->
````paste below
````

### Operating system

Fedora 33

### Cobbler log

<!--- Paste (partial) output from `/var/log/cobbler/cobbler.log` -->
```
[2021-10-27_154939_import] 2021-10-27T15:50:13 - INFO | associating repos
[2021-10-27_154939_import] 2021-10-27T15:50:13 - INFO | checking for apt repo(s)
[2021-10-27_154939_import] 2021-10-27T15:50:13 - INFO | adding apt repo for ubuntu-server-20_04_2-focal-casper-casper-x86_64
[2021-10-27_154939_import] 2021-10-27T15:50:13 - INFO | Exception occurred: <class 'TypeError'>
[2021-10-27_154939_import] 2021-10-27T15:50:13 - INFO | Exception value: arch needs to be of type enums.RepoArchs
[2021-10-27_154939_import] 2021-10-27T15:50:13 - INFO | Exception Info:
  File "/usr/lib/python3.9/site-packages/cobbler/remote.py", line 99, in run
    rc = self._run(self)

  File "/usr/lib/python3.9/site-packages/cobbler/remote.py", line 305, in runner
    self.remote.api.import_tree(

  File "/usr/lib/python3.9/site-packages/cobbler/api.py", line 1598, in import_tree
    import_module.run(path, mirror_name, network_root, autoinstall_file, arch, breed, os_version)

  File "/usr/lib/python3.9/site-packages/cobbler/modules/managers/import_signatures.py", line 272, in run
    self.repo_finder(distros_added)

  File "/usr/lib/python3.9/site-packages/cobbler/modules/managers/import_signatures.py", line 670, in repo_finder
    repo_adder(current_distro_added)

  File "/usr/lib/python3.9/site-packages/cobbler/modules/managers/import_signatures.py", line 817, in apt_repo_adder
    repo.arch = distribution.arch

  File "/usr/lib/python3.9/site-packages/cobbler/items/repo.py", line 428, in arch
    raise TypeError("arch needs to be of type enums.RepoArchs")

[2021-10-27_154939_import] 2021-10-27T15:50:13 - ERROR | ### TASK FAILED ###
```

### Additional information

<!--- Add any other context about the problem here. -->

### PR DESCRIPTION
**Pull request by holmesb**
Ubuntu 20.04 now imports

Fixes #2828

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@holmesb Would it be possible if you add a testcase for this? It should only be a matter of parameterizing `test_arch()` in `tests/items/repo_test.py`.

**Comment by holmesb** [comment]
@SchoolGuy, pls let me know if this test is what you had in mind.

**Comment by SchoolGuy** [comment]
@holmesb Sadly not exactly. I had in mind something like this: https://docs.pytest.org/en/latest/how-to/parametrize.html We do use this technique on multiple occasions in Cobbler already and I would love to have it here as well. If you feel this is over your head then I will approve and do it myself. No pressure there.

**Review by SchoolGuy — APPROVED** [review]
LGTM already.

**Comment by holmesb** [comment]
@SchoolGuy, pls let me know again

**Review by SchoolGuy — APPROVED** [review]
Beautiful test now! This will get merged ASAP!

**Pull request merged**
