### PR TITLE
fix getting ip address

### PR DESCRIPTION
**Pull request by thiller2018**
The current code tried to get the ip adress via for rrset in answers.response.additional, which is empty on my system (openSUSE).
So I added another dns query to get the ip address.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@thiller2018 Would you mind fixing your syntax error?

**Comment by SchoolGuy** [comment]
````
cobbler/modules/nsupdate_add_system_post.py:103:25: E711 comparison to None should be 'if cond is None:'
cobbler/modules/nsupdate_add_system_post.py:104:46: E231 missing whitespace after ','
cobbler/modules/nsupdate_delete_system_pre.py:103:25: E711 comparison to None should be 'if cond is None:'
cobbler/modules/nsupdate_delete_system_pre.py:104:46: E231 missing whitespace after ','
````

**Comment by thiller2018** [comment]
code issue fixed

**Comment by SchoolGuy** [comment]
Well this seems not that critical to merge (regarding negative side-effects to other code parts). So let's bring it into master!

**Pull request merged**
