### PR TITLE
Update distro_signatures.json

### PR DESCRIPTION
**Pull request by nthrow**
FreeBSD 9.3-10.2 working signatures.

### CODE REVIEW

**Comment by hddang1** [comment]
Hi, I am trying to import sles12 sp1 into Cobbler but got the "No signature matched in /var/www/cobbler/ks_mirror/sles12-sp1-gmc3-x86_64" error.   Can someone tell me where to get the distro_signatures.json file that has the sles12sp1?    Thank you.

**Comment by opoplawski** [comment]
nthrow - This seems to contradict the original 10.0 addition from #1461 can you comment on the differences?
~~~~~
-    "signatures":["release"],
-    "version_file":"10\\.0\\-RELEASE",
-    "version_file_regex":null,
+    "signatures":["boot"],
+    "version_file":"freebsd-version",
+    "version_file_regex":"USERLAND_VERSION=\"10.0-RELEASE\"",
~~~~~
I don't use FreeBSD so can't comment.

**Comment by opoplawski** [comment]
@hddang1 - Doesn't look like there is one, but it should be pretty obvious how to fix.  Please submit a separate PR for it instead of hijacking this one.

**Comment by hddang1** [comment]
Sure.  I am a new user here.  Can you please point me to the instruction for filling a PR?   Thanks again.

**Comment by nthrow** [comment]
Pardon my delayed response.  

The original signature for FreeBSD 10.0 was incorrect for that release.  The updated signatures that I submitted were tested and verified with help from a participant in the IRC channel.  It seems that the filename for the release notes had changed since the initial signature was generated, as had the version string therein.  I can confirm these signatures function for their respective releases in cobbler 2.6.10-1.el6.  

Please let me know if there are further questions.

\nat

**Comment by opoplawski** [comment]
Thanks.

**Comment by opoplawski** [comment]
@nthrow Would you be willing to do PRs for master and release28 as well?

**Pull request merged**
