### PR TITLE
ESXi 6.x and 7.x signatures

### PR DESCRIPTION
**Pull request by Jhongturney**
Fixed regex in distro_signatures for ESXi 6.5/6.7 after recent changes by VMware
Added support for ESXi 7.0 based on beta/GA release

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@Jhongturney Would you mind opening this against `master` again?

**Comment by Jhongturney** [comment]
> lgtm! But can anybody double check the `version_file_regex`. I don't have access to an ESXi to check that.

Images that I'm trying to build with report their version as:
ESXi650
vs:
VMware ESXi 6.5.0

Same goes for 6.7.  I think it must have changed in a recent patch from VMware.

**Comment by SchoolGuy** [comment]
Codacy does not behave. Anyway. We have two approvals and CI is green.

**Comment by vuile** [comment]
Support for ESXi 7.0 is in release28 branch but not in release30 branch. Or am I missing something?

**Comment by mpsOxygen** [comment]
While the 3.1.2 release notes mention this PR as being merged there is not signature for esxi7 in release 3.1.2.

**Pull request merged**
