### PR TITLE
Remove cobbler internal python tftp daemon implementation

### PR DESCRIPTION
**Pull request by watologo1**

### CODE REVIEW

**Comment by SchoolGuy** [comment]
We will merge this for 3.3.0 so we don't introduce breaking changes in a minor version. Otherweise fine by me!

**Comment by SchoolGuy** [comment]
@watologo1 Please rebase onto master as our CI has changed and I want to be sure that this causes no side effects.

**Review by SchoolGuy — COMMENTED** [review]
See comment from the Conversation.

**Review by SchoolGuy — APPROVED** [review]
LGTM in my eyes. As discussed this can now be merged.

**Comment by SchoolGuy** [comment]
@watologo1 There is one failing test. Could you please adjust that!

**Review by nodeg — APPROVED** [review]
I fixed the failed test and edited the `cobbler-conf.rst` file to remove `tftpd_py` there, too.

**Pull request merged**
