### PR TITLE
Shebang

### PR DESCRIPTION
**Pull request by kwizart**
Few fixes for shebangs and an empty file.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
Cool that you found this! I personally have nothing against the `/usr/bin/env  python3` but there are certainly people like the opensuse build service package maintainers which are not happy about this. They prefer to have it like this: `/usr/bin/python3`. I will check with them asap and then decide which way we go.

**Comment by kwizart** [comment]
Thx, the Fedora (EPEL) guideline only mention env to the fix for un-versionned python issue.
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#Multiple_Python_Runtimes

So the main issue here is to have python3 instead of python. But I can change to /usr/bin/python3 if prefered.

**Comment by SchoolGuy** [comment]
That would be indeed preferred at least for the opensuse build service. And since `/usr/bin/python3` is a pretty common shebang I would love to see if we use this one.

**Comment by kwizart** [comment]
forced-pushed with the /usr/bin/python3 shebang

**Pull request merged**
