### PR TITLE
setup.py: Fix logger

### LINKED ISSUE #3035: Logging in setup.py
### Describe the bug

At the moment we are using a custom logger. This is wrong because this is not adding to the log from the build.

### Steps to reproduce

1. `make install`

### Expected behavior

The log should show the custom log messages we added.

### Cobbler version

````paste below
main
````

### Operating system

openSUSE Leap

### Cobbler log

````paste below
````

### Screenshots

Not applicabel

### Additional information

Discovered while working on #3004

### PR DESCRIPTION
**Pull request by SchoolGuy**
Fixes #3035

### CODE REVIEW

**Review by vzhestkov — APPROVED** [review]
Looks good

**Comment by SchoolGuy** [comment]
Sigh... A `SEGFAULT` from the LDAP tests again. This is definitely not related to this change. Let's ignore this for now.

**Review by agraul — COMMENTED** [review]
LGTM

**Comment by agraul** [comment]
Whoops, I wanted to review the backport :laughing:

**Pull request merged**
