### PR TITLE
replace /srv/tftpboot with config variable in cobbler.conf; variable …

### PR DESCRIPTION
**Pull request by thiller2018**
…is in setup.py

replace the static path /srv/tftpboot into a setup.py config variable.
The path for non-SUSE systems is taken from google search...

### CODE REVIEW

**Comment by watologo1** [comment]
Nice!
I try to come up with an on-top fix which passes tftproot from spec file to setup.py.
Be careful, the dirs we use in spec file are slightly different.
You also forgot /etc/cobbler/settings
Thanks for bringing this up with a nice starting patch!

**Comment by watologo1** [comment]
Could you have a look at this one, please:
https://github.com/cobbler/cobbler/pull/2349

Be careful absolutely untested.
Your patch could then go on-top without the setup.py change.
And you need to add @@tftproot@@ to /etc/cobbler/settings as well (if this all works as expected).

This is all not nice, but at least variables are finally defined at one place (.spec)

**Comment by SchoolGuy** [comment]
@thiller2018 First of all: Thanks for your effort.

But: You deleted `setup.py` and you merged with upstream. I would prefer if you rebase and thus not delete `setup.py`.

**Comment by thiller2018** [comment]
Fixed with commit "using environment variables" from June 5th.

**Comment by watologo1** [comment]
> Fixed with commit "using environment variables" from June 5th.

Not really. I only added the setup.py part.
I now submitted this one:
https://github.com/cobbler/cobbler/pull/2359
And used your name/email @thiller2018 as the original patch was from you. Would be nice if you can have  a quick look at it and verify that you are ok with it. Thanks!

**Pull request closed without merging**
