### PR TITLE
Cobbler 3.3.x - Enable Sphinx 7 compatibility

### LINKED ISSUE #3455: Changes needed to accomodate Sphinx 7.x
### Describe the bug

If Sphinx 7.x is installed, during builds, the build fails with an error such as the following:

````(venv) [cinnion@wing-1 cobbler]$ make webtest
rm -rf //usr/share/cobbler
make savestate
Traceback (most recent call last):
  File "/home/cinnion/git.github/cobbler/setup.py", line 17, in <module>
    from sphinx.setup_command import BuildDoc
ModuleNotFoundError: No module named 'sphinx.setup_command'
make[1]: *** [Makefile:137: savestate] Error 1
make: *** [Makefile:132: devinstall] Error 2
````

The problem is caused by the removal of setup_command from Sphinx 7.x as a part of the removal of support for Setuptools.

### Steps to reproduce

1. Install/upgrade to Sphinx 7.x
2. Attempt to build (e.g. `make webtest`)
3.

### Expected behavior

The build should have proceeded without an error.

### Cobbler version

````
Cobbler 3.3.3
  source: fcabb2b7, Wed Jun 21 08:53:01 2023 +0200
  build time: Wed Jun 21 23:57:10 2023
````

### Operating system

Rocky Linux release 9.2 (Blue Onyx)

### Cobbler log

````paste below
````

### Additional information

The build works fine up to Sphinx 6.2.1.

### PR DESCRIPTION
**Pull request by opoplawski**
## Linked Items

Fixes #3455

## Description

Fixes doc build with Sphinx 7

## Category

This is related to a:

- [x] Bugfix
- [ ] Feature
- [ ] Packaging
- [x] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [ ] No tests required 

This is completely untested by me.

### CODE REVIEW

**Comment by opoplawski** [comment]
So my 3.3.3 build with this patch seems to be failing to generate the docs.  Any idea what I'm missing?

**Comment by opoplawski** [comment]
Nevermind, I found my issue - not calling make in my spec file.  Near as I can tell the test failure is due to the tests trying to use Fedora 35 which is now archived?

**Review by SchoolGuy — APPROVED** [review]
LGTM

**Comment by SchoolGuy** [comment]
@opoplawski Is there a way to point to an URL that will keep available long-term so we don't have to change it all the time?

**Comment by opoplawski** [comment]
I'm not aware of anything currently.  I've asked if one could be provided: https://lists.fedorahosted.org/archives/list/devel@lists.fedoraproject.org/thread/AALO644AU4G2URKGRMQCOOJPJRBQN3HP/

**Comment by opoplawski** [comment]
How about:
```
http://download.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os
https://mirrors.fedoraproject.org/mirrorlist?repo=rawhide&arch=x86_64
https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=x86_64
```

**Comment by SchoolGuy** [comment]
@opoplawski As those URLs are unrelated to this PR, I think I will merge this PR (after you signed the commit) and we then tackle this in another PR. How does this sound to you?

**Comment by opoplawski** [comment]
I think I've managed to sign the last commit.  I'm not sure how to sign the previous one.  I'll file another PR for the URL change.

**Comment by SchoolGuy** [comment]
@opoplawski Here you go: https://superuser.com/a/1123928

```
git rebase --exec 'git commit --amend --no-edit -n -S' -i release33-sphinx7
```

**Comment by opoplawski** [comment]
That didn't seem to work, but I think I've managed to sign the two commits now.

**Pull request merged**
