### PR TITLE
Feature/check json validity

### PR DESCRIPTION
**Pull request by SchoolGuy**
## Linked Items

Fixes #

## Description

This PR is addressing the area of `cobbler check`:

- ~~Add a new check that checks if the `_children` attribute contains empty strings and correct that immediately.~~ - @agraul was so kind to point out that this is pointless in the `main` branch as of #3301.
- Use `shutil.which()` to check for binaries instead of `os.path.exists()`.
- ~~Restore the old `SELinux` page that was previously in the GitHub Wiki.~~ - #3523

## Behaviour changes

Old: `cobbler check` uses absolute paths to check for tooling.

New: `cobbler check` uses `shutil.which` to check for tooling.

## Category

This is related to a:

- [ ] Bugfix
- [ ] Feature
- [ ] Packaging
- [ ] Docs
- [x] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

> Tests not yet created due to this being a Draft/RFC PR.

- [x] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [ ] No tests required

### CODE REVIEW

**Review by agraul — CHANGES_REQUESTED** [review]
Does it really make sense to have this new check in `main` where children are not read from the json files?

**Comment by SchoolGuy** [comment]
@agraul You are indeed right about your concerns. At first, I thought I should implement this as a generic check, but the effort for that seemed too big in the end. That's why I only looked at the children. I will go back to the drawing board and think about a better solution...

**Comment by SchoolGuy** [comment]
I created this PR initially to bring a fix for the potential inconsistencies of `children` in Cobbler 3.3.3 but on `main` those can't happen in the same way anymore. As such I will need to think of another solution for this problem that is specific to the 3.3.x release branch.

**Comment by SchoolGuy** [comment]
So in light of my workload, I will close this PR. I can't work on it and it doesn't add much benefit to the application. Furthermore, the JSON is only written to disk on a deserialize call which means that the data on disk is not always on par with the in-memory data.

**Pull request closed without merging**
