### PR TITLE
Change the style on cobbler web

### PR DESCRIPTION
**Pull request by theofilis**
Please check mine changes on cobbler web.

### CODE REVIEW

**Comment by jmaas** [comment]
Gonna check this out this weekend, please have patience :)

**Comment by alanoe** [comment]
- Main questions: Was this UI redesign discussed somewhere? What current problems it tries to fix?
- I see this patch adds Bootstrap dependency. Do we need it?
- There are too many changes in each patch and the scope of each one of them is not well-defined and clear in commit msg, please rebase

**Comment by jmaas** [comment]
So it took a while longer, excuse the delay.

I actually like the improvements there are some things i'd like to see different:
- the footer; i don't like all the links to external references, can we just have a thin footer?
- the first screen after logging in is quite empty, it would be nice if we could have some dashboard like views there (number of distros/profiles/systems)
- settings screen; settings should be directly editable without clicking the settings link

Are you willing to make some more improvements and maintain the web interface for a while?

**Comment by jmaas** [comment]
@alanoe in normal circumstances i'd agree with you. but the fact of the matter is that no-one is maintaining cobbler right now. this means that we should welcome user contributions, since that is the only thing that keeps the project alive.

**Comment by jmaas** [comment]
also releasing a major version with a new look is awesome

**Comment by jmaas** [comment]
Without longer term commitment as to maintaining this, i can not merge this in it's current form (there are some bugs).

**Comment by jmaas** [comment]
Too bad, but i have to close this PR

**Pull request closed without merging**
