### PR TITLE
Improve startup performance

### PR DESCRIPTION
**Pull request by watologo1**
_Copied by @SchoolGuy from #2840_ 

This PR fixes https://github.com/cobbler/cobbler/issues/2804

The goal of this PR is to find a way to increase the startup time to a reasonable performance level.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@watologo1 What is the difference to #2840? Can this PR be seen as a new revision of that PR?

**Comment by AaronBandt** [comment]
@SchoolGuy Can you provide a little more context on what you would consider the proper solution to this problem? I tried deploying 3.3.3 on one of our medium sized cobbler nodes with approximately 2,900 systems and starting/syncing cobbler takes just over an hour. This is a show stopper for us and I'd like to see if I can contribute to the proper solution so we can get off of 2.8.5. Thanks!

**Comment by SchoolGuy** [comment]
@AaronBandt I will answer you in #2804 because there is already a lot of context for this problem there.

**Comment by SchoolGuy** [comment]
Since November 2021 there is no activity in this PR (if one includes the predecessor). I will just close this PR thus.

**Pull request closed without merging**
