### PR TITLE
add httpboot config

### PR DESCRIPTION
**Pull request by thiller2018**
#2102 add httpboot to cobbler

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@watologo1 Review reminder.

**Comment by SchoolGuy** [comment]
@watologo1 Again! Review reminder.

**Comment by hbokh** [comment]
Sorry for crashing into a late party...
On my two Cobbler 3 installations (Debian & CentOS) I don't have anything Cobbler related in `/srv/` anymore.
Instead, grub & images are in `/var/lib/tftpboot/grub`.
Is there something missing or did I miss something myself?

**Comment by SchoolGuy** [comment]
@hbokh You make a totally valid point here. On Debian based systems the folders are different. Thus we need to replace the path depending on the distro. I will create an issue for that. As a quick fix you can of course adjust the paths manually in the config files.

**Comment by hbokh** [comment]
| On Debian based systems the folders are different.

FYI The paths are also missing in CentOS 7.
Only SUSE is pointing to `/srv/tftpboot` in `cobbler.spec`.

**Pull request merged**
