### PR TITLE
Enable all tests

### PR DESCRIPTION
**Pull request by SchoolGuy**
This PR is aiming to fix all the currently skipped tests.

TODO-Checklist:

- [x] Implement the tests which are currently raising a not implemented exception
- [x] Cut through the tests which are glued together in a specific order.
- [ ] Implement the cli tests for the import (and implement the mocks)
- [ ] Implement the server tests for the import (and implement the mocks)
- [ ] Publish the new repo with the integration tests
- [ ] Remove the integration test from this repo after the previous point was done

### CODE REVIEW

**Comment by SchoolGuy** [comment]
Force push for rebase onto master.

**Comment by SchoolGuy** [comment]
I decided to do the following things:

1. Remove the `misc` directory
2. Remove the tests under the `import` directory (and remove the dir itself)

Why did I decide to take these steps?

1. These scripts were not used by anything in the project and it was never touched after the initial commit except from my auto pep reformat. Since unused code is just not needed I deleted it.
2. The tests would require me to download all the distro iso's and then let the tests run. To save bandwidth and time I decided to remove them from this repository.

Next steps: I think it is reasonable to have an integration testsuite which does what the import tests were doing in the past. But these tests are out of the scope of this repository. I will bring them back in a separate repository which I will set up to run monthly and on demand inside travis.

Before I will bring back these tests I will mock the implementation of the actual import and test if the cli does it's job and is sending the correct command to the server. I will also create tests for the server part and mock the calls to the file system to see if the import actually works. The mocked tests are faster on can then be run on every PR and commit, meaning they are in the scope of this repository.

**Comment by SchoolGuy** [comment]
Before starting to implement the replacement tests I will implement the currently not implemented tests.

**Comment by SchoolGuy** [comment]
TODO-Checklist:

- [ ] Implement the tests which are currently raising a not implemented exception
- [ ] Cut through the tests which are glued together in a specific order.
- [ ] Implement the cli tests for the import (and implement the mocks)
- [ ] Implement the server tests for the import (and implement the mocks)
- [ ] Publish the new repo with the integration tests

**Comment by SchoolGuy** [comment]
Rebase onto master

**Comment by SchoolGuy** [comment]
Forcepush to get rid of conflict

**Comment by SchoolGuy** [comment]
I disabled the Codacy Linting for the test directory to skip all that unuseful warnings for the directory. We want our code analyzed not our tests.

**Comment by SchoolGuy** [comment]
Rebase & Force push after the big docs PR.

**Comment by SchoolGuy** [comment]
Reminder: Add dependency `hardlink` to the docs.

**Comment by SchoolGuy** [comment]
Reminder: Package and add https://github.com/pykickstart/pykickstart to the dependencies of Cobbler

**Comment by hbokh** [comment]
@SchoolGuy Just to be sure: do you want / need ALL the currently failing tests (see screenshot) to succeed? Because if so, I don't even know where to begin...

Screenshot 2020-05-12 at 17 31 36

**Comment by SchoolGuy** [comment]
@hbokh I need to commit my work of today, there are currently 30 tests failing. And don't worry, there is no need to fix the tests yourself. I just want that you review my changes (when it is not WIP anymore).

**Comment by SchoolGuy** [comment]
After looking at the current state of this PR and what I already have achieved, I think that it would be more reasonable to abandon the last four points of my TODO list for now. We will definitly need them in the future due to the complex concepts Cobbler is using but now this would hinder only the progress.

This PR will be ready when Travis is has a green checkmark and the histroy of this PR is cleaned up by me.

**Comment by SchoolGuy** [comment]
*sigh* Locally I only have 29 failures... So CI behaves differently. But I will look at then when I have fixed everything locally.

**Comment by SchoolGuy** [comment]
Rebase onto master

**Comment by hbokh** [comment]
I was just going to build & test `make test-debian10` because the RPM based failed on the `empty-file.txt` 😀. Now I see you (@SchoolGuy) removed it.

Only 2 failures left in Debian 10:

make test-debian10_2020-05-14 at 09 45 18

**Comment by SchoolGuy** [comment]
@hbokh Yeah apparently Travis had yesterday evening hickups and decided to require that file... Anyway now it seems to work.

**Comment by SchoolGuy** [comment]
What tests are Failing? Travis is green?!

**Comment by hbokh** [comment]
> What tests are Failing? Travis is green?!

Because Travis is not running the test(s) in the package build(s). Only make RPMs and a DEB.

**Comment by hbokh** [comment]
After your last commit 7a002da I ran `make test-centos7` again.
Only 1 test failure:

Make-test-centos7_2020-05-14 at 10 05 43

`== 1 failed, 205 passed, 4 skipped, 1 warning in 60.87s (0:01:00) ==`

Seems easy to fix:

```
E           xmlrpc.client.Fault: <Fault 1: "<class 'cobbler.cexceptions.CX'>:'power management type must be one of: amt_ws,apc,apc_snmp,bladecenter,brocade,cisco_mds,cisco_ucs,compute,drac5,eaton_snmp,emerson,eps,evacuate,heuristics_ping,hpblade,ibmblade,idrac,ifmib,ilo,ilo2,ilo3,ilo3_ssh,ilo4,ilo4_ssh,ilo5,ilo5_ssh,ilo_moonshot,ilo_mp,ilo_ssh,imm,intelmodular,ipdu,ipmilan,ipmitool,kdump,mpath,redfish,rhevm,rsa,rsb,sbd,scsi,virt,vmware_rest,vmware_soap,wti,xvm'">
```

**Comment by SchoolGuy** [comment]
@hbokh Which one is that?

**Comment by SchoolGuy** [comment]
@hbokh Will force push now my clean histroy.

**Comment by hbokh** [comment]
> @hbokh Which one is that?

Must be in `tests/xmlrpcapi/distro_profile_system_test.py`.

```
$ ag power tests/xmlrpcapi/distro_profile_system_test.py
153:        # power management
154:        ["power_type", ["lpar"], ["bla"]],
155:        ["power_address", ["127.0.0.1"], []],
156:        ["power_id", ["pmachine:lpar1"], []],
157:        ["power_pass", ["pass"], []],
158:        ["power_user", ["user"], []]
```

`Failed: good field (power_type=lpar) raised exception:`

**Comment by SchoolGuy** [comment]
@hbokh Could it be that the fence agents on CentOS7 don't have an lpar fence?

**Comment by SchoolGuy** [comment]
Because then that error is a correct and expected.

**Comment by hbokh** [comment]
Change `lpar` to `ipmitool`, which is quiet common and all test will pass. 🥳

```diff
diff --git a/tests/xmlrpcapi/distro_profile_system_test.py b/tests/xmlrpcapi/distro_profile_system_test.py
index c608251e..0f689517 100644
--- a/tests/xmlrpcapi/distro_profile_system_test.py
+++ b/tests/xmlrpcapi/distro_profile_system_test.py
@@ -151,7 +151,7 @@ def system_fields(redhat_autoinstall, suse_autoyast, ubuntu_preseed):
         ["virt_bridge-eth0", [], []],

         # power management
-        ["power_type", ["lpar"], ["bla"]],
+        ["power_type", ["ipmitool"], ["bla"]],
         ["power_address", ["127.0.0.1"], []],
         ["power_id", ["pmachine:lpar1"], []],
         ["power_pass", ["pass"], []],
```

Run `make test-centos7` locally:

Screenshot 2020-05-14 at 10 23 23

**Comment by SchoolGuy** [comment]
@hbokh Happy reviewing. Change is done!

**Comment by SchoolGuy** [comment]
@Conan-Kudo @brejoc @watologo1 Would you review too so we get at least two approvals.

**Comment by hbokh** [comment]
Running `make test-debian10, only one failure left:

```
============================================================== test session starts ==============================================================
platform linux -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
rootdir: /usr/src/cobbler, inifile:
plugins: cov-2.8.1
collected 210 items

tests/cli/cobbler_cli_direct_test.py ..........s...Fs.                                                                                    [  8%]
tests/cli/cobbler_cli_object_test.py .................................................................                                    [ 39%]
tests/modules/authentication/configfile_test.py .....                                                                                     [ 41%]
tests/xmlrpcapi/background_test.py ........                                                                                               [ 45%]
tests/xmlrpcapi/distro_profile_system_test.py ....................................                                                        [ 62%]
tests/xmlrpcapi/file_test.py .......                                                                                                      [ 65%]
tests/xmlrpcapi/image_test.py .......                                                                                                     [ 69%]
tests/xmlrpcapi/mgmt_class_test.py .......                                                                                                [ 72%]
tests/xmlrpcapi/miscellaneous_test.py ....s........s.............                                                                         [ 85%]
tests/xmlrpcapi/non_object_calls_test.py .................                                                                                [ 93%]
tests/xmlrpcapi/package_test.py .......                                                                                                   [ 96%]
tests/xmlrpcapi/repo_test.py .......                                                                                                      [100%]

=================================================================== FAILURES ====================================================================
________________________________________________ TestCobblerCliTestDirect.test_cobbler_hardlink _________________________________________________

self = <tests.cli.cobbler_cli_direct_test.TestCobblerCliTestDirect object at 0x7fd225c06080>
run_cmd = <function run_cmd.<locals>._run_cmd at 0x7fd225b2a400>
get_last_line = <function get_last_line.<locals>._get_last_line at 0x7fd225b8ef28>

    def test_cobbler_hardlink(self, run_cmd, get_last_line):
        (outputstd, outputerr) = run_cmd(cmd=["hardlink"])
        lines = outputstd.split("\n")
>       assert "*** TASK COMPLETE ***" == get_last_line(lines)
E       AssertionError: assert '*** TASK COMPLETE ***' == '!!! TASK FAILED !!!'
E         - *** TASK COMPLETE ***
E         + !!! TASK FAILED !!!

tests/cli/cobbler_cli_direct_test.py:159: AssertionError
```

First guess: the `hardlink` command is missing.

**Comment by SchoolGuy** [comment]
@hbokh Also done.

**Comment by hbokh** [comment]
Running `make test-debian10` now also passes! 👍🏻

Screenshot 2020-05-14 at 10 41 29

**Comment by hbokh** [comment]
@SchoolGuy The tests in Travis run in `opensuse/leap:15.2`.
Makes me wonder why there is no `make test-opensuse` or Dockerfile for that very specific distro.

**Comment by SchoolGuy** [comment]
@hbokh Yes but let's not bloat up this PR even more would be my suggestion. Or would you include that also here?

**Comment by hbokh** [comment]
> @hbokh Yes but let's not bloat up this PR even more would be my suggestion. Or would you include that also here?

No, make that a separate PR.

**Comment by brejoc** [comment]
@SchoolGuy I've just pushed a small fix for Fedora 31 Dockerfile. `pip3` was missing there.

**Comment by SchoolGuy** [comment]
We have two approvals. When the CI is green again let's get this into master!

**Comment by watologo1** [comment]
I also went through, at least the non /test files... Quite some important fixes and cleanups included, I couldn't find anything wrong.
Thumbs up here.
I let my devel_build OBS cobbler package point to your openSUSE:
openSUSE:enable-disabled-tests
branch and from what I can see it ran through with mainline spec and rpmlint file without any errors. Well done!
https://build.opensuse.org/package/live_build_log/home:trenn:cobbler_devel_build/cobbler/openSUSE_Tumbleweed/x86_64

**Pull request merged**
