### PR TITLE
Add EFI chainloader for SLE-Micro

### PR DESCRIPTION
**Pull request by beninidavide**
## Linked Items

Fixes #

 

## Description

Add support of SLE-Micro to the chainload file

## Behaviour changes

Old: a node booting PXE with SLE-Micro was unable to boot correctly

New: a node booting PXE with SLE-Micro can boot correctly

## Category

This is related to a:

- [X] Bugfix
- [ ] Feature
- [ ] Packaging
- [ ] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [ ] No tests required

### CODE REVIEW

**Comment by SchoolGuy** [comment]
Please also take a look at the similar approach taken in https://github.com/cobbler/cobbler/pull/3488. Back then I already had some suggestions. I think merging the two PRs would be appropriate but having two PRs for the same issue is kinda funky.

**Review by SchoolGuy — APPROVED** [review]
Thanks for this addition! I believe - without having tried it - that this is working as intended.

**Comment by SchoolGuy** [comment]
@beninidavide It would be nice if you could add a changelog fragment that states what you enabled. I would be `title.added` with a short oneliner that explains the change.

**Comment by beninidavide** [comment]
> @beninidavide It would be nice if you could add a changelog fragment that states what you enabled. I would be `title.added` with a short oneliner that explains the change.

just added changelog.d/3675.added, thank you!

**Comment by SchoolGuy** [comment]
@beninidavide I just saw that your commits are not signed. Is that something that you have set up?

**Comment by beninidavide** [comment]
> @beninidavide I just saw that your commits are not signed. Is that something that you have set up?

eh eh nope, I'm fixing it :)

**Comment by beninidavide** [comment]
> > @beninidavide I just saw that your commits are not signed. Is that something that you have set up?
> 
> eh eh nope, I'm fixing it :)

just fixed I think

**Pull request merged**
