### PR TITLE
Run black with --diff

### PR DESCRIPTION
**Pull request by opoplawski**
## Description

Hard to see what changes are needed for black.

## Behaviour changes

Old: CI would just say that a file would be reformatted

New: CI should show the changes needed

## Category

This is related to a:

- [ ] Bugfix
- [ ] Feature
- [ ] Packaging
- [ ] Docs
- [X] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [X] No tests required

### CODE REVIEW

**Review by SchoolGuy — APPROVED** [review]

**Comment by SchoolGuy** [comment]
The CI error in the basic system test are a mystery to me. Let's get this PR in.

**Comment by opoplawski** [comment]
I think the commits are signed now.

**Comment by opoplawski** [comment]
> The CI error in the basic system test are a mystery to me. Let's get this PR in.

```
2023-11-12 23:30:59.108Z error [CodacyCoverageReporter] Invalid configuration: Either a project or account API token must be provided or available in an environment variable  - (CodacyCoverageReporter.scala:25)
```
A problem with the codacy token?

**Comment by SchoolGuy** [comment]
@opoplawski No for that part we even have an issue already. I mean the Integration tests.

**Pull request merged**
