### PR TITLE
Backport AlmaLinux/Rocky Linux support

### PR DESCRIPTION
**Pull request by sbluhm**

### CODE REVIEW

**Comment by SchoolGuy** [comment]
Let's see what the CI says...

**Review by nodeg — APPROVED** [review]
LGTM. The CI ist fine and the changes are the same as in master.

**Review by SchoolGuy — APPROVED** [review]
LGTM

**Comment by sbluhm** [comment]
@SchoolGuy , can you please create a release or let me know when the next release is planned? I am trying to get this change into one of the known repos.

**Comment by SchoolGuy** [comment]
@sbluhm The next release will be 3.3.0 and is planned to be released a month ago. We are currently working on stabilizing the `master` branch which takes longer then expected. I will do my best but there is no exact estimate yet when this will arrive. The Orthos Team at SUSE is heavily included in these efforts as well.

**Comment by sbluhm** [comment]
@SchoolGuy , thank you, I actually meant 3.2.2 with this PR/commit. Or will there not be a release?

**Comment by SchoolGuy** [comment]
@sbluhm Upstream I can only support one version at a time. So there won't be a new release 3.2.2.

**Pull request merged**
