### PR TITLE
remove leading '/' from joinpath function call

### PR DESCRIPTION
**Pull request by ricortiz**
Addresses https://github.com/cobbler/cobbler/issues/3081

### CODE REVIEW

**Review by SchoolGuy — APPROVED** [review]
LGTM. Thanks for not only reporting but also fixing the issue!

**Comment by SchoolGuy** [comment]
The Unit Tests are broken on Tumbleweed. But the system-tests are passing, so this can be merged.

**Comment by SchoolGuy** [comment]
@ricortiz Are you able to sign your commit with GPG? If not its not a problem but if it is I would love to have the commit signed. :)

**Comment by ricortiz** [comment]
@SchoolGuy Is there anything else you need from me to merge this PR?

**Comment by SchoolGuy** [comment]
@ricortiz Sorry I lost track of this one. I will wait for CI and then if nothing pops up we can merge this one.

**Pull request merged**
