### PR TITLE
Update utils.py to include Rocky Linux

### PR DESCRIPTION
**Pull request by hveini**
Please add "rocky linux" into get_family() and os_release() as Centos replacement.

### CODE REVIEW

**Comment by nodeg** [comment]
Hi @hveini, thank you for your contribution.
I think to support Rocky Linux there has to be done more than just the changes in `utils.py`. I did one more necessary change in [distro_signatures.json](https://github.com/cobbler/cobbler/blob/13a5191be447b159d66dc46e6a1233a08e9e0e21/config/cobbler/distro_signatures.json#L127)
```diff
diff --git a/config/cobbler/distro_signatures.json b/config/cobbler/distro_signatures.json
index 561b8db2..751df3f4 100644
--- a/config/cobbler/distro_signatures.json
+++ b/config/cobbler/distro_signatures.json
@@ -124,7 +124,7 @@
         "signatures": [
           "BaseOS"
         ],
-        "version_file": "(redhat|sl|slf|almalinux|centos|centos-linux|centos-stream|oraclelinux|vzlinux)-release-(?!notes)([\\w]*-)*8[\\.-]+(.*)\\.rpm",
+        "version_file": "(redhat|sl|slf|almalinux|centos|centos-linux|centos-stream|oraclelinux|rockylinux|vzlinux)-release-(?!notes)([\\w]*-)*8[\\.-]+(.*)\\.rpm",

```
and then tried importing the [DVD](https://download.rockylinux.org/pub/rocky/8.3/isos/x86_64/Rocky-8.3-x86_64-boot.iso) (`Rocky-8.3-x86_64-dvd1.iso`) but the task failed.

```bash
$ mount -t iso9660 -o loop,ro /home/dom/host_isos/Rocky-8.3-x86_64-dvd1.iso /mnt2

$ ll /mnt2
total 30
dr-xr-xr-x 4 root root  2048 May  1 07:49 AppStream
dr-xr-xr-x 4 root root  2048 May  1 07:49 BaseOS
dr-xr-xr-x 3 root root  2048 May  1 07:49 EFI
dr-xr-xr-x 3 root root  2048 May  1 07:49 images
dr-xr-xr-x 2 root root  2048 May  1 07:49 isolinux
-r--r--r-- 1 root root 18092 Apr 29 04:58 LICENSE
-r--r--r-- 1 root root    86 May  1 07:45 media.repo
-r--r--r-- 1 root root   883 May  1 07:49 TRANS.TBL

$ cobbler import --name=rockylinux --arch=x86_64 --path=/mnt2
task started: 2021-05-07_132141_import
task started (id=Media import, time=Fri May  7 13:21:41 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
import_tree; ['/mnt2', 'rockylinux', None, None, None]
importing from a network location, running rsync to fetch the files first
mkdir: /srv/www/cobbler/distro_mirror/rockylinux-x86_64
running: rsync -a  '/mnt2/' /srv/www/cobbler/distro_mirror/rockylinux-x86_64 --progress
received on stdout: sending incremental file list
received on stderr: 
Found a candidate signature: breed=redhat, version=rhel8
Found a candidate signature: breed=suse, version=opensuse15generic
Found a candidate signature: breed=suse, version=sles15generic
Exception occurred: <class 'KeyError'>
Exception value: 'signatures'
Exception Info:
!!! TASK FAILED !!!
```
Our algorithm for importing signatures has to be improved to be able to support more distros and to support more installation medias like boot or live CDs/DVDs (#2623). Feel free to dig deeper and improve this.

**Comment by SchoolGuy** [comment]
@hveini Depending on how deep you want to dig, take a look at our signatures management library at https://github.com/cobbler/libcobblersignatures

**Comment by hveini** [comment]
Hi @nodeg, sorry for not being so clear. My three line change, was to make Cobbler run on top of Rocky Linux. 
e.g, installing and running 3.2 from epel (demoved the outputs of dnf-commands):
```
[root@localhost cobbler]# cat /etc/redhat-release 
Rocky Linux release 8.3
[root@localhost cobbler]# cat /etc/os-release 
NAME="Rocky Linux"
VERSION="8.3"
ID="rocky"
ID_LIKE="rhel fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.3"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:rocky:rocky:8"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
[root@localhost cobbler]# dnf install epel-release
[root@localhost cobbler]# dnf module enable cobbler
[root@localhost cobbler]# dnf install cobbler
[root@localhost cobbler]# dnf remove python3-django3
[root@localhost cobbler]# dnf install cobbler-web
[root@localhost cobbler]# systemctl enable cobblerd --now
Created symlink /etc/systemd/system/multi-user.target.wants/cobblerd.service → /usr/lib/systemd/system/cobblerd.service.
[root@localhost cobbler]# systemctl status cobblerd
● cobblerd.service - Cobbler Helper Daemon
   Loaded: loaded (/usr/lib/systemd/system/cobblerd.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Sat 2021-05-08 09:19:44 EDT; 9s ago
  Process: 50774 ExecStartPost=/usr/bin/touch /usr/share/cobbler/web/cobbler.wsgi (code=exited, status=0/SUCCESS)
  Process: 50773 ExecStart=/usr/bin/cobblerd -F (code=exited, status=0/SUCCESS)
 Main PID: 50773 (code=exited, status=0/SUCCESS)

May 08 09:19:44 localhost.localdomain systemd[1]: Starting Cobbler Helper Daemon...
May 08 09:19:44 localhost.localdomain systemd[1]: Started Cobbler Helper Daemon.
May 08 09:19:44 localhost.localdomain cobblerd[50773]: Traceback (most recent call last):
May 08 09:19:44 localhost.localdomain cobblerd[50773]:   File "/usr/bin/cobblerd", line 75, in main
May 08 09:19:44 localhost.localdomain cobblerd[50773]:     api = cobbler_api.CobblerAPI(is_cobblerd=True)
May 08 09:19:44 localhost.localdomain cobblerd[50773]:   File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 98, in __init__
May 08 09:19:44 localhost.localdomain cobblerd[50773]:     self.dist, self.os_version = utils.os_release()
May 08 09:19:44 localhost.localdomain cobblerd[50773]: TypeError: 'NoneType' object is not iterable
May 08 09:19:44 localhost.localdomain systemd[1]: cobblerd.service: Succeeded.
[root@localhost cobbler]# cp /usr/lib/python3.6/site-packages/cobbler/utils.py /usr/lib/python3.6/site-packages/cobbler/utils.py_orig
[root@localhost cobbler]# nano /usr/lib/python3.6/site-packages/cobbler/utils.py
[root@localhost cobbler]# diff /usr/lib/python3.6/site-packages/cobbler/utils.py /usr/lib/python3.6/site-packages/cobbler/utils.py_orig
1014c1014
<     redhat_list = ("red hat", "redhat", "scientific linux", "fedora", "centos", "virtuozzo", "rocky linux")
---
>     redhat_list = ("red hat", "redhat", "scientific linux", "fedora", "centos", "virtuozzo")
1043,1044d1042
<         elif "rocky linux" in distro_name:
<             make = "centos"
[root@localhost cobbler]# systemctl restart cobblerd
[root@localhost cobbler]# systemctl status cobblerd
● cobblerd.service - Cobbler Helper Daemon
   Loaded: loaded (/usr/lib/systemd/system/cobblerd.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2021-05-08 09:22:03 EDT; 2s ago
  Process: 50797 ExecStartPost=/usr/bin/touch /usr/share/cobbler/web/cobbler.wsgi (code=exited, status=0/SUCCESS)
 Main PID: 50796 (cobblerd)
    Tasks: 1 (limit: 11389)
   Memory: 30.5M
   CGroup: /system.slice/cobblerd.service
           └─50796 /usr/bin/python3.6 -s /usr/bin/cobblerd -F

May 08 09:22:03 localhost.localdomain systemd[1]: Starting Cobbler Helper Daemon...
May 08 09:22:03 localhost.localdomain systemd[1]: Started Cobbler Helper Daemon.
[root@localhost cobbler]# 
```

I also took a look in distro_signatures.json, this also in Rocky Linux, with modified 3.2 install:

```
[root@localhost cobbler]# cobbler import --name=rockylinux --arch=x86_64 --path=/mnt2
task started: 2021-05-08_092929_import
task started (id=Media import, time=Sat May  8 09:29:29 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Found a candidate signature: breed=redhat, version=rhel8
Found a candidate signature: breed=suse, version=opensuse15generic
Found a candidate signature: breed=suse, version=sles15generic
Exception occured: <class 'KeyError'>
Exception value: 'signatures'
Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 98, in run
    rc = self._run(self)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 305, in runner
    self.logger

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1489, in import_tree
    import_module.run(path, mirror_name, network_root, autoinstall_file, arch, breed, os_version)

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/import_signatures.py", line 182, in run
    self.signature = self.scan_signatures()

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/import_signatures.py", line 215, in scan_signatures
    for sig in sigdata["breeds"][breed][version]["signatures"]:

!!! TASK FAILED !!!
[root@localhost cobbler]# grep rocky /mnt2/BaseOS/repodata/repomd.xml 
    <distro cpeid="cpe:/o:rocky:rocky:8">Rocky Linux 8</distro>
[root@localhost cobbler]# nano /var/lib/cobbler/distro_signatures.json               
[root@localhost cobbler]# grep rocky /var/lib/cobbler/distro_signatures.json 
        "version_file": "(redhat|sl|slf|almalinux|centos|centos-linux|centos-stream|oraclelinux|rocky|vzlinux)-release-(?!notes)([\\w]*-)*8[\\.-]+(.*)\\.rpm",
[root@localhost cobbler]# systemctl restart cobblerd
[root@localhost cobbler]# cobbler import --name=rockylinux --arch=x86_64 --path=/mnt2
task started: 2021-05-08_093244_import
task started (id=Media import, time=Sat May  8 09:32:44 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Found a candidate signature: breed=redhat, version=rhel8
Found a matching signature: breed=redhat, version=rhel8
Adding distros from path /var/www/cobbler/distro_mirror/rockylinux-x86_64:
creating new distro: rockylinux-x86_64
trying symlink: /var/www/cobbler/distro_mirror/rockylinux-x86_64 -> /var/www/cobbler/links/rockylinux-x86_64
creating new profile: rockylinux-x86_64
associating repos
checking for rsync repo(s)
checking for rhn repo(s)
checking for yum repo(s)
starting descent into /var/www/cobbler/distro_mirror/rockylinux-x86_64 for rockylinux-x86_64
processing repo at : /var/www/cobbler/distro_mirror/rockylinux-x86_64/AppStream
need to process repo/comps: /var/www/cobbler/distro_mirror/rockylinux-x86_64/AppStream
looking for /var/www/cobbler/distro_mirror/rockylinux-x86_64/AppStream/repodata/*comps*.xml
Keeping repodata as-is :/var/www/cobbler/distro_mirror/rockylinux-x86_64/AppStream/repodata
processing repo at : /var/www/cobbler/distro_mirror/rockylinux-x86_64/BaseOS
need to process repo/comps: /var/www/cobbler/distro_mirror/rockylinux-x86_64/BaseOS
looking for /var/www/cobbler/distro_mirror/rockylinux-x86_64/BaseOS/repodata/*comps*.xml
Keeping repodata as-is :/var/www/cobbler/distro_mirror/rockylinux-x86_64/BaseOS/repodata
*** TASK COMPLETE ***
[root@localhost cobbler]#

```

So, using just "rocky" in distro_signatures.json seems to do the trick.

**Comment by nodeg** [comment]
Thanks for the clarification and the heads up on using just the name `rocky.` in `distro_signatures.json`. I was able to successfully import Rocky Linux on the master branch, too:

```bash
$ cobbler import --name=RockyLinux --path=/mnt2
task started: 2021-05-10_100655_import
task started (id=Media import, time=Mon May 10 10:06:55 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
import_tree; ['/mnt2', 'RockyLinux', None, None, None]
importing from a network location, running rsync to fetch the files first
mkdir: /srv/www/cobbler/distro_mirror/RockyLinux
running: rsync -a  '/mnt2/' /srv/www/cobbler/distro_mirror/RockyLinux --progress
received on stdout: sending incremental file list
received on stderr: 
Found a candidate signature: breed=redhat, version=rhel8
Found a matching signature: breed=redhat, version=rhel8
Adding distros from path /srv/www/cobbler/distro_mirror/RockyLinux:
creating new distro: RockyLinux-x86_64
trying symlink: /srv/www/cobbler/distro_mirror/RockyLinux -> /srv/www/cobbler/links/RockyLinux-x86_64
running python triggers from /var/lib/cobbler/triggers/add/distro/pre/*
running shell triggers from /var/lib/cobbler/triggers/add/distro/pre/*
shell triggers finished successfully
mkdir: /srv/www/cobbler/images/RockyLinux-x86_64
trying hardlink /srv/www/cobbler/distro_mirror/RockyLinux/images/pxeboot/vmlinuz -> /srv/www/cobbler/images/RockyLinux-x86_64/vmlinuz
trying hardlink /srv/www/cobbler/distro_mirror/RockyLinux/images/pxeboot/initrd.img -> /srv/www/cobbler/images/RockyLinux-x86_64/initrd.img
mkdir: /srv/tftpboot/images/RockyLinux-x86_64
trying hardlink /srv/www/cobbler/distro_mirror/RockyLinux/images/pxeboot/vmlinuz -> /srv/tftpboot/images/RockyLinux-x86_64/vmlinuz
trying hardlink /srv/www/cobbler/distro_mirror/RockyLinux/images/pxeboot/initrd.img -> /srv/tftpboot/images/RockyLinux-x86_64/initrd.img
processing boot_files for distro: RockyLinux-x86_64
skipping symlink, destination (/srv/www/cobbler/links/RockyLinux-x86_64) exists
Writing template files for RockyLinux-x86_64
mkdir: /srv/tftpboot/pxelinux.cfg
running python triggers from /var/lib/cobbler/triggers/change/*
running python trigger cobbler.modules.scm_track
running python trigger cobbler.modules.managers.genders
running shell triggers from /var/lib/cobbler/triggers/change/*
shell triggers finished successfully
running python triggers from /var/lib/cobbler/triggers/add/distro/post/*
running shell triggers from /var/lib/cobbler/triggers/add/distro/post/*
shell triggers finished successfully
creating new profile: RockyLinux-x86_64
running python triggers from /var/lib/cobbler/triggers/add/profile/pre/*
running shell triggers from /var/lib/cobbler/triggers/add/profile/pre/*
shell triggers finished successfully
Writing template files for RockyLinux-x86_64
mkdir: /srv/tftpboot/pxelinux.cfg
running python triggers from /var/lib/cobbler/triggers/change/*
running python trigger cobbler.modules.scm_track
running python trigger cobbler.modules.managers.genders
running shell triggers from /var/lib/cobbler/triggers/change/*
shell triggers finished successfully
running python triggers from /var/lib/cobbler/triggers/add/profile/post/*
running shell triggers from /var/lib/cobbler/triggers/add/profile/post/*
shell triggers finished successfully
associating repos
checking for rsync repo(s)
mkdir: /srv/www/cobbler/images/RockyLinux-x86_64
mkdir: /srv/tftpboot/images/RockyLinux-x86_64
processing boot_files for distro: RockyLinux-x86_64
skipping symlink, destination (/srv/www/cobbler/links/RockyLinux-x86_64) exists
Writing template files for RockyLinux-x86_64
Writing template files for RockyLinux-x86_64
mkdir: /srv/tftpboot/pxelinux.cfg
checking for rhn repo(s)
mkdir: /srv/www/cobbler/images/RockyLinux-x86_64
mkdir: /srv/tftpboot/images/RockyLinux-x86_64
processing boot_files for distro: RockyLinux-x86_64
skipping symlink, destination (/srv/www/cobbler/links/RockyLinux-x86_64) exists
Writing template files for RockyLinux-x86_64
Writing template files for RockyLinux-x86_64
mkdir: /srv/tftpboot/pxelinux.cfg
checking for yum repo(s)
starting descent into /srv/www/cobbler/distro_mirror/RockyLinux for RockyLinux-x86_64
processing repo at : /srv/www/cobbler/distro_mirror/RockyLinux/AppStream
need to process repo/comps: /srv/www/cobbler/distro_mirror/RockyLinux/AppStream
looking for /srv/www/cobbler/distro_mirror/RockyLinux/AppStream/repodata/*comps*.xml
Keeping repodata as-is :/srv/www/cobbler/distro_mirror/RockyLinux/AppStream/repodata
processing repo at : /srv/www/cobbler/distro_mirror/RockyLinux/BaseOS
need to process repo/comps: /srv/www/cobbler/distro_mirror/RockyLinux/BaseOS
looking for /srv/www/cobbler/distro_mirror/RockyLinux/BaseOS/repodata/*comps*.xml
Keeping repodata as-is :/srv/www/cobbler/distro_mirror/RockyLinux/BaseOS/repodata
mkdir: /srv/www/cobbler/images/RockyLinux-x86_64
mkdir: /srv/tftpboot/images/RockyLinux-x86_64
processing boot_files for distro: RockyLinux-x86_64
skipping symlink, destination (/srv/www/cobbler/links/RockyLinux-x86_64) exists
Writing template files for RockyLinux-x86_64
Writing template files for RockyLinux-x86_64
mkdir: /srv/tftpboot/pxelinux.cfg
*** TASK COMPLETE ***


$ cobbler distro report
Name                           : RockyLinux-x86_64
Architecture                   : x86_64
Automatic Installation Template Metadata : {'tree': 'http://@@http_server@@/cblr/links/RockyLinux-x86_64'}
TFTP Boot Files                : {}
Boot loader                    : grub
Breed                          : redhat
Comment                        : 
Fetchable Files                : {}
Initrd                         : /srv/www/cobbler/distro_mirror/RockyLinux/images/pxeboot/initrd.img
Kernel                         : /srv/www/cobbler/distro_mirror/RockyLinux/images/pxeboot/vmlinuz
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Management Classes             : []
OS Version                     : rhel8
Owners                         : ['admin']
Redhat Management Key          : 
Remote Boot Initrd             : ~
Remote Boot Kernel             : ~
Template Files                 : {}


$ tree -L 3 /srv/tftpboot/
/srv/tftpboot/
├── boot
├── etc
├── grub
│   ├── grub.cfg
│   ├── images -> ../images
│   ├── local_efi.cfg
│   ├── local_legacy.cfg
│   ├── local_powerpc-ieee1275.cfg
│   ├── system
│   ├── system_link
│   └── x86_64_menu_items.cfg
├── grub.cfg
├── images
│   └── RockyLinux-x86_64
│       ├── initrd.img
│       └── vmlinuz
├── images2
├── ppc
├── pxelinux.cfg
│   └── default
└── s390x

12 directories, 9 files
```

I do not have a VM with Rocky Linux ready to test running Cobbler there, so I rely on your testing here. I will push the correct changes for `distro_signatures.py`, rebase and then we wait for feedback from @SchoolGuy. After that this PR can be merged.

**Review by nodeg — APPROVED** [review]
LGTM.

**Review by SchoolGuy — APPROVED** [review]
LGTM

**Comment by InterceptorF** [comment]
So this thread got cobbler installed for me with a few extra caveats:  
I am running Rocky 8.4. I used a new VM. Cobbler import did not work the first time because selinux was active.  To get around that  I edited /etc/sysconfig/selinux and changed the line: SELINUX=disabled.
then ran command  setenforce 0 .
 Once selinux was disabled I ran command:
[root@localhost /]# cobbler import --name=rockylinux --path=/mnt2
task started: 2021-11-17_192450_import
task started (id=Media import, time=Wed Nov 17 19:24:50 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Found a candidate signature: breed=redhat, version=rhel8
Found a matching signature: breed=redhat, version=rhel8
Adding distros from path /var/www/cobbler/distro_mirror/rockylinux:
creating new distro: rockylinux-x86_64
trying symlink: /var/www/cobbler/distro_mirror/rockylinux -> /var/www/cobbler/links/rockylinux-x86_64
creating new profile: rockylinux-x86_64
associating repos
checking for rsync repo(s)
checking for rhn repo(s)
checking for yum repo(s)
starting descent into /var/www/cobbler/distro_mirror/rockylinux for rockylinux-x86_64
processing repo at : /var/www/cobbler/distro_mirror/rockylinux/AppStream
need to process repo/comps: /var/www/cobbler/distro_mirror/rockylinux/AppStream
looking for /var/www/cobbler/distro_mirror/rockylinux/AppStream/repodata/*comps*.xml
Keeping repodata as-is :/var/www/cobbler/distro_mirror/rockylinux/AppStream/repodata
processing repo at : /var/www/cobbler/distro_mirror/rockylinux/BaseOS
need to process repo/comps: /var/www/cobbler/distro_mirror/rockylinux/BaseOS
looking for /var/www/cobbler/distro_mirror/rockylinux/BaseOS/repodata/*comps*.xml
Keeping repodata as-is :/var/www/cobbler/distro_mirror/rockylinux/BaseOS/repodata
*** TASK COMPLETE ***




Then the distro report shows its available:
[root@localhost /]# cobbler distro report
Name                           : rockylinux-x86_64
Architecture                   : x86_64
Automatic Installation Template Metadata : {'tree': 'http://@@http_server@@/cblr/links/rockylinux-x86_64'}
TFTP Boot Files                : {}
Boot loader                    : grub
Breed                          : redhat
Comment                        : 
Fetchable Files                : {}
Initrd                         : /var/www/cobbler/distro_mirror/rockylinux/images/pxeboot/initrd.img
Kernel                         : /var/www/cobbler/distro_mirror/rockylinux/images/pxeboot/vmlinuz
Kernel Options                 : {}
Kernel Options (Post Install)  : {}
Management Classes             : []
OS Version                     : rhel8
Owners                         : ['admin']
Redhat Management Key          : 
Remote Boot Initrd             : ~
Remote Boot Kernel             : ~
Template Files                 : {}

What I have an issue with now is that tftp does not seem to be installed? so I'll be looking into that next. 
[root@localhost srv]# tree -L 3 /srv/tftpboot
/srv/tftpboot [error opening dir]

0 directories, 0 files
[root@localhost srv]# 

Hope this helps someone else ;)

**Pull request merged**
