### PR TITLE
Item Renaming: Remove the need to clone an object during the process

### LINKED ISSUE #2736: Renaming a system fails with 'IP address duplicated' error
### Describe the bug

With current master it's not possible to rename a system. The operation fails:

```
# cobbler system rename --name foo --newname bar
exception on server: IP address duplicated: 1.2.3.4
```

### Steps to reproduce

1. Create a system: `cobbler system add --name foo --profile baz --ip-address 1.2.3.4`
2. Try to rename the system: `cobbler system rename --name foo --newname bar`

### Expected behavior

It should be possible to rename a system.

### Cobbler version

````paste below
Cobbler 3.2.1
  source: ?, ?
  build time: Mon Jul 19 16:45:07 2021
````

### Operating system

CentOS 8

### Cobbler log

````paste below
[Thread-319] 2021-08-03T14:51:47 - INFO | Exception occurred: <class 'ValueError'>
[Thread-319] 2021-08-03T14:51:47 - INFO | Exception value: IP address duplicated: 1.2.3.4
[Thread-319] 2021-08-03T14:51:47 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 3514, in _dispatch
    return method_handle(*params)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 1898, in xapi_object_edit
    self.rename_item(object_type, handle, attributes["newname"], token)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 1449, in rename_item
    self.api.rename_item(what, obj, newname)

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 545, in rename_item
    self.get_items(what).rename(ref, newname)

  File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/collection.py", line 241, in rename
    newref = ref.make_clone()

  File "/usr/lib/python3.6/site-packages/cobbler/items/system.py", line 723, in make_clone
    cloned.from_dict(_dict)

  File "/usr/lib/python3.6/site-packages/cobbler/items/system.py", line 742, in from_dict
    super().from_dict(dictionary)

  File "/usr/lib/python3.6/site-packages/cobbler/items/item.py", line 752, in from_dict
    setattr(self, lowered_key, dictionary[key])

  File "/usr/lib/python3.6/site-packages/cobbler/items/system.py", line 830, in interfaces
    network_iface.from_dict(value[key])

  File "/usr/lib/python3.6/site-packages/cobbler/items/system.py", line 73, in from_dict
    setattr(self, key, dictionary[key])

  File "/usr/lib/python3.6/site-packages/cobbler/items/system.py", line 239, in ip_address
    raise ValueError("IP address duplicated: %s" % address)
````

### PR DESCRIPTION
**Pull request by SchoolGuy**
Fixes #2736 

@heroin-moose pls validate if this works for you

This removes the process of creating a cloned object during an item rename process, as well as fixes the problem that during a rename you get the error message "IP Address duplicated". This means that the UID of the object is preserved but all filesystem references are renamed.

### CODE REVIEW

**Comment by heroin-moose** [comment]
I get the following error while trying to create a system:

```
Traceback (most recent call last):
  File "/usr/bin/cobbler", line 35, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 1336, in main
    rc = cli.run(sys.argv)
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 888, in run
    self.object_command(object_type, object_action)
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 972, in object_command
    network_interface_fields, settings, object_action)
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 720, in add_options_from_fields
    _add_parser_option_from_field(parser, field, settings)
  File "/usr/lib/python3.6/site-packages/cobbler/cli.py", line 691, in _add_parser_option_from_field
    raise Exception("field %s default value (%s) is not listed in choices (%s)" % (name, default, str(choices)))
Exception: field power_type default value (ipmilanplus) is not listed in choices (['amt_ws', 'apc', 'apc_snmp', 'bladecenter', 'brocade', 'cisco_mds', 'cisco_ucs', 'compute', 'drac5', 'eaton_snmp', 'emerson', 'eps', 'evacuate', 'heuristics_ping', 'hpblade', 'ibmblade', 'idrac', 'ifmib', 'ilo', 'ilo2', 'ilo3', 'ilo3_ssh', 'ilo4', 'ilo4_ssh', 'ilo5', 'ilo5_ssh', 'ilo_moonshot', 'ilo_mp', 'ilo_ssh', 'imm', 'intelmodular', 'ipdu', 'ipmilan', 'kdump', 'mpath', 'redfish', 'rhevm', 'rsa', 'rsb', 'sbd', 'scsi', 'virt', 'vmware_rest', 'vmware_soap', 'wti', 'xvm'])
```

**Comment by SchoolGuy** [comment]
@heroin-moose What version of `fence_agents` to you have installed?

**Comment by heroin-moose** [comment]
Aside from that renaming works but without manual sync oldname is still haunting us (e.g. `grub/system_link/oldname`).

**Comment by heroin-moose** [comment]
4.2.1. from centos8.

**Comment by SchoolGuy** [comment]
> 4.2.1. from centos8.

You need this PR included: https://github.com/ClusterLabs/fence-agents/pull/381 which means that you need at least [4.7.1](https://github.com/ClusterLabs/fence-agents/releases/tag/v4.7.1) or you need to change the fence you are using.

**Comment by SchoolGuy** [comment]
> Aside from that renaming works but without manual sync oldname is still haunting us (e.g. `grub/system_link/oldname`).

I'll put it in the list of things...

**Comment by heroin-moose** [comment]
> You need this PR included: ClusterLabs/fence-agents#381 which means that you need at least 4.7.1 or you need to change the fence you are using.

I'm using the default one. I dunno, perhaps CentOS spec file should add some override to /etc/cobbler/settings.d as currently the default Cobbler build is broken on CentOS 8 out of the box. Anyway, this is out of scope of this PR.

**Comment by heroin-moose** [comment]
> Aside from that renaming works but without manual sync oldname is still haunting us (e.g. grub/system_link/oldname).

To clarify things: there are two files: newname and oldname. So everything works, but leftovers are there.

**Review by nodeg — APPROVED** [review]
LGTM.

**Pull request merged**
