### PR TITLE
Use curl instead of the missing wget for the breed suse

### PR DESCRIPTION
**Pull request by bruncsak**
## Linked Items

Fixes https://github.com/cobbler/cobbler/issues/3611

 

## Description

It checks for the breed `suse`, and if match, it creates code with `curl` instead of the default `wget`

## Behaviour changes

Old: on openSUSE tumbleweed got error message "wget: command not found".

New: no error message, trigger properly called

## Category

This is related to a:

- [x] Bugfix
- [ ] Feature
- [ ] Packaging
- [ ] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [x] No tests required

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@bruncsak Would you be able to add a newsfragment with the name `3611.fixed` and appropriate content?

**Comment by bruncsak** [comment]
@SchoolGuy, I think it is OK now.
newsfragement_checker is not failing any more.

**Review by SchoolGuy — APPROVED** [review]

**Comment by SchoolGuy** [comment]
@bruncsak The project normally desires that all commits are signed, as such I would appreciate it if you could so. If this is not possible I will of course still merge your PR.

**Comment by SchoolGuy** [comment]
@bruncsak Any update on your ability to sign commits?

**Comment by bruncsak** [comment]
Sorry, my repository is on CentOS 7. The version of git is not able to sign commits. I have a plan to upgrade to CentOS 9 Stream, but no deadline yet for that upgrade. Would you able to merge this commit without signature, exceptionally?

**Comment by SchoolGuy** [comment]
@bruncsak Yes of course. Thanks for the quick answer.

**Pull request merged**
