### PR TITLE
add regex for esxi kernel and initrd

### LINKED ISSUE #3069: Cannot import ESXI70 after fix commited
### Describe the bug

I have a lot of problems to import ESXI 7.0 (VMware-VMvisor-Installer-7.0.0-15843807.x86_64.iso) to *mnt/iso

### Steps to reproduce
I mount the image in /mnt/iso
1.Try import with all parameters availables 
`cobbler import --name=esxi70 --path=/mnt/iso --arch=x86_64 --breed=vmware --os-version=esxi70`
2. After that, we receive this error
```
[root@cobbler ~]# cobbler import --name=esxi70 --path=/mnt/iso --arch=x86_64 --breed=vmware --os-version=esxi70
task started: 2022-04-20_231133_import
task started (id=Media import, time=Wed Apr 20 23:11:33 2022)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
import_tree; ['/mnt/iso', 'esxi70', None, None, None]
importing from a network location, running rsync to fetch the files first
running: rsync -a  '/mnt/iso/' /var/www/cobbler/distro_mirror/esxi70-x86_64 --progress
received on stdout: sending incremental file list
received on stderr:
Found a candidate signature: breed=vmware, version=esxi70
Found a matching signature: breed=vmware, version=esxi70
Adding distros from path /var/www/cobbler/distro_mirror/esxi70-x86_64:
Could not detect the filetype and read the content of file "/var/www/cobbler/distro_mirror/esxi70-x86_64/tools.t00". Returning nothing.
creating new distro: esxi70-x86_64
Exception occurred: <class 'ValueError'>
Exception value: kernel not found: /var/www/cobbler/distro_mirror/esxi70-x86_64/mboot.c32
Exception Info:
!!! TASK FAILED !!!
```

### Cobbler version

```
[root@cobbler ~]# cobbler --version
Cobbler 3.4.0
  source: e03b1005, Tue Apr 12 09:13:22 2022 +0200
  build time: Wed Apr 13 09:18:48 2022
```

### Operating system
Centos 8

### Cobbler log

```
[Thread-291] 2022-04-20T23:11:33 - INFO | REMOTE start_task(Media import); event_id(2022-04-20_231133_import); user(?)
[2022-04-20_231133_import] 2022-04-20T23:11:34 - DEBUG | running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
[2022-04-20_231133_import] 2022-04-20T23:11:34 - DEBUG | running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
[2022-04-20_231133_import] 2022-04-20T23:11:34 - DEBUG | shell triggers finished successfully
[2022-04-20_231133_import] 2022-04-20T23:11:34 - INFO | import_tree; ['/mnt/iso', 'esxi70', None, None, None]
[2022-04-20_231133_import] 2022-04-20T23:11:34 - INFO | importing from a network location, running rsync to fetch the files first
[2022-04-20_231133_import] 2022-04-20T23:11:34 - INFO | running: rsync -a  '/mnt/iso/' /var/www/cobbler/distro_mirror/esxi70-x86_64 --progress
[2022-04-20_231133_import] 2022-04-20T23:11:34 - INFO | received on stdout: sending incremental file list

[2022-04-20_231133_import] 2022-04-20T23:11:34 - DEBUG | received on stderr:
[2022-04-20_231133_import] 2022-04-20T23:11:34 - DEBUG | Found a candidate signature: breed=vmware, version=esxi70
[2022-04-20_231133_import] 2022-04-20T23:11:34 - DEBUG | Found a matching signature: breed=vmware, version=esxi70
[2022-04-20_231133_import] 2022-04-20T23:11:34 - INFO | Adding distros from path /var/www/cobbler/distro_mirror/esxi70-x86_64:
[2022-04-20_231133_import] 2022-04-20T23:11:34 - INFO | Could not detect the filetype and read the content of file "/var/www/cobbler/distro_mirror/esxi70-x86_64/tools.t00". Returning nothing.
[2022-04-20_231133_import] 2022-04-20T23:11:34 - INFO | creating new distro: esxi70-x86_64
[2022-04-20_231133_import] 2022-04-20T23:11:34 - INFO | Exception occurred: <class 'ValueError'>
[2022-04-20_231133_import] 2022-04-20T23:11:34 - INFO | Exception value: kernel not found: /var/www/cobbler/distro_mirror/esxi70-x86_64/mboot.c32
[2022-04-20_231133_import] 2022-04-20T23:11:34 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 118, in run
    rc = self._run(self)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 347, in runner
    self.options.get("os_version", None),

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1886, in import_tree
    if not mirror_url.endswith("/"):

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/import_signatures.py", line 209, in run
    import_walker(self.path, self.distro_adder, distros_added)

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/import_signatures.py", line 87, in import_walker
    func(arg, top, names)

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/import_signatures.py", line 451, in distro_adder
    adtls.append(self.add_entry(dirname, kernel, initrd))

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/import_signatures.py", line 515, in add_entry
    new_distro.kernel = kernel

  File "/usr/lib/python3.6/site-packages/cobbler/items/distro.py", line 171, in kernel
    raise ValueError("kernel not found: %s" % kernel)

[2022-04-20_231133_import] 2022-04-20T23:11:34 - ERROR | ### TASK FAILED ###
```

### PR DESCRIPTION
**Pull request by javier-angulo**
Fixes #3069

### CODE REVIEW

**Review by SchoolGuy — CHANGES_REQUESTED** [review]
Could you please apply the black formatter to the file? Thanks a lot for the fix though!

**Comment by javier-angulo** [comment]
@SchoolGuy changed as requested (without much confidence though, as I had to use vscode instead of vi)

**Comment by SchoolGuy** [comment]
@javier-angulo Black is a cli tool. No need for vscode. But thanks a lot for going so far! :)

**Review by SchoolGuy — APPROVED** [review]
LGTM

**Pull request merged**
