### PR TITLE
Correct opensuse15.0 and Add opensuse15.1

### PR DESCRIPTION
**Pull request by xenlo**
- Correct signature and arch of OpenSuse Leap 15.0
- Add OpenSuse Leap 15.1

### CODE REVIEW

**Comment by xenlo** [comment]
Import tested with cobbler 2.8 with the following ISOs:
- ✔️ [openSUSE-Leap-15.0-DVD-x86_64](https://download.opensuse.org/distribution/leap/15.0/iso/openSUSE-Leap-15.0-DVD-x86_64.iso?mirrorlist)
```
cobbler import --name openSUSE_Leap-15.0-DVD --path /mnt/openSUSE-Leap-15.0-DVD-x86_64/ --arch x86_64
```
- ✔️ [openSUSE-Leap-15.1-DVD-x86_64](https://download.opensuse.org/distribution/leap/15.1/iso/openSUSE-Leap-15.1-DVD-x86_64.iso?mirrorlist)
```
cobbler import --name openSUSE_Leap-15.1-DVD --path /mnt/openSUSE-Leap-15.1-DVD-x86_64/ --arch x86_64
```
- ❌ [openSUSE-Leap-15.0-NET-x86_64](https://download.opensuse.org/distribution/leap/15.0/iso/openSUSE-Leap-15.0-NET-x86_64.iso?mirrorlist)
```
cobbler import --name openSUSE_Leap-15.0-NET --path /mnt/openSUSE-Leap-15.0-NET-x86_64/ --arch x86_64
```
- ✔️ [openSUSE-Leap-15.1-NET-x86_64](https://download.opensuse.org/distribution/leap/15.1/iso/openSUSE-Leap-15.1-NET-x86_64.iso?mirrorlist)
```
cobbler import --name openSUSE_Leap-15.1-NET --path /mnt/openSUSE-Leap-15.1-NET-x86_64/ --arch x86_64
```

The 15.0-NET fails because there is no release rpm package on the ISO. So for me, the issue is located on the ISO generation side.
```
root@cobbler-srv:/tmp# find /mnt/ -name "openSUSE-release-15*rpm"
/mnt/openSUSE-Leap-15.1-DVD-x86_64/x86_64/openSUSE-release-15.1-lp151.298.1.x86_64.rpm
/mnt/openSUSE-Leap-15.1-NET-x86_64/x86_64/openSUSE-release-15.1-lp151.298.1.x86_64.rpm
/mnt/openSUSE-Leap-15.0-DVD-x86_64/x86_64/openSUSE-release-15.0-lp150.129.1.x86_64.rpm
```

**Comment by xenlo** [comment]
It would be great to retro port those change for  previous release (we are using the 2.8 here).

To test the change, I substituted the `"default_autoinstall":"sample_autoyast.xml",` by `"default_kickstart":"/var/lib/cobbler/kickstarts/sample_autoyast.xml",`. But I have no idea how to commit this diff in the release28 branch…

**Comment by SchoolGuy** [comment]
I will port these changes on the weekend. @xenlo

**Comment by xenlo** [comment]
Super, thanks!

I will run my automated cobbler import script on Monday.

**Pull request merged**
